### ISSUE TITLE
CrawlerTrait has been removed from Laravel dev-master

### ISSUE THREAD

**Issue by tacone** [orchestral/testbench#100]
It's probably too soon, to act, by the way I'm seeing this my tests:

```
Trait 'Illuminate\Foundation\Testing\CrawlerTrait' not found in /home/travis/build/tacone/bees/vendor/orchestra/testbench/src/TestCase.php on line 11
```
CrawlerTrait has been removed from Laravel as the result of their ongoing refactoring.

(I'm testing with orchestra/dev-master vs laravel/dev-master)

**Comment by crynobone** [comment]
Can you make a PR with the relevant changes?

**Comment by tacone** [comment]
I guess it is too soon to fix.

This is the commit that broke everything.
https://github.com/laravel/framework/commit/ef0e179c60c286711f1f08a4637d7c04da404c8b

**Comment by tacone** [comment]
The fix for their own tests:
https://github.com/laravel/framework/commit/6b461cafb5682627ca88041952b893f58cf5358f

**Comment by tacone** [comment]
It's working now, thank you very much.
