### ISSUE TITLE
Writing a package and getting 'Session not set on request'

### ISSUE THREAD

**Issue by bretterer** [orchestral/testbench#102]
My package uses views with forms in it.  I am using old() to get the old input if I send it back to the form.  When I do this and try to run my tests I am getting the message `Session not set on request` 

I am using v3.1 with Laravel 5.1

I have tried the following.

```
    protected function getEnvironmentSetUp($app)
    {
        $app['request']->setSession($app['session']->driver('array'));
    }
```

No luck!

What do I need to do?

**Comment by crynobone** [comment]
Can you provide an the failing code?

**Comment by bretterer** [comment]
Like I said, it is using the method `old()` in the view

```
<div class="form-group group-email">
                                <label class=col-sm-4>Email</label>
                                <div class="col-sm-8">
                                    <input type="text"
                                           class="form-control"
                                           autofocus="true"
                                           placeholder="Email"
                                           name="login"
                                           value="{{ old('login') }}"
                                    >
                                </div>
                            </div>

```

**Comment by crynobone** [comment]
Have you tried applying `withSession()`, <https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Testing/ApplicationTrait.php#L136>

**Comment by bretterer** [comment]
That does not work. 

Here is the test.

```
/** @test */
    public function it_works()
    {
        $this->visit('login');
    }
```

Here is the login page.
```
@extends('stormpath::base')

@section('title', 'Log In')
@section('description', 'Log into your account!')
@section('bodytag', 'login')

@section('content')
    <div class="container custom-container">
        <div class="va-wrapper">
            <div class="view login-view container">
                <div class="box row">
                    <div class="email-password-area col-xs-12 large col-sm-12">

                        @include('stormpath::partials._loginStatusMessages')


                        <div class="header">
                            @if(config('stormpath.web.register.enabled'))
                                Log In or <a href="{{ config('stormpath.web.register.uri') }}">Create Account</a>
                            @else
                                Log In
                            @endif
                        </div>

                        @if (isset($errors) && count($errors) > 0)
                            <div class="alert alert-danger bad-login">
                                @foreach ($errors->all() as $error)
                                    <p>{{ $error }}</p>
                                @endforeach
                            </div>
                        @endif

                        <form action="{{ config('stormpath.web.login.uri') }}" class="login-form form-horizontal" method="post"
                              role="form">
                            {{ csrf_field() }}

                            <div class="form-group group-email">
                                <label class=col-sm-4>Email</label>
                                <div class="col-sm-8">
                                    <input type="text"
                                           class="form-control"
                                           autofocus="true"
                                           placeholder="Email"
                                           name="login"
                                           value="{{ old('login') }}"
                                    >
                                </div>
                            </div>

                            <div class="form-group group-password">
                                <label class="col-sm-4">Password</label>
                                <div class="col-sm-8">
                                    <input type="password"
                                           class="form-control"
                                           placeholder="Password"
                                           name="password"
                                    >
                                </div>
                            </div>

                            <div class="col-sm-8">
                                <button class="login btn btn-login btn-sp-green" type="submit">Log In</button>
                            </div>

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
```

You can find the test case at https://github.com/stormpath/stormpath-laravel/blob/develop/tests/TestCase.php

My error is here
```
phpunit tests/Http/Controllers/ForgotPasswordControllerTest.php
PHPUnit 4.8.19 by Sebastian Bergmann and contributors.

Runtime:	PHP 5.6.15 with Xdebug 2.3.2
Configuration:	/Users/bretterer/Sites/com.stormpath.packages.laravel/phpunit.xml.dist

E

Time: 512 ms, Memory: 15.00Mb

There was 1 error:

1) Stormpath\Tests\Http\Controllers\ForgotPasswordControllerTest::it_works
ErrorException: Session store not set on request. (View: /Users/bretterer/Sites/com.stormpath.packages.laravel/src/views/login.blade.php)
```

**Comment by crynobone** [comment]
This is actually a problem with how Laravel create the request, I have submitted a bugfix for it and this should be resolved when they merged it in.

Thanks for the report.

**Comment by crynobone** [comment]
On further investigation, Our HTTP Kernel doesn't run `StartSession` middleware by default.

You can solved this by adding.

```php
    /** @test */
    public function it_works()
    {
        $this->app->make('Illuminate\Contracts\Http\Kernel')->pushMiddleware('Illuminate\Session\Middleware\StartSession');

        $this->visit('login');
    }
```

**Comment by bretterer** [comment]
That works... should I be able to run this in a setUp method so it adds for EVERY testcase by default?

**Comment by bretterer** [comment]
That fixed my issue.... I would suggest to anyone else having this issue to use the folowing code in their baseTestCase class.

```
public function getEnvironmentSetUp($app)
    {
        parent::getEnvironmentSetUp($app); // TODO: Change the autogenerated stub

        $app->make('Illuminate\Contracts\Http\Kernel')->pushMiddleware('Illuminate\Session\Middleware\StartSession');

    }
```

Thank you for the help @crynobone

**Comment by crynobone** [comment]
You should be able to run this under `setUp` or `getEnvironmentSetUp`.

I'm considering to add a method to add global middleware (just as you add package provider) as adding the middleware to `Orchestra\Testbench\Http\Kernel` could cause potential BC at the moment.

**Comment by crynobone** [comment]
Added to the README <https://github.com/orchestral/testbench#session-not-set-on-request>

Thanks for the report.

**Comment by manuelcalerosolis** [comment]
I tried to start my test but errors persist .

TestCase.php

<?php

//class TestCase extends Illuminate\Foundation\Testing\TestCase
class TestCase extends Orchestra\Testbench\TestCase
{
/**
* The base URL to use while testing the application.
*
* @var string
*/
protected $baseUrl = 'http://laravel.dev';

/**
 * Creates the application.
 *
 * @return \Illuminate\Foundation\Application
 */
public function createApplication()
{
    $app = require __DIR__.'/../bootstrap/app.php';

    $app->make(Illuminate\Contracts\Console\Kernel::class)
        ->bootstrap();

    return $app;
}

public function getEnvironmentSetUp($app)
{
    parent::getEnvironmentSetUp($app); // TODO: Change the autogenerated stub

    $app->make('Illuminate\Contracts\Http\Kernel')
        ->pushMiddleware('Illuminate\Session\Middleware\StartSession');
}
}

login.blade.php

{!! csrf_field() !!} @include('partials.errors')
{{trans('forms.email')}}
{{trans('forms.password')}}
{{trans('forms.login')}}
LoginTest.php

<?php

use \Mockery as m;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Session\Middleware\StartSession;

class LoginTest extends TestCase
{
use DatabaseMigrations;
use WithoutMiddleware;

public function testRegisterUserCreateFromForm()
{

    $this->startSession();

    $this->visit('/auth/register')
        ->type('Taylor Otwell', 'name')
        ->type('taylor@laravel.com', 'email')
        ->type('secret', 'password')
        ->type('secret', 'password_confirmation')
        ->press(trans('forms.register'))
        ->seeInDatabase('users', ['email' => 'taylor@laravel.com']);

    $this->visit('/auth/login')
        ->type('taylor@laravel.com', 'email')
        ->type('secret', 'password')
        ->press(trans('forms.login'))
        ->seePageIs('/home');

    $this->visit('auth/logout')
        ->seePageIs('/');

    $this->visit('auth/login')
        ->type('taylor@laravel.es', 'email')
        ->type('secret', 'password')
        ->press(trans('forms.login'))
        ->seeStatusCode(200);
}
}

Thanks in advance.

**Comment by crynobone** [comment]
You're overriding `createApplication()`, packages development doesn't have access to `$app = require DIR.'/../bootstrap/app.php';` as how it available for application development.

**Comment by crynobone** [comment]
And ...

```php
$this->visit('/auth/register')
        ->type('Taylor Otwell', 'name')
        ->type('taylor@laravel.com', 'email')
        ->type('secret', 'password')
        ->type('secret', 'password_confirmation')
        ->press(trans('forms.register'))
        ->seeInDatabase('users', ['email' => 'taylor@laravel.com']);

    $this->visit('/auth/login')
        ->type('taylor@laravel.com', 'email')
        ->type('secret', 'password')
        ->press(trans('forms.login'))
        ->seePageIs('/home');

    $this->visit('auth/logout')
        ->seePageIs('/');

    $this->visit('auth/login')
        ->type('taylor@laravel.es', 'email')
        ->type('secret', 'password')
        ->press(trans('forms.login'))
        ->seeStatusCode(200);
```

Each of `visit()` call should be on it's own `test*` method, so the application can be reboot on each test.

**Comment by manuelcalerosolis** [comment]
Thank you very much for answering.

About overwriting the method ' createApplication ()', I do not quite understand what it suggests to me , should I or should not overwrite ?. In fact if I do my 'test ' does not work.

Finally in my test I have left only the first visit () and does not work me.

$this->visit('/auth/register')
        ->type('Taylor Otwell', 'name')
        ->type('taylor@laravel.com', 'email')
        ->type('secret', 'password')
        ->type('secret', 'password_confirmation')
        ->press(trans('forms.register'))
        ->seeInDatabase('users', ['email' => 'taylor@laravel.com']);
 
exception 'RuntimeException' with message 'Session store not set on request.' in C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Http\Request.php:760

**Comment by crynobone** [comment]
> About overwriting the method ' createApplication ()', I do not quite understand what it suggests to me , should I or should not overwrite ?. In fact if I do my 'test ' does not work.

Are you testing an application or a package? Testbench `TestCase` are design to bootstrap Laravel for packages, not application and we have our own `createApplication()` method to handle how the to boot Laravel, replacing it would just break many of the bootstrapping process that we have.

**Comment by manuelcalerosolis** [comment]
I`m testing an application.

**Comment by crynobone** [comment]
> I`m testing an application.

Then you don't need Testbench, Just use the built-in Testing feature which is shipped with Laravel. Testbench are also utilizing that and the only different is how we boot Laravel without the app skeleton.

**Comment by manuelcalerosolis** [comment]
Sorry but I'm a bit of a novice in these matters of testing. Is not necessary to use the package for my test orchestral ?.

**Comment by crynobone** [comment]
> Is not necessary to use the package for my test orchestral ?

This package is only necessary for testing other "packages" for Laravel, when you're building an application using `laravel/laravel` all these testing features is available by default for you.

**Comment by manuelcalerosolis** [comment]
Actually it would be just inherit again ' Illuminate \ Foundation \ Testing \ TestCase ' and even my problems with the use of 'old ()' persist, Any idea how to fix it ?

**Comment by crynobone** [comment]
If you can reproduce the problem with a basic Laravel application then you could make a report to Laravel team, or you could try asking the Laravel forum.
