### ISSUE TITLE
How to test migrations for the package?

### ISSUE THREAD

**Issue by cviebrock** [orchestral/testbench#106]
I'm refactoring one of my packages for Laravel 5 -- https://github.com/cviebrock/eloquent-taggable/tree/laravel-5-refactor

One of things I have is an artisan command that creates a migration file.  Previously, I could just run the stub in my test's `setUp()` command:

```php
    public function setUp()
    {
        parent::setUp();

        // Call migrations specific to our tests, e.g. to seed the db
        $this->artisan('migrate', [
            '--database' => 'testbench',
            '--realpath' => realpath(__DIR__.'/../tests/database/migrations'),
        ]);

        // Call migrations for the package
        $this->artisan('migrate', [
            '--database' => 'testbench',
            '--realpath' => realpath(__DIR__.'/../stubs'),
        ]);
    }
```

This no longer works, and I get an error that the table that is supposed to be generated doesn't exist.

I tried another approach, by running my artisan command directly, then migrating:

```php
    public function setUp()
    {
        parent::setUp();

        // Call migrations specific to our tests, e.g. to seed the db
        $this->artisan('migrate', [
            '--database' => 'testbench',
            '--realpath' => realpath(__DIR__.'/../tests/database/migrations'),
        ]);

        // Create our tables
        $this->artisan('taggable:table');

        // Call migrations for the package
        $this->artisan('migrate', [
            '--database' => 'testbench'
        ]);
    }
```

This works perfectly the first time I run `phpunit`.  Subsequent runs, however, give me an error:

> PHP Fatal error:  Cannot redeclare class CreateTaggableTables in /Users/admin/Documents/github/cviebrock/eloquent-taggable/vendor/orchestra/testbench/fixture/database/migrations/2016_01_04_225226_create_taggable_tables.php on line 38

Any suggestions on how I can best fix this issue?  Feel free to dig through the code in my repo (https://github.com/cviebrock/eloquent-taggable/tree/laravel-5-refactor) for any details I might have left out here ... keeping in mind that the branch is still a work in progress.

Thanks!

**Comment by crynobone** [comment]
What would happen if you run `php artisan taggable:table` more than once. Does it only create the migration once or does create multiple migrations?

**Comment by cviebrock** [comment]
Well, running `phpunit` more than once creates a new migration file in `/vendor/orchestra/testbench/fixture/database/migrations` each time, so it's more about the class names for each of those migrations being the same, rather than having multiple files.

**Comment by crynobone** [comment]
That not something testbench could handle. Using a more conventional approach such as using the `vendor:publish` command could avoid this as it check for filename duplication.
