### ISSUE TITLE
mkdir(): No such file or directory

### ISSUE THREAD

**Issue by Jeroen-G** [orchestral/testbench#111]
creating a new directory is part of my package, so it also happens during tests.
I am using Laravel's Filesystem class for that. During the tests with Testbench, I get the error that Filesystem cannot create the directory because `mkdir(): No such file or directory` (which is true, it is the point of all this to make the directory exist :stuck_out_tongue_winking_eye: ).
I am guessing it has something to do with permissions (I am on Ubuntu). Could you perhaps help me out?

**Comment by crynobone** [comment]
Could you share some code related to the problem.

**Comment by Jeroen-G** [comment]
In the test
```php
if( ! $this->fs->isDirectory(base_path() . '/tests/results')) {
    $this->fs->makeDirectory(base_path() . '/tests/results');  // This is what causes the error
}
```

Illuminate/Filesystem
```php
public function makeDirectory($path, $mode = 0755, $recursive = false, $force = false)
    {
        if ($force) {
            return @mkdir($path, $mode, $recursive);
        }
        return mkdir($path, $mode, $recursive);  // This is what causes the error
    }
```

**Comment by crynobone** [comment]
That's because our dummy app doesn't have `tests` path by default. Any reason not to use `$recursive` as `true`, since it is possible someone installing your package deleted the `tests` folder.

**Comment by Jeroen-G** [comment]
Well, I didn't know what is means or is for. I'll try it and see if it works.

**Comment by Jeroen-G** [comment]
It worked, the directory got created. Editing and saving files in it is a little tricky still, but I'll figure it out. Thanks!
