### ISSUE TITLE
Route [route.name.show] not defined

### ISSUE THREAD

**Issue by josecelano** [orchestral/testbench#112]
I get that error trying to execute a test. Routes are being loading well in the application.

This is the test:

```
    /** @test */
    public function given_an_admin_is_logged_in_it_should_return_a_list_of_projects()
    {
        $admin = new User();

        $this->actingAs($admin)
            ->withSession(['foo' => 'bar'])
            ->visit('/admin/xxx/xxx')
            ->see('Projects');
    }
```

The problem occurs only when I use `route` funtion in views intead of `url`helpers:

This works:

`{{ url('admin/crowdfunding/projects', ['id' => $project->id]) }}`

This does not work:

`{{ route('admin.crowdfunding.projects.show', ['id' => $project->id]) }}`

When I use the second option I get the error:

```
ErrorException: Route [admin.crowdfunding.projects.show] not defined.
```

**Comment by crynobone** [comment]
Does this work with base Laravel app tests?

**Comment by josecelano** [comment]
Hi @crynobone , yes, if I copy the same test to the Laravel app where the package is installed, it works.

**Comment by crynobone** [comment]
Testbench only handle bootstrapping Laravel, everything else is handled by Laravel. Which version of Testbench are you using the test with?

**Comment by josecelano** [comment]
I am using the latest one: v.3.2.2. And FYI this is how I define the route:

```
Route::group(['prefix' => env('ROUTES_PREFIX', ''), 'namespace' => 'Modules\CrowdfundingLaravelBridge\Http\Controllers' , 'middleware' =>['web', 'auth']], function () {
    Route::get('/admin/crowdfunding/projects/{id}', 'Admin\ShowProjectController@__invoke')->name('admin.crowdfunding.projects.show');
});
```

**Comment by crynobone** [comment]
What the value of `env('ROUTES_PREFIX', '')` when you run the test?

**Comment by josecelano** [comment]
It's an empty string.

**Comment by josecelano** [comment]
I have the same problem in controllers.

I can not use this:

```
return redirect()->route('admin.crowdfunding.projects.show', ['id' => $newProjectId]);
````
but this works:
```
return redirect("admin/crowdfunding/projects/$newProjectId");
```

It seems named routes are not working in general.

**Comment by crynobone** [comment]
The issue was due to new fluent named route which was introduce recently. Fixed by adding `$app['router']->getRoutes()->refreshNameLookups();` during bootstrap.

**Comment by josecelano** [comment]
Ok, thank you very much @crynobone . The problem can be fixed also changing the way I define the routes:

```
Route::group(['prefix' => env('ROUTES_PREFIX', ''), 'namespace' => 'Modules\CrowdfundingLaravelBridge\Http\Controllers'], function () {
    // Backend
    Route::group(['prefix' => 'admin/crowdfunding', 'middleware' => ['web', 'auth']], function () {
        Route::get('projects/{id}', ['as' => 'admin.crowdfunding.projects.show', 'uses' => 'Admin\ShowProjectController@__invoke']);
    });
});
```

If fact, I have realixed a few minutes ago that when I run 

```
php artisan route:list
```

The name is not shown  in the list.
