### ISSUE TITLE
Correct way to override config variables

### ISSUE THREAD

**Issue by r34ch** [orchestral/testbench#115]
I am creating a laravel package. For testing purposes, the tests must run contained within the package without relying on anything from the framework which uses the package through composer.

Within `orchestra/testbench/fixture/config/auth.php` is a variable I need to change `['providers => [ 'users' => ['model' => Some\Different\Name\Space\UserModel::class]]]`

Perhaps I am going about what I am trying to do in an odd way but I am still curious how I can change the default `App\User` class (that is being used in testbench) from within my own package in the absence of `env()`.

**Comment by crynobone** [comment]
See https://github.com/orchestral/testbench#overriding-setup-method `getEnvironmentSetUp()`.
