### ISSUE TITLE
Can't change database config in Models

### ISSUE THREAD

**Issue by autn** [orchestral/testbench#118]
Hi,

This is my package: `https://github.com/autn/laravel-schema`
I'll use `orchestral/testbench` to test my package. I need change database config, I do it by:
```
$app['config']->set('database.connections.mysql', [
            'driver' => 'mysql',
            'host' => env('DB_HOST', 'localhost'),
            'port' => env('DB_PORT', '3306'),
            'database' => 'glc2',
            'username' => env('DB_USERNAME', 'root'),
            'password' => env('DB_PASSWORD', 'root'),
            'charset' => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
]);
```
It changed in test files (get right databse config), but in my Models file: `https://github.com/autn/laravel-schema/blob/master/packages/Schema/src/Console/Commands/DumpSql.php`, the `Config::get('database.connections.')` return default Laravel database config.

How to change this?

**Comment by crynobone** [comment]
Need more detail

**Comment by autn** [comment]
You can see this branch: `https://github.com/autn/laravel-schema/tree/refactor/Tests/refoctor-tests`

I changed config in TestCase: `https://github.com/autn/laravel-schema/blob/refactor/Tests/refoctor-tests/tests/TestCase.php`

I dump config (`dd(Config::get('database.connections')`) in test files: `https://github.com/autn/laravel-schema/blob/refactor/Tests/refoctor-tests/packages/Schema/tests/SchemaTest.php`

It return right config, what I changed (database, user, password...)

But get get it in Models files: `https://github.com/autn/laravel-schema/blob/refactor/Tests/refoctor-tests/packages/Schema/src/Console/Commands/DumpSql.php`

It return default Laravel database config (not like my changed)

P/s: sorry my English not good :)

**Comment by crynobone** [comment]
Your testing setup is so mess up. 

And https://travis-ci.org/autn/laravel-schema/builds/130481708 isn't even related to Testbench issue.

**Comment by crynobone** [comment]
Marking this as invalid. If database connection can't be changed in artisan environment it would be impossible to run database migration or database seeding right now.

**Comment by autn** [comment]
This is old test. I tried to test with Testbench in localhost, but I can't get expect config. I pushed this branch just to show file structures.

**Comment by crynobone** [comment]
There nothing wrong with Testbench code. Unless you can create a simple code that I can duplicate regarding this issue I'm not going to do anything about this.

**Comment by autn** [comment]
Ok, I'll add test code and will show to you.
