### ISSUE TITLE
ErrorException: file_put_contents(/meta/services.json): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by bpfruin** [orchestral/testbench#119]
I am a novice php dev and I get this error every time I try to run phpunit in my Laravel 4.2 project.  The error starts in:

vendor/orchestra/testbench/src/Testbench/TestCase.php in the setUp() function.  It propagates from there.  It looks like storage_path() is returning null and thus giving the manifest a bad path but I cannot figure out why this can be or how to fix it.  I've messed around with the 'manifest' value in my app.php file and tried to setup a special testing config file but nothing is yielding any progress or even any changes.  I still get the file_put_contents(/meta/services.json) error every time with the same path being passed into file_put_contents.

**Comment by crynobone** [comment]
I'm sorry but Laravel 4.2 (which use Testbench 2.2) is no longer supported <http://timeline.orchestraplatform.com/>
