### ISSUE TITLE
v.3.2.5: Route not defined

### ISSUE THREAD

**Issue by devsalman** [orchestral/testbench#120]
according to issue #112 this problem should've been fixed, but i still got an error in my test case. Here's my test script:

```
protected function getEnvironmentSetUp($app)
{
	$app['config']->set('database.default', 'testbench');
	$app['config']->set('database.connections.testbench', [
	    'driver'   => 'sqlite',
	    'database' => ':memory:',
	    'prefix'   => '',
	]);

	$app['config']->set('session', [
	    'driver'          => 'array',
	    'lifetime'        => 120,
	    'expire_on_close' => false,
	    'encrypt'         => false,
	    'lottery'         => [2, 100],
	    'path'            => '/',
	    'domain'          => 'localhost',
	]);

	$kernel = app('Illuminate\Contracts\Http\Kernel');
	$kernel->pushMiddleware('Illuminate\Session\Middleware\StartSession');
}

public function testSaveIngredientSuccess()
{
	$input = [
		'name' => 'Name 1',
		'description' => 'Description 1',
		'color' => '#FFFFFF',
		'category' => '1'
	];

	$response = $this->visit('POST', route('ingredient.save'), $input);
	$this->assertEquals(302, $response->status());
}
```

but, when i run PHPUnit, i still got this error:

```
1) IngredientControllerTest::testSaveIngredientSuccess
InvalidArgumentException: Route [ingredient.save] not defined.
```

I tried to change the `route` method into static path like `manages/ingredient/save` and i got `Symfony\Component\HttpKernel\Exception\NotFoundHttpException:`

This test case doesn't have problem with routing if i use `TestCase` class from laravel (but i got problem with the `Session store not set in Request` that's why i'm using this testbench)

By the way this is my routing definition:

```
Route::group(['prefix' => 'ingredients', 'as' => 'ingredient.', 'middleware' => ['permission:manage-users']], function () {
	Route::get('/', ['as' => 'index', 'uses' => 'IngredientController@index']);
	Route::get('form/{uuid?}', ['as' => 'form', 'uses' => 'IngredientController@form']);
	Route::get('data', ['as' => 'data', 'uses' => 'IngredientController@ajaxData']);
	Route::post('save', ['as' => 'save', 'uses' => 'IngredientController@save']);
	Route::post('delete', ['as' => 'delete', 'uses' => 'IngredientController@delete']);
});
```

**Comment by crynobone** [comment]
Have you tried using the available `route()` method? 

https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php#L574

And the following should be:

```php
$kernel = $app->make('Illuminate\Contracts\Http\Kernel');
```

Lastly, shouldn't you attach the middleware before setting the session, should it be after running the middleware. 

Anyhow it not a bug with Testbench (because routing is handle directly from `Illuminate\Foundation\Testing`).

**Comment by crynobone** [comment]
And to be clear, your problem isn't related to #112

**Comment by devsalman** [comment]
Hi @crynobone, thanks for the response :smile: 

> Have you tried using the available route() method?

I've tried the `route()` method but i still got the same error.

> And to be clear, your problem isn't related to #112

Hmmm.. is it because the issue #112 has `route()` problem in view? i though the problem is similar with me because the issue is in `route()`, but thanks for the correction.

**Comment by crynobone** [comment]
https://github.com/orchestral/testbench/compare/v3.2.2...v3.2.5

We haven't change anything between v3.2.2 to v3.2.5 except updating `laravel/laravel` config and updating `TestCase` based on `Illuminate\Foundation\Testing\TestCase` changes (to support phpunit ~5.0) if not mistaken.

So if it was working then, it should be working now (as proven with our updated testcase).

**Comment by crynobone** [comment]
> This test case doesn't have problem with routing if i use TestCase class from laravel (but i got problem with the `Session store not set in Request` that's why i'm using this testbench)

Seem to be more of a configuration issue. There no reason to use `orchestra/testbench` when you're working on a laravel app since you have no problem booting laravel framework. 

Testbench was design to allowed booting the framework within a Laravel packages so you can test the packages as if it was booted from a laravel application.
