### ISSUE TITLE
Migrate:rollback/DatabaseMigrations Trait

### ISSUE THREAD

**Issue by loren138** [orchestral/testbench#121]
I was wondering if their was a reason that rollback was left out of the database commands updated for use with the realpath attribute, and if you had considered implementing something like the DatabaseMigrations trait in Laravel for tests.  (The arguments would have to come from a test class property or getter function.)

I reimplemented the trait for my own use (using migrate:refresh) since migrate:rollback was unavailable.  If you would be interested in them, I could port the trait into testbench and contribute it as a pull request.  If not or if you would rather implement it yourself or have a reason you don't  want it, that's fine.

**Comment by crynobone** [comment]
You send the PR, thank you.
