### ISSUE TITLE
How to use a custom middleware?

### ISSUE THREAD

**Issue by josecelano** [orchestral/testbench#125]
Hi. I am using a custom `RoleMiddleware` in order to check roles for some routes like this:

```
Route::group(['prefix' => 'admin/xxx', 'namespace' => 'Admin', 'middleware' => ['web', 'auth', 'role:admin']], function () {
```

How can I add this middleware? I get an error in a test becuase it does not find that `RoleMiddleware ` class. Is there a way to add new middlewares without ovewriting your `Kernel` class?:

https://github.com/orchestral/testbench/blob/3.3/src/Http/Kernel.php

**Comment by crynobone** [comment]
Should be similar to https://github.com/orchestral/testbench#session-not-set-on-request

**Comment by ahinkle** [comment]
What was the solution here? I'm looking for a solution and this section was removed from the README.

**Comment by crynobone** [comment]
> What was the solution here? I'm looking for a solution and this section was removed from the README.

The section has been remove because it no longer relevant to current version. 

https://github.com/orchestral/testbench/tree/3.3#session-not-set-on-request
