### ISSUE TITLE
The "path" option does not exist

### ISSUE THREAD

**Issue by dimsav** [orchestral/testbench#126]
Hi @crynobone 

I've installed orchestra/testbench 3.3.x-dev and it seems there are some issues with the migrations reset command.

I wanted to make a pull request but couldn't find the class `Orchestra\Database\Console\Migrations\ResetCommand` anywhere in this or the database github repository.

The bug is it calls 

```php
$path = $this->input->getOption('path');
```

but `path` is not in the `getOptions()` array so we have a `Symfony\Component\Console\Exception\InvalidArgumentException` exception thrown.

You could either add it to the options or remove it completely.

**Comment by crynobone** [comment]
Pushed a fix to `orchestra/kernel` (which handle `orchestra/database` subsplit). It should be available soon.

Thank for the report.

**Comment by crynobone** [comment]
Should be fixed now. Reopen this if you still having issues.

**Comment by dimsav** [comment]
Thanks!
