### ISSUE TITLE
testbench v3.3 [Laravel 5.3]

### ISSUE THREAD

**Issue by arcanedev-maroc** [orchestral/testbench#127]
Hi @crynobone, thanks for this awesome package and i'm using it for all my laravel packages, it's a life saver 👍.

Is there any release date for the v3.3 ?

Best regards

**Comment by crynobone** [comment]
I only need to create a changelog for both testbench and database component and it should be good to go.

**Comment by arcanedev-maroc** [comment]
OK, let us know when you're done 👍

**Comment by crynobone** [comment]
Should be within the next 24 hours.

Right now you can test with Laravel 5.3 by updating the requirement to `"orchestra/testbench": "~3.3"`

**Comment by arcanedev-maroc** [comment]
Thanks man, i've just tested it and it's worked like a charm.
