### ISSUE TITLE
Custom fixture autoloading?

### ISSUE THREAD

**Issue by dmitry-ivanov** [orchestral/testbench#133]
Hi!

For my package tests I need "pre-install" fixture with route, db connect, migration, and a custom model. What is the best practice to achieve that?

I've created route, db connect, migration according to the docs. But what about custom model?
I've created `tests\fixture` folder (see pic).

It works fine, but I have to manually require model file.

Also, I've tried to copy full "fixture" folder from `orchestral` and override base path (via `getBasePath` method), but it seems to be also not supporting autoloading.

What is the best practice? Should I require all custom fixture files manually?

Thanks and have a great day!

![fixture](https://cloud.githubusercontent.com/assets/1286821/19929730/7f8e5538-a10d-11e6-812d-ad61e45593f6.png)

**Comment by crynobone** [comment]
You need to include anything that need to be autoloaded under `autoload-dev` in your package `composer.json`.

This can't be handled by `orchestra/testbench`.
