### ISSUE TITLE
Migrate:rollback in loadMigrationsFrom cannot find migrations table

### ISSUE THREAD

**Issue by CyberiaResurrection** [orchestral/testbench#134]
Shouldn't this be migrate:reset, as it looks like it's supposed to roll back all migrations, not just latest batch?

**Comment by crynobone** [comment]
https://github.com/laravel/framework/blob/5.3/src/Illuminate/Foundation/Testing/DatabaseMigrations.php#L21

Upstream using `migrate:rollback`, so does we.

**Comment by CyberiaResurrection** [comment]
Ok, fair enough. Thanks.
