### ISSUE TITLE
[PHP 7.0] PHPUnit_Framework_Exception: Segmentation fault (core dumped) while calling `vendor:publish` command

### ISSUE THREAD

**Issue by arcanedev-maroc** [orchestral/testbench#135]
Hi @crynobone,

Thanks for this great package, it's a life savior.

I need your help for an issue that i've encountered on laravel packages that i've created.

>**Note:** I think it's related only to PHP 7.0 with Travis CI.

In the local machine, i've solved the issue by making `processIsolation="true"` in the phpunit configuration file but it does not work on Travis CI.

References:
 * https://travis-ci.org/ARCANESOFT/Auth/jobs/178588567
 * https://travis-ci.org/ARCANEDEV/LogViewer/builds/178354822

Any help would be highly appreciated to solve this annoying issue.

Best regards

**Comment by crynobone** [comment]
Never has this problem before.

**Comment by arcanedev-maroc** [comment]
I cleaned the published files after each test.

I think i've forgot the main cause: **Running the tests with code coverage**

There is no issue when running tests without code coverage on PHP 7.0

**Comment by crynobone** [comment]
It would be very hard for me to debug, but I'll leave this issue open if someone else came across the same problem.
