### ISSUE TITLE
Fatal error: Trait 'Illuminate\Foundation\Testing\Concerns\ImpersonatesUsers'

### ISSUE THREAD

**Issue by lukepolo** [orchestral/testbench#136]
`Fatal error: Trait 'Illuminate\Foundation\Testing\Concerns\ImpersonatesUsers' not found in /home/travis/build/lukepolo/laracart/vendor/orchestra/testbench/src/TestCase.php on line 28`

See builds :  https://travis-ci.org/lukepolo/laracart/jobs/181709682

**Comment by lukepolo** [comment]
Guess its probably cause of this : https://github.com/laravel/framework/pull/16667/files

**Comment by crynobone** [comment]
The PR was made for Laravel 5.4, it's not a stable release yet.

**Comment by lukepolo** [comment]
Ok, well unless testbench is including master then im not sure why it would fail

**Comment by crynobone** [comment]
well, the PR made for Laravel (which you had link above) was only merged 1 day ago. I will looks into it when I'm available to work on this. Otherwise feel free to make a PR to `master` branch.

**Comment by crynobone** [comment]
> Ok, well unless testbench is including master then im not sure why it would fail

Your project version constraint (with combination to `minimum-stability` as `dev`) allows to resolve to latest master. 

![screen shot 2016-12-07 at 3 04 34 pm](https://cloud.githubusercontent.com/assets/172966/20958070/9157b588-bc8e-11e6-8e62-cf041c28689a.png)

**Comment by lukepolo** [comment]
Crap
