### ISSUE TITLE
Wont load deferred service provider in TravisCI

### ISSUE THREAD

**Issue by a-komarev** [orchestral/testbench#138]
I'm not sure it's current test bench problem. I've found an issue when tried to test my new package with deferred service provider. Locally PHPUnit passed all the tests, but TravisCI ignored my service provider.

I've placed some debug strings:
https://travis-ci.org/cybercog/laravel-ownership/jobs/184698136

> Set user model in config: Cog\Ownership\Tests\Stubs\Models\User

After setting service provider's defer attribute to `false` Travis passed the tests too:

https://travis-ci.org/cybercog/laravel-ownership/jobs/184699971

> In binding
> Get user model from config: Cog\Ownership\Tests\Stubs\Models\User

- Here is a [service provider which was ignored](https://github.com/cybercog/laravel-ownership/blob/1ceae440f30a393ffd9584b67e0a1ec198fbe97b/src/Providers/OwnershipServiceProvider.php).
- Here is main [test case which using Orchestra](https://github.com/cybercog/laravel-ownership/blob/1ceae440f30a393ffd9584b67e0a1ec198fbe97b/tests/TestCase.php).

Sorry if this bug not related to the current package.

**Comment by crynobone** [comment]
That is how deferred service provider suppose to work. Not a bug!

**Comment by a-komarev** [comment]
But why locally it's working then?

**Comment by crynobone** [comment]
Don't ask me how it works on your machine, test bench is programmed to mimic how Laravel load services, and this is how it should work

**Comment by a-komarev** [comment]
Sorry for raising it again, but as I understand service provider will be loaded only it will be called\used somewhere. And it's defined in `getPackageProviders()` method, shouldn't it be loaded in this case?

I found `App::loadDeferredProviders();` method, but not sure it's a correct solution to place it in unit tests.

**Comment by crynobone** [comment]
> Sorry for raising it again, but as I understand deferred service provider will be loaded only it will be called\used somewhere.

Please read the documentation <https://laravel.com/docs/5.3/providers#deferred-providers> and really look at the sample, especially how `register` depends on `provides` method.

**Comment by a-komarev** [comment]
I'm so dumb. Thanks @crynobone!
