### ISSUE TITLE
Suppress warning

### ISSUE THREAD

**Issue by eduardokum** [orchestral/testbench#141]
Hello,

I'm creating tests but when I run phpunit I do not get the error but if I run in the browser it fails, when I run phpunit it simply ignores the error and poses as if the variable is blank

![1ce1d04e-e150-11e6-88f2-1e4d13ba63e5](https://cloud.githubusercontent.com/assets/2566340/22219079/86e95486-e190-11e6-80b6-634849327eae.png)

Does anyone know what I can do to get the same result from the browser? Because if I do not know if the code broke.

Thanks

**Comment by crynobone** [comment]
Testbench in these case should return equivalent `500` (assuming here) that correspond to the error message page. 

If you need to fetch the raw exception, you need to throw the error from your custom exception handler instead of rendering it. <https://github.com/orchestral/testbench/blob/3.3/src/Exceptions/Handler.php#L66>

**Comment by eduardokum** [comment]
This is the point, it does not return the error page.

Let's assume:

I render a view like this:

```php
# without any params
view('view', [])
```

and I have a blade template like this:

```html
<html>
<head>
<title>test</title>
<head>
<body>
<h1>{{ $test }}</h1>
</body>
</html>
```

In the browser I get the error. 

In phpunit I get:
```html
<html>
<head>
<title>test</title>
<head>
<body>
<h1></h1>
</body>
</html>
```

**Comment by crynobone** [comment]
Can you send a PR of the failing test that showcase the example of such issue so it's easier for me to look at it.

**Comment by crynobone** [comment]
Sorry don't have time to read through someone code, if you can PR a failing test on this project that would help me solve the problem much faster.

**Comment by eduardokum** [comment]
Sorry my mistake.

I found the problem. It's php version

```php
$numero = 1;
echo $numero['asdas'];
```

this code in php 5.6 show a fatal error, but in php7 dont.

Thanks for your help.
