### ISSUE TITLE
Laravel 5.4 Support

### ISSUE THREAD

**Issue by Gummibeer** [orchestral/testbench#142]
Hey, when will `v3.4` be available with L5.4 Support?

**Comment by GrahamCampbell** [comment]
It already is available?

**Comment by GrahamCampbell** [comment]
Just set the correct min stability settings.

**Comment by GrahamCampbell** [comment]
I already test all my laravel packages using it.

**Comment by sebastiaanluca** [comment]
Getting a dependency conflict here when using with Laravel 5.4:

```
"require": {
    "php": "^7.0",
    "laravel/framework": "5.4.*"
},
```

```
- orchestra/testbench v3.3.4 requires laravel/framework ~5.3.11 -> satisfiable by laravel/framework[5.3.x-dev, v5.3.11, v5.3.12, v5.3.13, v5.3.14, v5.3.15, v5.3.16, v5.3.17, v5.3.18, v5.3.19, v5.3.20, v5.3.21, v5.3.22, v5.3.23, v5.3.24, v5.3.25, v5.3.26, v5.3.27, v5.3.28, v5.3.29] but these conflict with your requirements or minimum-stability.
- orchestra/testbench v3.3.4 requires laravel/framework ~5.3.11 -> satisfiable by laravel/framework[5.3.x-dev, v5.3.11, v5.3.12, v5.3.13, v5.3.14, v5.3.15, v5.3.16, v5.3.17, v5.3.18, v5.3.19, v5.3.20, v5.3.21, v5.3.22, v5.3.23, v5.3.24, v5.3.25, v5.3.26, v5.3.27, v5.3.28, v5.3.29] but these conflict with your requirements or minimum-stability.

- Installation request for orchestra/testbench ^3.3.4 -> satisfiable by orchestra/testbench[v3.3.4].

```

**Comment by crynobone** [comment]
What's your orchestra/testbench constraint?

**Comment by sebastiaanluca** [comment]
`"orchestra/testbench": "^3.3.4"`

**Comment by crynobone** [comment]
That doesn't permit installation anything above 3.3, update the constraint to `~3.4` etc

**Comment by sebastiaanluca** [comment]
I don't see a release tagged 3.4 yet though? Only a 3.4 branch (https://github.com/orchestral/testbench/releases).

**Comment by GrahamCampbell** [comment]
> I don't see a release tagged 3.4 yet though? Only a 3.4 branch 

Yeh, just because there's no tag, it doesn't mean you can't ask for that version.

**Comment by arcanedev-maroc** [comment]
So, is not gonna be a `3.4` tag for this package ?

**Comment by crynobone** [comment]
there will be one, when the documentation and changeling is ready. In the meantime there no reason you can't test your packages against Laravel 5.4, in fact testbench can already be tested with Laravel 5.5 since day one.

**Comment by arcanedev-maroc** [comment]
The `3.4` version is considered as an unstable version (dev version) and i don't want to mess the composer settings (only stable packages).

No problem, i'm gonna wait 😃

**Comment by crynobone** [comment]
you should be using orchestra/testbench only for require+dev, so it's irrelevant with that your are saying.

**Comment by arcanedev-maroc** [comment]
Check this @crynobone and you're going to understand the situation: https://github.com/ARCANEDEV/LogViewer/blob/master/.travis.yml#L15-L23

**Comment by crynobone** [comment]
It should have been under `require-dev`. PERIOD!

**Comment by crynobone** [comment]
https://github.com/mpociot/reauthenticate/blob/master/composer.json#L19

https://github.com/mpociot/reauthenticate/blob/master/.travis.yml#L16-L43

Of course you can simplify this using `LARAVEL_VERSION` variable.

**Comment by crynobone** [comment]
v3.4.0 has been released.

Please review the changelog https://github.com/orchestral/testbench/releases/tag/v3.4.0 for further details.
