### ISSUE TITLE
[Question] Testbench support for Laravel 5.4

### ISSUE THREAD

**Issue by arcanedev-maroc** [orchestral/testbench#143]
Hi @crynobone,

Any release date for the testbench's version 3.4 ?

Best regards

**Comment by crynobone** [comment]
You should be able to use it right now. check previous closed issue.

**Comment by arcanedev-maroc** [comment]
Duplicated: #142

**Comment by crynobone** [comment]
v3.4.0 has been released.

Please review the changelog https://github.com/orchestral/testbench/releases/tag/v3.4.0 for further details.
