### ISSUE TITLE
How to load migrations of dependecy?

### ISSUE THREAD

**Issue by rathesDot** [orchestral/testbench#145]
Hey,

I have a problem setting up my testing environment for my package. The situation is that my package depends on another of my packages, that ships with its own migrations. I'm really new into this testing stuff, so I hope someone you could help me.

As shown here: https://github.com/orchestral/testbench/blob/3.4/tests/DatabaseFixtureTest.php I did following:

```php
// in tests/TestCase.php

    /**
     * Setup the test environment.
     */
    public function setUp()
    {
        parent::setUp();

        // call migrations for packages upon which our package depends, e.g. Cartalyst/Sentry
        // not necessary if your package doesn't depend on another package that requires
        // running migrations for proper installation
        $this->loadMigrationsFrom([
            '--database' => 'testing',
            '--realpath'     => realpath(__DIR__ . '/../vendor/mastercontrol/core/database/migrations'),
        ]);

        // call migrations specific to our tests, e.g. to seed the db
        // the path option should be relative to the 'path.database'
        // path unless `--path` option is available.
        $this->loadMigrationsFrom([
            '--database' => 'testing',
            '--realpath' => realpath(__DIR__.'/../database/migrations'),
        ]);

        $this->withFactories(__DIR__ . '/../database/factories');

    }
```

This results in `ErrorException: Undefined index: 2017_01_25_150332_create_pages_table` that is the migration of my package ...

I also tried to run the migrations on my own:

```php
    /**
     * Setup the test environment.
     */
    public function setUp()
    {
        parent::setUp();

        $this->artisan('migrate', [
            '--database' => 'testing',
            '--realpath' => realpath(__DIR__ . '/../vendor/mastercontrol/core/database/migrations'),
        ]);

        $this->artisan('migrate', [
            '--database' => 'testing',
            '--realpath' => realpath(__DIR__ . '/../database/migrations'),
        ]);

        $this->withFactories(__DIR__ . '/../database/factories');

    }
```

That works fine, but I'm not sure if thats the correct way. Another way was to remove `$this->app[ConsoleKernel::class]->setArtisan(null);` from the `loadMigrationsFrom()` method ...

Thank you.

**Comment by crynobone** [comment]
Don't see what's wrong with how you do this right now.

**Comment by rathesDot** [comment]
So you say that there is nothing wrong with running the migrations with `$this->artisan('migrate', [])` instead of using `$this->loadMigrationsFrom()`

**Comment by crynobone** [comment]
if the package is properly configured, then yes.


realpath migration was added since the early 5.0 releases because Laravel decided that package developer should publish all migration to `app/database/migrations` instead running it from the packages. This however has changed since 5.1 or 5.2.

**Comment by rathesDot** [comment]
Thank you very much for your help!
