### ISSUE TITLE
Planned release for 3.4

### ISSUE THREAD

**Issue by garrensweet** [orchestral/testbench#146]
Any plans to release this soon? I know of a few packages for Laravel 5.4 that are awaiting a stable 3.4 release before they'll support 5.4.

**Comment by GrahamCampbell** [comment]
Duplicate issue. There's no requirement for there to be a tag on this repo for you to use it.

**Comment by garrensweet** [comment]
@GrahamCampbell My apologies. I should've looked. Closing.

**Comment by crynobone** [comment]
There will be a release tag soon, but I need to make sure everything is done properly:

- release note (especially regarding browserkit-testing)
- updating the documentation
- running the tests on other packages using testbench to make sure everything is fine.

But there shouldn't hold you from running and using testbench against Laravel 5.4.

**Comment by crynobone** [comment]
v3.4.0 has been released.

Please review the changelog https://github.com/orchestral/testbench/releases/tag/v3.4.0 for further details.

**Comment by Gummibeer** [comment]
The `orchestra/database` is still in dev mode.

> orchestra/testbench v3.4.0 requires orchestra/database ~3.4.0 -> satisfiable by orchestra/database[3.4.x-dev] but these conflict with your requirements or minimum-stability.

**Comment by crynobone** [comment]
@Gummibeer read e80767d56bb34036d2520bd69d67fc09433e069c 

`v3.4.1` coming right up.
