### ISSUE TITLE
Version 3.4.0 has "dev" as minimum stability, cannot require package

### ISSUE THREAD

**Issue by aedart** [orchestral/testbench#147]
Hi there - would it be possible to release your `testbench`, `database` and other nested depedencies as "stable"?

At the moment, I am not able to require `testbench`, into a "stable" package, due to this issue.

**Comment by crynobone** [comment]
Use minimum `"dev"` with prefer stable.

**Comment by aedart** [comment]
Ty mate- that solved it :)

**Comment by crynobone** [comment]
Personally, most packages should stick with "dev" as minimum stability and test `--prefer-lowest`, `--prefer-stable` on every supported Laravel najor release via Travis-CI
