### ISSUE TITLE
 Class 'Orchestra\Database\ConsoleServiceProvider' not found, version 3.4.1

### ISSUE THREAD

**Issue by aedart** [orchestral/testbench#149]
You removed the "database" dependency (in version 3.4.1), yet the `vendor/orchestra/testbench/fixture/config/app.php` still requires it.

**Comment by crynobone** [comment]
can you make a PR to remove that

**Comment by aedart** [comment]
5 min...

**Comment by crynobone** [comment]
never mind, done it on GitHub UI (via phone)

**Comment by crynobone** [comment]
tag version in 2 min

**Comment by aedart** [comment]
ah - ty... was tinkering around with "fetch upsteam" merges..
