### ISSUE TITLE
$this->action() call fails after upgrade to Laravel 5.4

### ISSUE THREAD

**Issue by aimeos** [orchestral/testbench#150]
This fails after upgrading to Laravel 5.4 even with `orchestra/testbench-browser-kit` installed:
```
$response = $this->action('GET', '\Aimeos\Shop\Controller\AccountController@indexAction', ['site' => 'unittest']);
```
with
```
Error: Call to undefined method AccountControllerTest::action()
```
Do can we get around this while maintaining compatibility to Laravel 5.1/5.2/5.3?

**Comment by GrahamCampbell** [comment]
> This fails after upgrading to Laravel 5.4 even with orchestra/testbench-browser-kit installed:

You'll have to do more than just "installing the package".

**Comment by aimeos** [comment]
Using `Orchestra\Testbench\BrowserKit\TestCase` instead of `Orchestra\Testbench\TestCase` is not compatible with 5.1 to 5.3

**Comment by GrahamCampbell** [comment]
Yes, well. Looks like it's not easily possible to support both.

**Comment by GrahamCampbell** [comment]
:/

**Comment by crynobone** [comment]
Done.

https://packagist.org/packages/orchestra/testbench-browser-kit
