### ISSUE TITLE
Class not found PHPUnit\Framework\TestCase

### ISSUE THREAD

**Issue by nWidart** [orchestral/testbench#151]
Hello,

I'm in the process of upgrading to laravel 5.4 on a package. However tests are crashing with the following error:

```
PHP Fatal error:  Class 'PHPUnit\Framework\TestCase' not found in /Users/nicolaswidart/Sites/Packages/laravel-menus/vendor/orchestra/testbench/src/TestCase.php on line 22
```

However when changing the following in `Orchestra\Testbench\TestCase`

```
use PHPUnit\Framework\TestCase as BaseTestCase;
```

To:

```
use PHPUnit_Framework_TestCase as BaseTestCase;
```

It works.
I'm using version 3.4.2 on testbench. I see in those release notes that this was fixed, which is weird.

Thanks

**Comment by brayniverse** [comment]
What version of phpunit are you pulling in?

**Comment by nWidart** [comment]
`4.8.34`. 
Weird is that I see this change https://github.com/orchestral/testbench/commit/ba4b3eddfd26fc8721cf2614de70df8a9289c385 which I don't see locally.

**Comment by crynobone** [comment]
It's part of `v3.4.2` changelog.

<https://github.com/orchestral/testbench/releases/tag/v3.4.2>

Testbench v3.4.0 above now requires PHPUnit 5.7 as suggested in our composer.json <https://github.com/orchestral/testbench/blob/3.4/composer.json#L38>

**Comment by crynobone** [comment]
It not really on our full changelog because this was done in the core of Laravel, where there also bump up the minimum deps to `~5.7`.

**Comment by nWidart** [comment]
I see. Thank you, updated phpunit to 5.7 did the trick.

Thanks for the very quick reply as always! 👍

**Comment by sebastiaanluca** [comment]
Using 3.4.0 in combination with PHPUnit 5.7 or 6 seems to fail with the same class not found error. Noticed this when testing my package using TravisCI. I need to specifically install version 3.4.2, am I missing something here?

The only combination that works for Laravel 5.4 when testing the most minimal requirements:
```
ILLUMINATE_VERSION="5.4.*" ORCHESTRA_VERSION="^3.4.2" PHPUNIT_VERSION="6.*" COMPOSER_FLAGS="--prefer-lowest"
```

**Comment by crynobone** [comment]
3.4 only support PHPUnit 5.7, 3.5 will only support PHPUnit 6.0
