### ISSUE TITLE
Orchestra database version not exists

### ISSUE THREAD

**Issue by a-komarev** [orchestral/testbench#155]
> Exception: Missing `orchestra/database` in composer.json

```js
"require": {
    "php": "^5.6|^7.0",
    "illuminate/database": "~5.2.0|~5.3.0|~5.4.0",
    "illuminate/support": "~5.2.0|~5.3.0|~5.4.0"
},
"require-dev": {
    "orchestra/testbench": "~3.0",
    "phpunit/phpunit": "^5.2"
},
```

Latest version of test bench require `"orchestra/database": "~3.4.0"`, but latest release is 3.3.5!

**Comment by crynobone** [comment]
Use minimum stability dev!!

**Comment by a-komarev** [comment]
I've added orchestra database as dev:
```
"orchestra/database": "@dev",
```

And updated realpath usage:
```
$this->loadMigrationsFrom([
'--realpath' => realpath(__DIR__ . '/database/migrations'),
]);
$this->artisan('migrate');
```

Package was found, installed, but PHPUnit tests are broken:

> Symfony\Component\Console\Exception\InvalidOptionException: The "--realpath" option does not exist.

Then I've tried to set `"minimum-stability": "dev"`. Composer fetched all packages from dev-master but there is the initial error too:

> Exception: Missing orchestra/database in composer.json

**Comment by a-komarev** [comment]
This way I've sticked to stable versions, but still not working.
```
"minimum-stability": "dev",
"prefer-stable" : true
```

If add `"orchestra/database": "@dev",` to this config - everything works, but it will use Laravel 5.3.x & `orchestra/database v3.3.5`.

**Comment by crynobone** [comment]
> I'm not sure that using of dev minimum-stability is a good idea, because it will fetch all packages as dev-master, which could be unstable.

User should use `minimum-stability` as `dev` and test using `--prefer-stable`, `--prefer-lowest`, latest dev on travis. See https://github.com/orchestral/testbench/blob/3.4/.travis.yml as example

**Comment by a-komarev** [comment]
@crynobone I'll look on it, but I can't fix my tests anyway, with `minimum-stability` as `dev` they aren't working too!

**Comment by crynobone** [comment]
Sorry, I need to edit it because I don't want that to be the solution when someone read this thread/issue.

**Comment by a-komarev** [comment]
@crynobone I've posted [new branch](https://github.com/cybercog/laravel-ownership/tree/feature/laravel-5.4-support) to my package to show you whats happening: https://travis-ci.org/cybercog/laravel-ownership/builds/199225333
It's failing with all changes I've tried above.

**Comment by crynobone** [comment]
```json
    "require-dev": {
        "friendsofphp/php-cs-fixer": "^1.11",
        "mockery/mockery": "^0.9.5",
        "orchestra/testbench": "~3.4.0",
        "orchestra/database": "~3.4.0",
        "phpunit/phpunit": "^5.2"
    },
```

`"phpunit/phpunit": "^5.2"` this is useless since Laravel 5.4 requires `"~5.7"`

**Comment by a-komarev** [comment]
This will produce the error:
> Symfony\Component\Console\Exception\InvalidOptionException: The "--realpath" option does not exist.

Accordingly PHPUnit, it will use `5.7` anyway, because `^5.2` includes `5.7` too.

**Comment by crynobone** [comment]
```json
"require": {
        "php": "^5.6|^7.0",
        "illuminate/database": "~5.2.0|~5.3.0|~5.4.0",
        "illuminate/support": "~5.2.0|~5.3.0|~5.4.0"
    },
    "require-dev": {
        "friendsofphp/php-cs-fixer": "^1.11",
        "mockery/mockery": "^0.9.5",
        "orchestra/testbench": "~3.4.0",
        "phpunit/phpunit": "^5.2"
    },
```

This is why I really disagree with just checking against `"latest stable"`, You are suggesting that this package works with Laravel `~5.2.0`, `~5.3.0` and `~5.4.0`. However you're only loading  `"orchestra/testbench": "~3.4.0"` which only test against "latest stable" of Laravel 5.4. Do your code really work with 5.2 and 5.3? Travis doesn't check this.

**Comment by a-komarev** [comment]
Yes... travis isn't testing it, but I'm using this code in 5.2 and 5.3 projects.

**Comment by crynobone** [comment]
Read https://github.com/orchestral/testbench#realpath-migration

The code is working, otherwise Testbench own test would have failed https://github.com/orchestral/testbench/blob/3.4/tests/DatabaseWithCustomMigrationFixtureTest.php#L29

**Comment by a-komarev** [comment]
@crynobone I know about this changes, and that's why I've done this: https://github.com/cybercog/laravel-ownership/blob/feature/laravel-5.4-support/tests/TestCase.php#L72

**Comment by crynobone** [comment]
READ THE README!

![screen shot 2017-02-07 at 10 44 33 pm](https://cloud.githubusercontent.com/assets/172966/22695807/04985de4-ed87-11e6-8229-3ae3173b97a8.png)
