### ISSUE TITLE
ReflectionException: Class App\Console\Kernel does not exist

### ISSUE THREAD

**Issue by xoco70** [orchestral/testbench#160]
Hi, 

I'm trying to use TestBench to develop my Laravel plugin with Functional tests.

here is my TestCase.php,  I changed
`use Illuminate\Foundation\Testing\TestCase as BaseTestCase;`

by 

` use Orchestra\Testbench\TestCase as BaseTestCase;`

```<?php

namespace Xoco70\KendoTournaments\Tests;

use App\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Lang;
use Orchestra\Testbench\TestCase as BaseTestCase;
use Xoco70\KendoTournaments\TournamentsServiceProvider;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    protected function getPackageProviders($app)
    {
        return [TournamentsServiceProvider::class];
    }


    /**
     * Setup the test environment.
     */
    public function setUp()
    {
        parent::setUp();
        $this->root = factory(User::class)->create(['role_id' => Config::get('constants.ROLE_SUPERADMIN')]);
        $this->logWithUser($this->root);

    }

    /**
     * @param \App\User $newUser
     */
    public function logWithUser(User $newUser){
        Auth::loginUsingId($newUser->id);
        Lang::setLocale($newUser->locale);
    }
}
```
But I get 

> 1)   ##Xoco70\KendoTournaments\Tests\PreliminaryTreeTest::check_number_of_row_when_generating_tournament
> ReflectionException: Class App\Console\Kernel does not exist

> /Users/juliencappiello/Documents/Proyectos/tournament-plugin/package/xoco70/kendo-tournaments/vendor/laravel/framework/src/Illuminate/Container/Container.php:681
> /Users/juliencappiello/Documents/Proyectos/tournament-plugin/package/xoco70/kendo-tournaments/vendor/laravel/framework/src/Illuminate/Container/Container.php:565
> /Users/juliencappiello/Documents/Proyectos/tournament-plugin/package/xoco70/kendo-tournaments/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:702
> /Users/juliencappiello/Documents/Proyectos/tournament-plugin/package/xoco70/kendo-tournaments/vendor/laravel/framework/src/Illuminate/Container/Container.php:239
> /Users/juliencappiello/Documents/Proyectos/tournament-plugin/package/xoco70/kendo-tournaments/vendor/laravel/framework/src/Illuminate/Container/Container.php:678
> /Users/juliencappiello/Documents/Proyectos/tournament-plugin/package/xoco70/kendo-tournaments/vendor/laravel/framework/src/Illuminate/Container/Container.php:565
> /Users/juliencappiello/Documents/Proyectos/tournament-plugin/package/xoco70/kendo-tournaments/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:702
> /Users/juliencappiello/Documents/Proyectos/tournament-plugin/package/xoco70/kendo-tournaments/tests/CreatesApplication.php:18
> /Users/juliencappiello/Documents/Proyectos/tournament-plugin/package/xoco70/kendo-tournaments/vendor/orchestra/testbench/src/TestCase.php:102
> /Users/juliencappiello/Documents/Proyectos/tournament-plugin/package/xoco70/kendo-tournaments/vendor/orchestra/testbench/src/TestCase.php:81
> /Users/juliencappiello/Documents/Proyectos/tournament-plugin/package/xoco70/kendo-tournaments/tests/TestCase.php:27

it comes with instruction : 

 `parent::setUp();`

this happens because I have in my trait : CreatesApplication a reference to  Illuminate\Contracts\Console\Kernel;

 
```
<?php

namespace Xoco70\KendoTournaments\Tests;

use Illuminate\Contracts\Console\Kernel;

trait CreatesApplication
{
    /**
     * Creates the application.
     *
     * @return \Illuminate\Foundation\Application
     */
    public function createApplication()
    {
        $app = require __DIR__.'/../../../../bootstrap/app.php';

        $app->make(Kernel::class)->bootstrap();

        return $app;
    }
}
```

I tried others route to Kernel Class, but none worked...

If I remove trait : use CreatesApplication; app is not boostraping anymore.

What should I do???

**Comment by crynobone** [comment]
```php
$app = require __DIR__.'/../../../../bootstrap/app.php';
```

This is booting Laravel Application, not Testbench fixture application.

There no guide in Testbench that ever uses `CreatesApplication` trait.

**Comment by xoco70** [comment]
ok, but how should I boot testBench fixture... my TestCase file follows the guide, but it is not loading -> now I get : 


   ` Class 'App\Http\Controllers\Controller' not found ``

What am I missing???

**Comment by crynobone** [comment]
@xoco70 you should never depends on `App\Http\Controllers\Controller`, what would happen if someone rename the default app namespace to `Acme` using `php artisan app:name Acme`?

**Comment by xoco70** [comment]
It would generate a conflict? It's my first plugin, and I followed this [tuto](http://laraveldaily.com/how-to-create-a-laravel-5-package-in-10-easy-steps/), using Controllers...

So, what should I use, any good tuto you can advise??? Or, How should I avoid  using controllers?

**Comment by crynobone** [comment]
You could directly use `Illuminate\Routing\Controller`

**Comment by xoco70** [comment]
Tx! I think it will do the trick! Tx for your advices, and for your plugin!

**Comment by xoco70** [comment]
oooo, now I understand what you was saying. If I use any App\ reference, and programmer change App\ namespace, plugin will break!!!

Ok, so the solution if I need App\User, you should set it on config file, so it can be changed, am I right???

**Comment by crynobone** [comment]
> Ok, so the solution if I need App\User, you should set it on config file, so it can be changed, am I right???

Yes.
