### ISSUE TITLE
Error: Class 'App\User' not found

### ISSUE THREAD

**Issue by xoco70** [orchestral/testbench#161]
I spent all day on that, can't make it work :(

```
use App\User;

public function setUp()
    {
        parent::setUp();
        $this->artisan('migrate', [
            '--realpath' => realpath(__DIR__ . '/../database/migrations'),
        ]);
      $this->withFactories(__DIR__ . '/../database/factories');
        $this->root = factory(User::class)->create();
}
```

At this point, I can see all my tables created in DB, but can't find  `App\User;`

The project depends on `App\User;` and in my case, class exists, so what's wrong???

I know depending on App\ is bad, but later, i will probably implement config like mentioned here : [https://github.com/orchestral/testbench/issues/137](https://github.com/orchestral/testbench/issues/137)

But for now, I'm ok to hardcode it, I just want to make it work....

**Comment by crynobone** [comment]
I would suggest using a stub model, refer to https://github.com/laravie/authen/tree/master/tests for such example.

If you just using a basic User model without any modification, you definitely can use `Illuminate\Foundation\Auth\User` as the base model.

**Comment by xoco70** [comment]
you rock! Tx!
