### ISSUE TITLE
Error: Call to undefined method Xoco70\KendoTournaments\Tests\PreliminaryTreeTest::visit()

### ISSUE THREAD

**Issue by xoco70** [orchestral/testbench#163]
Why would it gives me this error???? visit() is part of Laravel testing suite

Here is the problematic function:

``` 
public function generatePreliminaryTree(Tournament $tournament)
    {
        $this->visit('/tournaments/' . $tournament->slug . "/edit")
            ->click('#competitors')
            ->press('generate');
    }
```

It works well when I test it with my main app.

**Comment by crynobone** [comment]
BrowserKit testing is available on a separate project as mention in our FAQ.

https://github.com/orchestral/testbench#missing-browser-kit-support-after-testing-on-laravel-54
