### ISSUE TITLE
$this->visit('/') gives me a 404

### ISSUE THREAD

**Issue by xoco70** [orchestral/testbench#164]
Hi, 

when I hit $this->visit('http://tournament-plugin.dev/') method in my test, phpunit send me a 404,

but the URL exists, when I copy it in browser.

I also have routes

```$router->group(['prefix' => 'kendo-tournaments', 'middleware' => ['web']], function ($router) {
            $router->get('/', 'Xoco70\KendoTournaments\TreeController@index')->name('tree.index');
            $router->post('/championships/{championship}/trees', 'Xoco70\KendoTournaments\TreeController@store')->name('tree.index');
        });
```

So basically, $this->visit('http://tournament-plugin.dev/kendo-tournaments') should also work, and it gives me a 404...

Why is it happening???

**Comment by crynobone** [comment]
https://github.com/orchestral/testbench-browser-kit/blob/3.4/src/TestCase.php#L54

**Comment by xoco70** [comment]
It's becoming weird.

When I change $baseUrl or I harcode it, I get a 404 ( But URL exists)

When I specially hit this url: `$this->visit('/kendo-tournaments');`

I get : `RuntimeException: The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.`
But I checked in config/app.php

`'cipher' => 'AES-256-CBC',`

Also, when running phpunit in my main app, $baseURL = "http://localhost" and it still works fine ( In browser, I access it via : http://laravel.dev

So, I guess it should also work here...

**Comment by crynobone** [comment]
> RuntimeException: The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.

https://github.com/orchestral/testbench#no-supported-encrypter-found-the-cipher-and--or-key-length-are-invalid
