### ISSUE TITLE
config('kendo-tournaments.default_settings') gives me NULL

### ISSUE THREAD

**Issue by xoco70** [orchestral/testbench#165]
Hi, 

It's taking a little longer than I thought :(

when I try to get a value from a config file, with:

`config('kendo-tournaments.default_settings')`

it returns null. 

Thing is when I open it in browser, I can reach this data.

this config file is located in: `/package/xoco70/kendo-tournament/config/kendo-tournaments.php`

Do you know why???

**Comment by crynobone** [comment]
https://laravel.com/docs/5.4/packages#configuration

![screen shot 2017-02-18 at 11 57 07 am](https://cloud.githubusercontent.com/assets/172966/23090142/6a26f5a6-f5d1-11e6-866c-f77b3c7414e1.png)
