### ISSUE TITLE
Class 'Form' not found

### ISSUE THREAD

**Issue by xoco70** [orchestral/testbench#166]
Sorry to bother you again.

I get this error `Class 'Form' not found` because I use Form::open() in my views.

So, I tried to include it in TestCase.php

```
use \Collective\Html\FormFacade;
use \Collective\Html\HtmlFacade;
use \Collective\Html\HtmlServiceProvider;

abstract class TestCase extends BaseTestCase{


protected function getPackageProviders($app)
    {
        return [TournamentsServiceProvider::class,
            ConsoleServiceProvider::class,
            HtmlServiceProvider::class,
        ];
    }

protected function getPackageAliases($app)
    {
        return [
            'Form'      => FormFacade::class,
            'Html'      => HtmlFacade::class,
        ];
    }

}```

But now I get : `Error: Class 'Collective\Html\HtmlServiceProvider' not found` 

Why is it happening???

**Comment by crynobone** [comment]
Don't expect me to solve all your problem. If the class is missing, there something wrong with that. This has nothing to do with Testbench

**Comment by xoco70** [comment]
Sorry, I have so much trouble to make it work that it is sometimes difficult to know which one is from the plugin, and which one is not! Tx for your help with the plugin!!!

**Comment by crynobone** [comment]
>  I have so much trouble to make it work that it is sometimes difficult to know which one is from the plugin

Testbench loads Laravel, Testbench has no idea about any other 3rd party package that your package may need to require. So do you have `laravelcollective/html` in the `composer.json`, which is needed to pull in the package during testing? 

https://github.com/xoco70/kendo-tournaments/blob/master/composer.json#L30-L44
