### ISSUE TITLE
Prevent multiple migrate:rollback on beforeApplicationDestroyed

### ISSUE THREAD

**Issue by a-komarev** [orchestral/testbench#168]
If `loadMigrationsFrom` method will be called multiple times - test bench will crash on the rollback. Because it's registering this action twice. First rollback will be successful and the second one will crash an app.

```php
$this->beforeApplicationDestroyed(function () use ($options) {
    $this->artisan('migrate:rollback', $options);
});
```

Use case:

```php
// Migrating package migrations
$this->loadMigrationsFrom([
    '--realpath' => database_path('migrations'),
]);

// Migrating unit test migrations
$this->loadMigrationsFrom([
    '--realpath' => realpath(__DIR__ . '/database/migrations'),
]);
```

**Comment by crynobone** [comment]
If you have a solution for this, feel free to submit a PR.

**Comment by a-komarev** [comment]
Tried to fix this but no luck still. Will try to find the way to solve this later this week because it's blocking the upgrade of some of my packages.

**Comment by crynobone** [comment]
Could you do me a favour and try with the following changes:

```php
    /**
     * Register a callback to be run before the application is destroyed.
     *
     * @param  callable  $callback
     *
     * @return void
     */
    protected function beforeApplicationDestroyed(callable $callback)
    {
        array_unshift($this->beforeApplicationDestroyedCallbacks, $callback);
    }
```

**Comment by a-komarev** [comment]
@crynobone It works! I haven't checked if database migrations are rolled back correctly between tests, but no errors with this fix.

**Comment by a-komarev** [comment]
Should I make a PR for it or you will do it?

**Comment by crynobone** [comment]
That's is good news, use that first on your projects and feel free to submit a PR once you're confident with the fix.

To confirm, the following tests in the same class shouldn't have any data (created from factory) from the previous tests.

**Comment by a-komarev** [comment]
@crynobone Thanks for a such a quick resolution as always!

**Comment by crynobone** [comment]
> Should I make a PR for it or you will do it?

Everything works great right? can you make the PR to branch `3.1` for this

**Comment by a-komarev** [comment]
@crynobone Yes. It works well for my case. Why to 3.1? I thought it should be pointed to 3.4.
