### ISSUE TITLE
Missing 'Bus' as class Alias

### ISSUE THREAD

**Issue by RikSomers** [orchestral/testbench#170]
Hi!

A couple of weeks ago, Laravel added the `Bus` facade for testing, and added it in the default [alias array]( https://github.com/laravel/laravel/blob/master/config/app.php#L200). The Bus facade is however not added in the aliases array in testbench.

This will result in an error when using `Bus::Fake()` in your tests.

- Rik

**Comment by crynobone** [comment]
should be fixed in latest dev.

**Comment by RikSomers** [comment]
Thanks. Issue should be resolved then :)
