### ISSUE TITLE
Database --realpath problem

### ISSUE THREAD

**Issue by actuallymab** [orchestral/testbench#172]
Hi,

When I try to load migrations with realpath option I just started to get `Symfony\Component\Console\Exception\LogicException: An option named "path" already exists.` exception. My package was passing whole tests before last update. So I think somewhere broken with realpath.

**Comment by a-komarev** [comment]
Confirming. All tests was worked before package update.

> - Removing orchestra/testbench (v3.4.5)
> - Installing orchestra/testbench (v3.4.6)

**Comment by a-komarev** [comment]
It seems not a Testbench problem. I've rolled back to 3.4.5 but issue still exists.

**Comment by a-komarev** [comment]
It's an issue in `laravel/framework 5.4.17`.

**Comment by crynobone** [comment]
Should be fixed now.

**Comment by spawnia** [comment]
This describes how to resolve the issue when using Laravel 5.5:

https://github.com/orchestral/testbench/tree/3.5#running-testing-migrations
