### ISSUE TITLE
tearDown ReflectionException: Class config does not exist

### ISSUE THREAD

**Issue by developerMerna** [orchestral/testbench#173]
this is my setup function for login user
  public function setUp(){
        parent::setUp();
        $this->user = factory(App\User::class)->create([
	            'email' => 'testuser@email.com',
	            'password' => bcrypt($this->password),
	            'type' => 'admin'
        		]);
    }
and this is 
	public function tearDown(){
        parent::tearDown();
        $this->user->delete();
    }

i got this error
tearDown
ReflectionException: Class config does not exist

How i can solve it?

**Comment by crynobone** [comment]
`parent::tearDown();` would flush Laravel `app` instance and any declared instance/service provider including `config`.

**Comment by developerMerna** [comment]
@crynobone Thank you but  I am not understand your comment

**Comment by GrahamCampbell** [comment]
Call parent after.

**Comment by developerMerna** [comment]
in the end of setup function?

**Comment by developerMerna** [comment]
@GrahamCampbell  i try put it after create user but sadlly its not work :)

**Comment by crynobone** [comment]
```php
public function tearDown()
{
    // do whatever you need to do while still interacting with the app.
    parent::tearDown();
}
```

**Comment by crynobone** [comment]
Or

```php
public function setUp()
{
    parent::setUp();
    
    $this->user = factory(App\User::class)->create([ ... ]);

    $this->beforeApplicationDestroyed(function () {
        $this->user->delete();
    });
}
```

**Comment by developerMerna** [comment]
and in test function how i can use the user ??
because it give me undefined user

**Comment by crynobone** [comment]
I would prefer to keep this focus on bug reports, personally been using factories and it is fine with Testbench.
