### ISSUE TITLE
HTTP request caching error?

### ISSUE THREAD

**Issue by derrekbertrand** [orchestral/testbench#174]
I don't know if this is an error with Orchestral Testbench, Laravel's tests, or my ineptitude.

In one of my projects, I kept getting old responses in certain instances. If, within a single test, you make a request to the same route multiple times, you end up with the same response, even though the data may have changed. HTTP status code, data, it is all carried over.

Doing this between tests, but within the same suite class does not have this issue. You can hit the same route as many times as you like, just not within one test.

I have replicated the problem and stripped away as much junk as I can. You can [check it out here](https://github.com/derrekbertrand/testbenchtest).

### General Info:
PHP: 7.0 & 7.1
phpunit: 5.x branch
Laravel: 5.3

### Use Case:
GET /api/v1/user/1 -> should return 404, we did not seed
GET /api/v1/user -> should return empty set
POST /api/v1/user -> should create user
GET /api/v1/user/1 -> should return new user; **fails, returns old 404**
GET /api/v1/user -> should return set of 1 users; **fails, returns old empty set**

**Comment by crynobone** [comment]
Orchestra Testbench doesn't change anything about the original request. We just bootstrap Laravel outside of a standard Laravel skeleton application.
