### ISSUE TITLE
Please solve the readme file

### ISSUE THREAD

**Issue by SerbanBlebea** [orchestral/testbench#175]
Very difficult to understand readme file.

What do you mean by:
"Warning: --realpath support has been deprecated in favour of ServiceProvider::loadMigrationsFrom()."

First you talk about using --realpath (witch doesn't work) and at the end you specify use ServiceProvider with a protected method. (witch doesn't work).

Should this be used in TestCase or somewhere else?

**Comment by crynobone** [comment]
> Should this be used in TestCase or somewhere else?

As a package developer (which most of Testbench user use this package for) should already gone through the official Laravel [Package Development Documentation](https://laravel.com/docs/5.4/packages), and come across these note:

![screen shot 2017-05-14 at 7 11 15 pm](https://cloud.githubusercontent.com/assets/172966/26033183/295236bc-38d9-11e7-9abd-86a101046589.png)

So if there anything more than you think should be in Testbench Readme, do make a Pull Request for it.

**Comment by spawnia** [comment]
This describes how to resolve the issue when using Laravel 5.5:

https://github.com/orchestral/testbench/tree/3.5#running-testing-migrations
