### ISSUE TITLE
Route model binding not working

### ISSUE THREAD

**Issue by ingro** [orchestral/testbench#177]
Hello and thanks for this great package!

However I have an issue: I'm testing a controller that is expected to work with laravel's [route model binding](https://laravel.com/docs/5.4/routing#route-model-binding).

So this is how the `setUp` method of my `TestCase` class appear:

```php
Route::model('post', Post::class);
        
Route::get('posts', '\App\Http\Controllers\PostController@index');
Route::get('posts/{post}', '\App\Http\Controllers\PostController@show');
```

But it's not working, in the `show` method of my Controller the first parameter is always a string and not a `Post` model.

I'm doing something wrong or this is something which testbench doesn't support yet?

Thank you.

**Comment by crynobone** [comment]
Have you added `bindings` route middleware to those routes?

**Comment by ingro** [comment]
That indeed fixed my problem, I wasn't aware that a middleware was needed for bindings to work, thanks and sorry again for opening this.

**Comment by ajcastro** [comment]
@crynobone @ingro newbie question. 
how do you add the bindings? any link pls? thanks!

**Comment by ingro** [comment]
@ajcastro I'm not really using this library anymore but for what I can remember you should explicitly add the `bindings` middleware to your route like this:

```php
Route::get('posts/{post}', '\App\Http\Controllers\PostController@show')->middleware('bindings');
```

That's just an example anyway, you can set it to a Route group so you don't have to write it down for each route.

**Comment by ajcastro** [comment]
@ingro why don't use this anymore? and what are you currently using for package development?

**Comment by ingro** [comment]
Sadly I'm not using Laravel anymore at work, but for what I can say this library was very helpful when I had the chance to use it

**Comment by ajcastro** [comment]
Yes, this seems to be the accepted and official library for package development.

**Comment by calebdw** [comment]
To folks that may stumble on this in the future, you'll have to use the following:

```php
Route::get(...)->middleware(SubstitutesBindings::class);
```
