### ISSUE TITLE
Created classes not found

### ISSUE THREAD

**Issue by OliverZiegler** [orchestral/testbench#184]
Hi there,

I currently develop a package that writes some class files in a laravel application to speed up development.

When trying to test this, the class file will be written to `vendor/testbench-core/fixtures/app`.
So after generation I have a class `FooBar` in `vendor/testbench-core/fixtures/app/FooBar.php` with `namespace App`.

Checking if file was written works like this
```PHP
$this->assertFileExists(base_path('/app/FooBar.php'));
```

I now want to write the test if the generated class can be used (and other method tests for this generated class) to verify the correctness of the class stub.
When I use
 ```PHP
$foobar = new \App\FooBar();
$this->assertInstanceOf('App/FooBar', $foobar);
```

I get an error that the class `\App\FooBar` is not found.

How can I instantiate the class?
Do I need some special composer autoload setup?
Or should this be tested with a real and complete Laravel application?

Appreciate your help :)

**Comment by crynobone** [comment]
there no autoloading for "App" namespace, you should actually check for file existing and check for it's content.

**Comment by OliverZiegler** [comment]
I see... but checking content will not verify if methods can be called, are correct etc.
Is there any other approach to be able to test stuff like this?

As the class is generated out of mutliple stubs and with some name replacements it is necessary to test the logic and not only content.

**Comment by crynobone** [comment]
https://github.com/orchestral/testbench#why-testbench-doesnt-include-any-of-the-app-classes

**Comment by OliverZiegler** [comment]
As my package *generates* these classes an I just want to verify generating *valid* and *working* classes it's not like I rely on the app-classes.

But I just managed to get this working by require-dev the whole laravel/laravel package for my tests. As I also need to verify user model creation, and working guards and login, I think this is the only reliable way for this kind of integration tests. My package itself just works as a file generator or appender. So the main functionality is not relying on any app classes but the generated ones.

**Comment by MarekGogol** [comment]
Hello,

I have same problem. Googling, stackowerflowing, but I can't find any correct way for solving this particular case. My package generates files in app/ folder, and then this package loads them for some purposes... How is correct way to load this files with namespaces from app folder in tests?

Thanks,

**Comment by calebporzio** [comment]
I ran into this same problem. To solve it, add the following snippet to the composer.json of your package:

```
"autoload-dev": {
        "psr-4": {
            "App\\": "vendor/orchestra/testbench-core/laravel/app"
        }
    },
```

Kinda hacky, but it does the trick.

**Comment by crynobone** [comment]
@calebporzio is the project you working on opensourced?

**Comment by calebporzio** [comment]
Not yet, will be. Why do you ask?

**Comment by crynobone** [comment]
Wondering if we can use `phpunit.xml` bootstrap file configuration to set a custom bootstrap file and register the namespace from there.

```php
<?php

$loader = require "vendor/autoload.php";

$loader->setPsr4('App\\', 'vendor/orchestra/testbench-core/laravel/app');
```

**Comment by calebporzio** [comment]
Yeah, I suppose I could. Are there any advantages to that approach? None come to mind.

**Comment by crynobone** [comment]
No actually, just wondering which method to promote if this is included in the troubleshooting section on the documentation

**Comment by calebporzio** [comment]
Ah, I would think adding it to the composer.json would have a lower barrier to entry.

**Comment by mtolhuys** [comment]
> I ran into this same problem. To solve it, add the following snippet to the composer.json of your package:
> 
> ```
> "autoload-dev": {
>     "psr-4": {
>         "App\\": "vendor/orchestra/testbench-core/laravel/app"
>     }
> },
> ```
> 
> Kinda hacky, but it does the trick.

You just saved my day with this, thnx!
