### ISSUE TITLE
Thoughts on Laravel 5.5 auto-discovery

### ISSUE THREAD

**Issue by kz** [orchestral/testbench#185]
Just a quick question: I'm wondering whether Testbench will support Laravel 5.5's auto-discovery? https://medium.com/@taylorotwell/package-auto-discovery-in-laravel-5-5-ea9e3ab20518

I'm personally opposed to the idea of Testbench automatically adding service providers based on packages'  composer.json files; having greater control of what's loaded in the test cases is more important to me than convenience.

**Comment by crynobone** [comment]
No, it will not be added by default. However I might access PR to include `runTestWithAutoDiscovery()` etc for such purpose, if anyone interested to do it.
