### ISSUE TITLE
Tenant Migrations

### ISSUE THREAD

**Issue by DeivCodeCamp** [orchestral/testbench#187]
maybe i'm short in knowledge but i'm having problems with the migrations of the tables in the tenant databases.
my primary database is main and the tenant databases are names of companies, i get the value from a custom field in the table users (company).

I have the driver migrations in this path.
```
'drivers' => [
        'user' => [
            'model'  => App\User::class,
            'path'   => database_path('tenanti/user'),
            'shared' => false,
        ],
    ],
```
And i want to migrate with this sentence `php artisan tenanti:migrate user` but i get this error.

```
[ErrorException]
Creating default object from empty value

```
do you know what is happening? do you need more information?

I thank you in advance.
Gretting from Argentina, David

**Comment by crynobone** [comment]
Wrong repo.
