### ISSUE TITLE
Testing package using Laravel Dusk?

### ISSUE THREAD

**Issue by marktopper** [orchestral/testbench#189]
Is it possible to test a package using Laravel Dusk in any way using Testbench?

**Comment by crynobone** [comment]
Not right now, I don't have the time to play around and cover it.

**Comment by marktopper** [comment]
Okay, I will see if I can figure something out and let you know.

**Comment by Keoghan** [comment]
@crynobone I started to have a play with this and put something together which works (i.e. the test works for me - I have not tested on travis etc, but placed in your std files for travis etc).

I'm happy to share/move the repo to you if think this is an appropriate direction. 

The main issue I had was in creating a local server for the package, where it doesn't really exist as a full Laravel app (so you can't straight out 'artisan:serve'). I took an unusual direction to allow the recreation of the app state on the served site - in that I effectively reference the Test class when building the app on the server in a custome 'server.php' file.

https://github.com/konsulting/testbench-dusk

**Comment by crynobone** [comment]
That looks awesome.

> I'm happy to share/move the repo to you if think this is an appropriate direction.

I personally have no problem either having it under `Orchestra` namespace or yours. If it is going to be moved to orchestra we need to make sure that it would have constant version upgrade per Laravel releases.

**Comment by Keoghan** [comment]
Cool, I’ll keep tidying it up a bit and once it’s in the right spot, we can decide where it should live :)

**Comment by crynobone** [comment]
Added you as admin to https://github.com/orchestral/testbench-dusk

If you want to use Orchestra feel free to do so, but need your help on managing further improvements for it.

**Comment by Keoghan** [comment]
Thanks, totally understand on support in the future.

**Comment by Keoghan** [comment]
Hi @crynobone, just a little update. I've now got tests passing for Laravel 5.4 (and Dusk 1.x) in a 3.4.x branch and Laravel 5.5 (with Dusk 2.x) in master/3.5.x working on Travis. I've also simplified how it works quite a bit, and I think we're almost at a transfer point.

**Comment by Keoghan** [comment]
@crynobone I've just pushed the repo contents over to https://github.com/orchestral/testbench-dusk. The readme needs a couple of tweaks, and it'd be good if you can advise how you'd like to adjust the licence etc. Happy to chat via slack, email or other if that better suits you.

I've not tagged a release yet, need to get Travis up, and then link through to Packagist :)

**Comment by crynobone** [comment]
> I've not tagged a release yet, need to get Travis up, and then link through to Packagist :)

Everything is setup, feel free to tag stable `v3.4.0` and `v3.5.0` whenever you're ready.

**Comment by marktopper** [comment]
Really appreciated 👍
