### ISSUE TITLE
How to overwrite binding in register() of service provider

### ISSUE THREAD

**Issue by aimeos** [orchestral/testbench#191]
There's a method in a class registered in the service provider we have to overwrite for the tests.

Class: https://github.com/aimeos/aimeos-laravel/blob/master/src/Aimeos/Shop/Base/View.php
Registered: https://github.com/aimeos/aimeos-laravel/blob/master/src/Aimeos/Shop/ShopServiceProvider.php#L103
Overwrite here: https://github.com/aimeos/aimeos-laravel/blob/master/tests/AimeosTestAbstract.php#L5

Adding these lines doesn't work:
```
$app->singleton('Aimeos\Shop\Base\View', function($app) {
	return new \AimeosTestView($app['Aimeos\Shop\Base\I18n'], $app['Aimeos\Shop\Base\Support']);
});
```

How can we achieve that?

**Comment by crynobone** [comment]
Shouldn't you use `$app->instance()` on this case?

**Comment by aimeos** [comment]
We want to replace the existing instance (if already instantiated), not using the created instance

**Comment by aimeos** [comment]
It doesn't work if the controllers are tested with
```
$this->action('GET', '\Aimeos\Shop\Controller\JqadmController@createAction', $params);
```
In this case, always the binding from the ServiceProvider of the package will be used.

**Comment by crynobone** [comment]
If you feel there's a bug create a failing test case on this repository to demonstrate this issue, otherwise `$app->instance()` still is the right option for it.
