### ISSUE TITLE
Migration | Custom path/migration not working

### ISSUE THREAD

**Issue by t1k3hu** [orchestral/testbench#192]
Tables does not exists after migration.
```php
$this->artisan('migrate', [
    '--database' => 'testing',
    '--path'     => __DIR__ . '/fixtures/database/migrations',
]);

// Output: SQLSTATE[HY000]: General error: 1 no such table: tablename
```

**Comment by crynobone** [comment]
`--path` will always prefixed with `$app->basePath()`

https://github.com/laravel/framework/blob/v5.5.0/src/Illuminate/Database/Console/Migrations/BaseCommand.php#L19-L23

Read the Testbench documentation for migration, or review or tests.

**Comment by yunism-my** [comment]
So what can we do when we're testing the package's implementation with additional database table?

For instance, I need to add a `users` table for the `User` model, which implement my package's trait...

**Comment by mikebronner** [comment]
This should probably be documented. Thanks for sharing @yunism-my

**Comment by crynobone** [comment]
@mikebronner feel free to make a PR on that
