### ISSUE TITLE
Model not associated with...anything ??

### ISSUE THREAD

**Issue by joshbruce** [orchestral/testbench#193]
This one is odd - may be more appropriate on Stack.

I will try to give what I think is pertinent, but I'm new to this package (thank you for making it; been very frustrating to test packages). Apologies for physical lenght, but I am erring on the side of too much information. :)

```php
namespace Eightfold\Registered\Tests;

use Orchestra\Testbench\TestCase as BaseTestCase;

use Eightfold\Registered\Tests\Stubs\User;

abstract class TestCase extends BaseTestCase
{
    public function setUp()
    {
        parent::setUp();

         // Works as expected. 
        $this->loadMigrationsFrom([
            '--database' => 'testing',
            '--path' => realpath(__DIR__.'/../src/migrations'),
        ]);

        $this->artisan('migrate', ['--database' => 'testing']);
    }

    // use CreatesApplication;
    protected function getPackageProviders($app)
    {
        // Works as expected.
        return [
            RegisteredServiceProvider::class
        ];
    }

    protected function getEnvironmentSetUp($app)
    {
        $this->app = $app;

        // Does work. I can pull models from the database using DB and the package main models.
        // The problem comes when I try to 
        $app['config']->set('database.default', 'testing');
        $app['config']->set('database.connections.testing', [
            'driver'   => 'sqlite',
            'database' => ':memory:',
            'prefix'   => '',
        ]);

        // I have tried this with auth.providers.users.model as well.
        $config = $app->make('config');
        $config->set([
            'auth.providers.users.model' => User::class
        ]);
    }

    // Works as expected (passes)
    public function inviteUser()
    {
        $invitation = UserInvitation::invite('someone@example.com');
        $this->assertNull($invitation->claimed_on);
        return $invitation;
    }

    // Works as expected (passes)
    // As long as I don't use the User class - see below
    public function registerUser()
    {
        $invitation = $this->inviteUser();

        // POST request data
        $username = 'someone';
        $email = 'someone@example.com';

        $registration = UserRegistration::registerUser($username, $email, null, $invitation);
        
        $slug = $registration->type->slug;
        $this->assertTrue($slug == 'owners', $slug);
        $this->assertTrue($invitation->isClaimed, $invitation);
        return $registration;
    }
}
```

So far so good, I think.

```php
namespace Eightfold\Registered\Models;

class UserRegistration extends Model
{
    //...

    static public function registerUser(string $username, string $email, UserType $type = null, UserInvitation $invitation = null): UserRegistration
    {
        //...

        // Create user.
        $user = null;
        if (App::runningUnitTests()) {
            // Workaround
            // TODO: There has to be a way to get the user class with this check.
            \DB::table('users')->insert([
                'username' => $username,
                'email' => $email
            ]);
            $user = \DB::table('users')
                ->where('username', $username)
                ->first();

        } else {
            // Desired and works manually
            $userClass = static::belongsToUserClassName();
            $user = $userClass::create([
                    'username' => $username,
                    'email' => $email
                ]);

        }

        //...
    }
}
```

What am I missing? Again, I'm new to this library and appreciate it a great deal...and I would like to avoid putting `runningUnitTests` checks throughout the code; especially when the package classes seem to work just fine. Thank you for your assistance.

The main project - and the working branch: https://github.com/8fold/laravel-registered/tree/testing

The project that holds `belongsToUserClassName`: https://github.com/8fold/laravel-traits

**Comment by crynobone** [comment]
Too long for me to understand what's really wrong here. 

I personally has no problem interacting with Model during testing. https://github.com/laravie/authen/blob/master/tests/AuthenticateTest.php

**Comment by joshbruce** [comment]
@crynobone: Yeah, I used the AuthenticateTest as the basis for setting all this up. I'm sorry it's too long. The ultimately short version is:

Setup:

- works - `setUp()`: Designed based on instructions here.
- works - `getPackageProviders($app)`: Designed based on instructions here.
- works (I think) - getEnvironmentSetUp($app): The class name found from by the app config is correct.

Tests:

- works - `inviteUser()`: Passes. Only involves a class that is part of the package.
- **fails** (unless adjusted) - `registerUser()`: As soon as the call stack reaches the User stub, tests crash.

Workaround:

- The workaround I have now is to *not* use the the User stub class when interacting with the users table.

Package oddity:

- This package uses a trait (`BelongsToUser`) for handling relationship with the User class. This trait is not part of the base project. I have not tested whether this actually makes a difference yet.

**Comment by crynobone** [comment]
Still have no idea **"what has failed?"**, might as well provides a full tests example on `orchestra/testbench-core` so I can fix it.

**Comment by joshbruce** [comment]
Interesting development.

Was actually working on stripping the package down to one test and the files needed to bootstrap.

As I was starting to build the failing demo I got access to the user class...so, I started discarding changes one file at a time and running the tests without the hack to cover the glitch...they continued to pass.

Eventually, I merged it all back together to have my package back.

If you check out the /testing branch linked at the bottom of the initial comment you can check out the commit history. Still not sure what exactly changed on my end (if anything). Thanks again for the package. Definitely a great help.
