### ISSUE TITLE
Run without auto-discovery

### ISSUE THREAD

**Issue by nWidart** [orchestral/testbench#195]
Hello,

I just stumbled upon an issue where laravel registers auto-discovered packages, before the environment was setup, causing errors.

In the `CreatesApplication` trait, `resolveApplicationBootstrappers` method:

```php
$app->make('Illuminate\Foundation\Bootstrap\HandleExceptions')->bootstrap($app);
$app->make('Illuminate\Foundation\Bootstrap\RegisterFacades')->bootstrap($app);
$app->make('Illuminate\Foundation\Bootstrap\SetRequestForConsole')->bootstrap($app);

$this->getEnvironmentSetUp($app); // If I put this here no more errors
$app->make('Illuminate\Foundation\Bootstrap\RegisterProviders')->bootstrap($app);

$this->getEnvironmentSetUp($app); 
```

I'm guessing this is because of auto-discovery. Is there a way to disable it?

Thanks!

**Comment by crynobone** [comment]
Can you create a failing test case so I can focus on the fix?

**Comment by nWidart** [comment]
Hm this would be tricky to test, as it depends on a couple of requirements:

- needs to have a package that is using auto-discover
- that package requires having configuration set

I have a failing suite [here](https://travis-ci.org/AsgardCms/Platform/jobs/280418357), which is failing because the config is set after autodiscovery.

**Comment by crynobone** [comment]
Can you test on the latest build.

**Comment by nWidart** [comment]
Thanks! how can I get this? By using the branch-alias on testbench core of `dev-master`?

**Comment by nWidart** [comment]
I just tested this and works. Thanks! 👍

**Comment by fulopattila122** [comment]
Does this mean that in a testing environment no package auto discovery happens? So that if I want to rely on packages I need to register them along with their aliases as with 5.4?

**Comment by nWidart** [comment]
I think you can use the `getPackageProviders` method to register them.

**Comment by crynobone** [comment]
> So that if I want to rely on packages I need to register them along with their aliases as with 5.4?

Yes, imagine if the user of your package decide to disable auto discovery but load your package manually. They might not know that you have a hidden dependency to another package.

**Comment by fulopattila122** [comment]
Not a problem, I just wanted to know if it is the intended way.
