### ISSUE TITLE
Index already exists error

### ISSUE THREAD

**Issue by smtlk** [orchestral/testbench#196]
`SQLSTATE[HY000]: General error: 1 index idx_country_operators already exists (SQL: create index "idx_country_operators" on "ipv6_locations" ("country_code", "operator_name"))`

I'm getting that error on my setup i don't really know why, my migration does set up the index in question but why is testbench trying to create it twice? I'm using an SQLite Memory connection and my TestCase class (which extends testbench) is defined as follows.

    public function setUp()
    {
        parent::setUp();

        $this->artisan('migrate', ['--database' => 'testing']);
    }

    /**
     * Define environment setup.
     *
     * @param  \Illuminate\Foundation\Application  $app
     *
     * @return void
     */
    protected function getEnvironmentSetUp($app)
    {
        $app['config']->set('database.default', 'testing');
        $app['config']->set('database.connections.testing', [
            'driver'   => 'sqlite',
            'database' => ':memory:',
            'prefix'   => '',
        ]);
    }

    /**
     * Get package providers.  At a minimum this is the package being tested, but also
     * would include packages upon which our package depends, e.g. Cartalyst/Sentry
     * In a normal app environment these would be added to the 'providers' array in
     * the config/app.php file.
     *
     * @param  \Illuminate\Foundation\Application  $app
     *
     * @return array
     */
    protected function getPackageProviders($app)
    {
        return [
            "Oxy\\GeoIP\\GeoIpServiceProvider"
        ];
    }

**Comment by crynobone** [comment]
Not a testbench bug.

**Comment by smtlk** [comment]
Hi @crynobone then what is it related to? Can you give me any hint?

**Comment by crynobone** [comment]
I have no idea how you structure your tests and I'm 100% sure it's not related to testbench since I am using testbench with an application with close to 100 migrations with multiple indexing without any issue.

**Comment by smtlk** [comment]
@crynobone thanks, i managed to figure it out it was referencing the wrong DB, what i ended up doing was override the entire DB config in my base class

        $app['config']->set('database.default', 'testing');
        $app['config']->set('database.connections.testing', [
            'driver' => 'mysql',
            'host' => 'mysql',
            'port' => '3306',
            'database' => 'testing',
            'username' => 'root',
            'password' => 'root',
            'unix_socket' => '',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ]);
