### ISSUE TITLE
ExceptionHandler is not instantiable

### ISSUE THREAD

**Issue by nWidart** [orchestral/testbench#197]
Hello,

I'm not sure this is because of the latest version, but on php 7.2, I'm getting the following error:

```
Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. 
```

[full travis job](https://travis-ci.org/nWidart/laravel-modules/jobs/282374954)

I've found a usage in the `CreatesApplication` trait but not sure why it's not binding on php 7.2 only.

**Comment by crynobone** [comment]
The tests are failing during generating HTML coverage, not the test itself. It could be something related to the way PHPUnit generate the files.

I have no idea how this can be fixed by Testbench.

**Comment by nWidart** [comment]
Oh ok, I see. This is something on laravel's side then maybe?

**Comment by crynobone** [comment]
> This is something on laravel's side then maybe?

Can't be certain, but I do know the way PHPUnit lookup coverage is not based on how Laravel would load those files, which for example Laravel 5.1 added the following https://github.com/laravel/laravel/blob/5.1/phpunit.xml#L20 because it could cause problem when the file is referring to undefined variable etc when not loaded properly.

**Comment by nWidart** [comment]
Strangely it does it even for packages without running the coverage like: https://travis-ci.org/AsgardCms/Notification/jobs/283674581

Which simply runs `- vendor/bin/phpunit`

**Comment by crynobone** [comment]
https://github.com/AsgardCms/Notification/blob/master/phpunit.xml.dist#L37

It define here and the **test log clearly state the error started while generating code coverage.**

**Comment by nWidart** [comment]
Hm ok. I thought that wasn't run without specifying it in the command.

Though this doesn't fix the issue does it? 

The binding shouldn't be an error when generating code coverage.

**Comment by crynobone** [comment]
This is seriously outside the scope/control of Testbench.

**Comment by nWidart** [comment]
Hm ok.

Though from what I can see, it's this package that binds the interface with its implementation, here: https://github.com/orchestral/testbench-core/blob/c1ccd1bde213ebf739bfbcbc0e743f1d1f306aa8/src/Traits/CreatesApplication.php#L293

Which clearly isn't working.

**Comment by crynobone** [comment]
The test is passing! which show when loaded properly based on Laravel app loading sequence it is working fine.

What's not passing is HTML code coverage which is not in my or this package control.
