### ISSUE TITLE
vendor/orchestra/testbench-core/tests/ in autoload

### ISSUE THREAD

**Issue by aphofstede** [orchestral/testbench#199]
Seems like `vendor/orchestra/testbench/composer.json` points to the wrong place for `\Orchestra\Testbench\Tests\Stubs\ServiceProvider` to be included in the `getPackageProviders()` override [as per the docs](https://github.com/orchestral/testbench-core/tree/3.5/tests/Databases).
I had to add the following to my package's `composer.json`:
```
    "autoload-dev": {
        "psr-4": {
            ...
            "Orchestra\\Testbench\\Tests\\": "vendor/orchestra/testbench-core/tests/"
        },
        ...
    },
```

<img width="338" alt="screen shot 2017-10-12 at 22 20 57" src="https://user-images.githubusercontent.com/701218/31517391-0c319c8c-af9c-11e7-9449-bca18e760d6a.png">

( `vendor/orchestra/testbench/composer.json` points to a non-existing `"core/tests/"`, perhaps that should be `"../testbench-core/tests/"`)

**Comment by aphofstede** [comment]
Composer doesn't seem to support git submodules.. Am I missing something?

**Comment by crynobone** [comment]
You shouldn't care about autoload-dev when you pull this to your project.

**Comment by LaurentChardin** [comment]
I had to manually execute the following in testbench folder:

```
git submodule init
git submodule update
```

It actually pulled out the corresponding code.

(which leads to duplication of code because therefore the testbench-core folder added by composer is useless).

**Comment by crynobone** [comment]
I already answered this issue, yoi simply using it wrongly.

**Comment by LaurentChardin** [comment]
Yes i was looking at the composer file and the psr4 path is correct.

Thanks
