### ISSUE TITLE
Dealing with chunked tests?

### ISSUE THREAD

**Issue by jpcaparas** [orchestral/testbench#200]
Hi there,

First of all, thanks for the package. [I'm using it for tests](https://github.com/jpcaparas/xerovel/blob/master/tests/Feature/ServiceProviderTest.php) on [this wrapper](https://github.com/jpcaparas/xerovel) I put around the Xero API client.

I was wondering if there is a pattern I need to be aware of when chunking PHPUnit tests that do modifications to the file system.

Is there a way to get a fresh, untainted filesystem every time a test is run? Or should that be my responsibility? Thanks.

**Comment by crynobone** [comment]
What's we offer is basically to make it easier to run packages tests as if it was on a basic Laravel installation.
