### ISSUE TITLE
Not able to find ApplicationTrait

### ISSUE THREAD

**Issue by Modelizer** [orchestral/testbench#204]
[Laravel Selenium Package](https://github.com/Modelizer/Laravel-Selenium) is dependent on this package. And when travis try to run it on PHP7 it says `Orchestra\Testbench\Traits\ApplicationTrait` not found. To know more you can checkout [travis build](https://travis-ci.org/Modelizer/Laravel-Selenium/jobs/277781803).

Is there any alternative if AplicationTrait is been removed or what change do we need to make?

**Comment by crynobone** [comment]
`Orchestra\Testbench\Traits\ApplicationTrait` has been deprecated in `3.4` and removed in `3.5`.

Use `Orchestra\Testbench\Traits\CreatesApplication`
