### ISSUE TITLE
RefreshDatabase is running my package migration before laravel CreateUsersTable migration

### ISSUE THREAD

**Issue by saqueib** [orchestral/testbench#206]
I am very new to package development, I have setup the testbench and I can run the migration using `RefreshDatabase` trait on my tests. But the problem arises when I need to add a column is_active on users table, I created migration in my package migrations folder, and it's giving me `no such table users` It seems my packages migration is running before the laravel migration.

Here is my **TestCase**

```php
public function setUp()
{
    parent::setUp();
    $this->loadLaravelMigrations(['--database' => 'testbench']);
}

protected function getEnvironmentSetUp($app)
{
    // Setup default database to use sqlite :memory:
    $app['config']->set('database.default', 'testbench');
    $app['config']->set('database.connections.testbench', [
        'driver'   => 'sqlite',
        'database' => ':memory:',
        'prefix'   => '',
    ]);
}
```

Here is my **TestClass**

```php
use Illuminate\Foundation\Testing\RefreshDatabase;

class AuthTest extends TestCase
{
    use RefreshDatabase;
    ...
}
```
Here is my package migration.
`2017_11_30_072550_package_migration`

**Compose.json**
```json
"require-dev": {
        "phpunit/phpunit": "^6.2",
        "orchestra/testbench": "~3.0"
    },
```

Please suggest how I can run the laravel migration first, then my packages migration.

**Comment by saqueib** [comment]
one more issue: not able test Mail

**MailTest**
```php
Mail::fake();
        
$this->post('/register', $payload)
            ->assertStatus(302)
            ->assertRedirect('home');
            
// Assert a mailable was sent...
Mail::assertSent(ConfirmationEmail::class);
```

This gives `The expected [MyPackage\Mail\ConfirmationEmail] mailable was not sent.`, but if I comment out the `Mail::fake()` It sends email I can see in my inbox.

**Comment by crynobone** [comment]
Don't lump everything under one issue.

**Comment by saqueib** [comment]
ok, I deleted my second issue, now if you can help me @crynobone that would be great

**Comment by crynobone** [comment]
AFAIK, `RefreshDatabase` is mainly useful when you have an prepared database setup for your Continuous Integration, since it would just set every changes under database transaction and rollback during tear down. 

If you have a prepared database setup, there shouldn't be a reason to still run `loadLaravelMigrations()` since the table should be ready.

**Comment by rushairer** [comment]
OK, 

please note  that at README.md file.
