### ISSUE TITLE
Load .env for secrets. Cannot use phpunit.xml

### ISSUE THREAD

**Issue by tpraxl** [orchestral/testbench#211]
I need to use a secret API Key in my tests. 
This key cannot be part of `phpunit.xml`, because it must not end up in the VCS.

I noticed that orchestra/testbench doesn't pick up the package's `.env` file. Is it supposed to ignore it?

I tried the following in my `TestCase` that extends the orchestra/testbench `TestCase`:

```php 
protected function setUp()
{
   if (! $this->app) {
      $this->refreshApplication();
   }
   // doesn't work
   $this->app->useEnvironmentPath(__DIR__.'/..');
   parent::setUp();
}
```

I also tried to copy my `.env` file into the scope of the testbench app:

```php
    public function setUp()
    {
        // make sure, our .env file is loaded
        copy(__DIR__.'/../.env', $this->getVendorPath().'/orchestra/testbench-core/laravel/.env');
        parent::setUp();
    }
```

But my tests report that it is not set:

```php
dd(env('API_KEY')); // results in null
```

Is there any way to keep the API_KEY out of the VCS but make it available during my tests?

**Comment by tpraxl** [comment]
Should anyone come across this problem, here's the solution:

```php
use Illuminate\Foundation\Bootstrap\LoadEnvironmentVariables;
…
abstract class TestCase extends \Orchestra\Testbench\TestCase
{
    protected function getEnvironmentSetUp($app)
    {
        // make sure, our .env file is loaded
        $app->useEnvironmentPath(__DIR__.'/..');
        $app->bootstrapWith([LoadEnvironmentVariables::class]);
        parent::getEnvironmentSetUp($app);
    }
```

**Comment by crynobone** [comment]
PHPUnit developers suggests the use of `phpunit.xml.dist`, see <https://stackoverflow.com/a/44764078/1458318>

**Comment by tpraxl** [comment]
@crynobone thanks for the hint. Besides this option, is there any reason not to load `.env` during application setup?

**Comment by crynobone** [comment]
1. It's an optional features and not every package developer needs to depends on it. 
2. I just prefer to avoid any possible issues with adding an extra dependencies so far.
3. If you needs to verify `.env` usage, you can load it manually and control the interaction (without having to swap how Testbench loads it).

**Comment by tpraxl** [comment]
I see. Thank you very much. 

Would you mind me making a PR that adds the specifics about how this works to the README? 

Because it took me some time to figure out that:

1. orchestra/testbench doesn't load .env on purpose (I wasn't sure if this was a setup issue or a bug in the first place)
2. how to make it load the `.env`

**Comment by crynobone** [comment]
No, I don't want to recommends using `.env`.

**Comment by crynobone** [comment]
Furthermore we already put a suggested `APP_KEY` on [our README](https://github.com/orchestral/testbench#no-supported-encrypter-found-the-cipher-and--or-key-length-are-invalid). And more than 1k project is using this dummy `APP_KEY` on GitHub. https://github.com/search?q=AckfSECXIvnK5r28GVIWUAxmbBSjTsmF&type=Code&utf8=%E2%9C%93

**Comment by tpraxl** [comment]
I understand that you don't want that in your README. Thank you for your help and feedback.

**Comment by bayareawebpro** [comment]
Came across this and wanted to share another approach: 

Load it in the setup method and let the app pick it up when it boots.

```
   protected function setUp(): void
    {
        // Code before application created.
        $dotenv = Dotenv::createImmutable(__DIR__.'/../');
        $dotenv->load();

        parent::setUp();
    }
```

**Comment by SuperHydroman** [comment]
> Should anyone come across this problem, here's the solution:
> 
> use Illuminate\Foundation\Bootstrap\LoadEnvironmentVariables;
> …
> abstract class TestCase extends \Orchestra\Testbench\TestCase
> {
>     protected function getEnvironmentSetUp($app)
>     {
>         // make sure, our .env file is loaded
>         $app->useEnvironmentPath(__DIR__.'/..');
>         $app->bootstrapWith([LoadEnvironmentVariables::class]);
>         parent::getEnvironmentSetUp($app);
>     }

Oh my lord I wish I found this earlier... Would've saved me 7 hours of trial and error. I indeed noticed it was reading the `vendor/laravel/.env` file instead of the `./workbench/.env` file. At least that is where I store my `.env` so I had to affix your snippet with `/workbench`:  `$app->useEnvironmentPath(__DIR__.'/../workbench');`

**Edit:** Documentation **HAS** to be updated. It litterly says that it reads out the `.env` by default. I asked different AI tools, they all said the same thing about how the `.env` is automatically read out from `./workbench` directory
