### ISSUE TITLE
Error: Class 'xyz' not found

### ISSUE THREAD

**Issue by mtrajano** [orchestral/testbench#216]
For some reason my nested classes aren't being auto-loaded.

This is how my files are structured
```
- src/
- - Generator.php
- - Parameters/
- - - PathParameter.php
```

and my composer.json file:
```
    ...
    "autoload": {
        "psr-4": {
            "Mtrajano\\LaravelSwagger\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Mtrajano\\LaravelSwagger\\Tests\\": "tests/"
        }
    },
    ...
```

In my Generator class I initialize PathParameter like so:
`new Parameters\PathParameter()`

But its giving me an error when running in a test environment:
`Error: Class 'Mtrajano\LaravelSwagger\Parameters\PathParameter' not found`

However when I run the command directly through the console it works. Any idea on how I can resolve this issue?

**Comment by crynobone** [comment]
Never encountered such issue

**Comment by mtrajano** [comment]
@crynobone Neither have I, it's a really weird issue

**Comment by mtrajano** [comment]
Not sure why but when I ran `composer dump-autoload` with the `--optimize` flag it worked... You can close this ticket I guess, but just leaving this here in case someone else comes across this issue

**Comment by crynobone** [comment]
Testbench doesn't mess around with autoloading and I have  done  same style initiation before without issues.
