### ISSUE TITLE
helpers.php

### ISSUE THREAD

**Issue by lloricode** [orchestral/testbench#217]
Hi!, how can i include helper functions like inside file `helpers.php` in testing?

Thanks :)

**Comment by crynobone** [comment]
Look into how Laravel adds helper files?

Irrelevant to Testbench.

**Comment by lloricode** [comment]
@crynobone im mean my `package` has a helper, but didnot include when running in test, so the function didnot exist on testing

**Comment by lloricode** [comment]
hmm, yes in `composer.json` will manage it, 
i mean just like in `TestCase` that has

```php
    protected function getPackageAliases($app)
    {
        return [
            "DataTables" => "Yajra\\DataTables\\Facades\\DataTables"
        ];
    }

    protected function getPackageProviders($app)
    {
        return [
            "Me\\Base\\Providers\\BaseServiceProvider",
            "Me\\Base\\Providers\\EventServiceProvider",

            // --
            "Yajra\\DataTables\\DataTablesServiceProvider",
        ];
    }
```

because it cannot run a `composer.json`, so how possible to test this with a file helpers, 
sorry for inconvenience, but how is ti possbile to include helpers?, hmmm maybe just dont make a file helpers?

Thanks @crynobone

**Comment by lloricode** [comment]
hmm maybe just to `require` a file?

hhmm thanks @crynobone  :)

**Comment by crynobone** [comment]
Nope, Testbench doesn't autoload files. What you show above is Testbench registering the relevant services to Laravel. THAT TWO COMPLETELY DIFFERENT things.

**Comment by crynobone** [comment]
This is autoloading: <https://github.com/laravel/framework/blob/v5.6.0/composer.json#L86-L94>
