### ISSUE TITLE
Session store not set on request when flashing request

### ISSUE THREAD

**Issue by Okipa** [orchestral/testbench#220]
I get the `Session store not set on request.` issue when I try to flash a request, in order to get the `old()` value in  a view.

I tried to add the following code in the `getEnvironmentSetUp` or  in the `setUp` methods but it does not change anything as it was suggested in older versions but without success.
```
$kernel = app('Illuminate\Contracts\Http\Kernel');
$kernel->pushMiddleware('Illuminate\Session\Middleware\StartSession');
```

Here is what I was trying to do in a test :
```
$request = request()->merge(['name' => 'test-old-value']);
$request->flash();
```

What am I doing wrong here ?

**Comment by crynobone** [comment]
The suggested code was meant for Testbench 3.1 and below.

I don't know exactly what you trying to test that is failing. You could send a failing tests to `testbench-core` to demonstrate how this would fail.

**Comment by Okipa** [comment]
> The suggested code was meant for Testbench 3.1 and below.
Yes this is what I understood but I still tried it to check if it had any incidence on my problem.

What I am trying to do is to manually store values in the `_old` part of the session, in order to check a html rendering with `old()` method called.  
I don't know if it is a bug or if I am not doing it the right way.  
I used Testbench for a few packages testings without any problem but this is the first time I am trying to test such a thing and I spent hours to check for a solution, without finding anything.

Anyway, I wrote a test here to point the issue : https://github.com/Okipa/testbench-core/blob/3.6/tests/RequestTest.php

**Comment by crynobone** [comment]
You can't just use `request()` or `old()` without making a HTTP request, cause 

```php
$kernel = app('Illuminate\Contracts\Http\Kernel');
$kernel->pushMiddleware('Illuminate\Session\Middleware\StartSession');
```

Is only attach to HTTP middleware when you make a request.

See <https://github.com/orchestral/testbench-core/commit/a7046d52423241d535ea2c48158759b949ed83ff> for reference.

**Comment by Okipa** [comment]
Ok, so I did it the wrong way ;)
Thank you for this example I search for.
