### ISSUE TITLE
app instance unavailable during setUp / @before

### ISSUE THREAD

**Issue by sandervanhooft** [orchestral/testbench#221]
While upgrading a package from testbench v3.1 to latest, I noticed the `$this->app` instance is no longer available during test `setUp`.

Is this by design?

**Comment by crynobone** [comment]
It is by design to be consistent with `Illuminate\Foundation\Testing\TestCase`.

**Comment by sandervanhooft** [comment]
Thanks for clearing that one up @crynobone :)
