### ISSUE TITLE
Clean Config

### ISSUE THREAD

**Issue by FuriosoJack** [orchestral/testbench#223]
Hello, I am doing some tests on my package and I notice that the configuration of my package is being "cached".

My package uses settings that I then publish in the laravel project, but doing the test with your package the configuration every time I run the test is not created as the first time. Rather I see that the configuration file is being left in the _vendor / testbench-core / laravel / config._

In a project I know that this problem would be solved with **php artisan config: cache** or **config: clear** but in your package it is not necessary to erase the cache of a configuration of the package to be tested.

**Comment by crynobone** [comment]
That should be the responsibility of package developer to do so if you need it. 

**Testbench** doesn't interfere and now what you are doing during installation/bootstrapping Laravel.
