### ISSUE TITLE
Can't get schema column listing

### ISSUE THREAD

**Issue by Okipa** [orchestral/testbench#226]
Hi @crynobone,

I have an issue to get a schema column listing with testbench.  
Here is a test I have written to point the problem : https://github.com/Okipa/testbench-core/blob/3.7/tests/SchemaTest.php

This work perfectly in Laravel but I can't get it work on a package testing.

As you can see, my tests are using sqlite and not mysql. Could this cause this wrong behaviour ?
Is there a way to make this work with testbench ?

**Comment by crynobone** [comment]
I don't see how it going to work with `:memory:` database, you need to migrate `testbench_users` before using `Schema::getColumnListing('testbench_users')`.

Try again using mysql, or sqlite with physical file and ensure that the table exists, you should get the tests to be green.
