### ISSUE TITLE
Class not found even after autoloading classmap in autoload-dev

### ISSUE THREAD

**Issue by introwit** [orchestral/testbench#228]
Hi, Thank you for Testbench 🙂 

- I am creating a `mailable` class in the `setUp` method of my test class.
- As expected it is created in the `vendor/orchestra/testbench-core/laravel/app/Mail` directory.
- To use that mail class in one my test methods I do `app()->getNamespace() . Mail\\TheClassName`
- But test fails saying `Class App\Mail\TheClassName not found`

I have already added the `vendor/orchestra/testbench-core/laravel/` to the `classmap` of `autoload-dev` still the problem persists when running the tests on a fresh deploy to a CI service.

If I am doing it wrong, can you help me out on whats the right way to access the mail class created in the setUp method to use in other methods of the test? Thanks :)

**Comment by crynobone** [comment]
Shouldn't `classmap` require `composer dump-autoload` before composer start accepting the class
