### ISSUE TITLE
Container issues in v3.7.0

### ISSUE THREAD

**Issue by antonkomarev** [orchestral/testbench#229]
When I'm running `$ vendor/bin/phpunit` there is fatal error:
> PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Console\Kernel] is not instantiable. in /home/ell/Projects/laravel/laravel-love/vendor/laravel/framework/src/Illuminate/Container/Container.php:933

When Travis trying to run the tests there is another one error:
> PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /home/travis/build/cybercog/laravel-love/vendor/laravel/framework/src/Illuminate/Container/Container.php:933

But when I'm running tests using PHPStorm IDE all tests are green (there are no issues).

v3.6.0 working without any issues.

Here is a link to [failing PR](https://github.com/cybercog/laravel-love/pull/21).

**Comment by crynobone** [comment]
There no changes in container between 5.6 to 5.7 <https://github.com/illuminate/container/compare/5.6...5.7>

Futhermore Travis also throws that the tests having php memory limits exception. You might want to increase that first since you have no problem running this locally.

**Comment by antonkomarev** [comment]
I've found solution. It's happens because `$this->artisan` returns `PendingCommand` instead of output. But this [new console behavior could be turned off](https://github.com/laravel/framework/pull/25499).

If there is a need to support Laravel 5.7 as well as earlier framework versions you could you could use `withoutMockingConsoleOutput` method before the artisan call.

```php
if (starts_with($this->app->version(), '5.7')) {
    $this->withoutMockingConsoleOutput();
}
```

**Comment by mikebronner** [comment]
Thanks @antonkomarev I was having this problem as well with my console command unit tests.

**Comment by crynobone** [comment]
This should be added to the README documentation. PR are welcomes

**Comment by antonkomarev** [comment]
@crynobone I've created PR to the Laravel core: https://github.com/laravel/framework/pull/25573
If it will be rejected - I'll migrate it to this repo.

**Comment by antonkomarev** [comment]
I've pushed another one solution which seems more flexible for me: https://github.com/laravel/framework/pull/25574

**Comment by antonkomarev** [comment]
PR was merged, so we will be able to use `run` method for immediately command execution on `PendingCommand` in next release.

```php
$output = $this->artisan('foo:bar')->run();
```
