### ISSUE TITLE
Route NotFoundHttpException

### ISSUE THREAD

**Issue by jigneshwebclues** [orchestral/testbench#230]
- When i call route from test case file that time i face the `NotFoundException`.
- the way of calling route is `$response = $this->get('login');`

**Comment by crynobone** [comment]
Please provide more specific information or create a PR with failing tests on <https://github.com/orchestral/testbench-core>

**Comment by jigneshwebclues** [comment]
Thanks for reply but that i had solve and face new problem that i send you.
```
 public function test_should_return_login_view()
    {
        View::shouldReceive('make')
        ->once()
        ->with('login::login');
    $this->response->shouldReceive('getOriginalContent')
        ->once()
        ->andReturn(Mockery::mock([
            'getName' => 'login::login'
        ]));
    $response = $this->controller->index();
    dd($response);
    // $this->assertViewis('login');
    }
```
Now the error is 
```No matching handler found for Mockery_1_Illuminate_View_Factory::make('login::login', [], []). Either the method was unexpected or its arguments matched no expected argument list for this method```

**Comment by crynobone** [comment]
This is not how you test with Testbench, and definitely not a bug with Testbench. You should try asking these sort of questions on Laravel's Slack, Forum or StackOverflow.
