### ISSUE TITLE
Global config is null inside controller when testing.

### ISSUE THREAD

**Issue by dorin-niscu** [orchestral/testbench#235]
When I access the api with Postman everything behaves normally.

When I run the test **config('users')** is null inside the controller.

**config('app')** and the other Laravel configurations return data.

If I merge the config inside service provider it works, but not with the exported one.

```
$this->mergeConfigFrom(
    __DIR__ . '/../../config/users.php', 'users'
 );
```

The test runs fine excepting this.

**Controller**

```
class UserController extends Controller
{
    public function __construct()
    {
        dump(config('users'));        
    }
}
```

**Test**

```
public function testBasicTest()
{
    $user = factory(User::class, 'user')->create();

    $this->actingAs($user, 'api')
         ->json('GET', '/api/users/' . $user->id)
         ->assertStatus(200)
         ->assertJson([
             'data' => [
                 'id' => $user->id,
             ],
         ]);
}
```

**Comment by dorin-niscu** [comment]
@crynobone I am using the config() helper inside a real controller, not in a test. Is it possible to include it in the Testbench setup like I added service providers and facades?

**Comment by crynobone** [comment]
Do you see `users.php` under <https://github.com/orchestral/testbench-core/tree/3.7/laravel/config>? Testbench loads config from this folder **during tests**.

**Comment by dorin-niscu** [comment]
No, of course it`s not there. It is my custom config file which I intend to include in the test if it`s possible otherwise I will run tests using the merged config files.

**Comment by crynobone** [comment]
> It is my custom config file which I intend to include in the test if it's possible otherwise I will run tests using the merged config files.

If you want to include your custom config file, you need to export it to the skeleton as you would ask your user to do when installing the package, such as using `php artisan vendor:publish`. Testbench doesn't do this automatically because you might want to test with or without the config file.

**Comment by dorin-niscu** [comment]
I understand. Thanks.

**Comment by dorin-niscu** [comment]
Would be useful e feature / concern like loadConfigurationsFrom($paths) similar with loadMigrationsFrom($paths)

**Comment by crynobone** [comment]
No plan at the moment.

**Comment by henzeb** [comment]
2022, but still you might hitting this problem, I just did. You can mergeConfigFrom in your service provider and then load that service provider in your test class with getPackageProviders. If you don't want them to load by default, you can use Config::set inside your test or inside your setUp.
