### ISSUE TITLE
Allow using App\ namespace

### ISSUE THREAD

**Issue by andrewgorpenko** [orchestral/testbench#237]
HI. Please, add a new configuration option to allow using App\ namespace. I know about your idea to make developers "save", but we need some kind of "override".

I mean the following: it is often needed to access application models. For example factories. If I want to make a fake model, I cannot do that, because there is no access to App\Models namespace for example. Of course there are many many different situations where it would be really handy.

However, if you wont add this feature to your repository, then can you advise me how to do that by myself? I mean I would create a fork and modify your original version, so nobody else would be "touched".

By the way, thanks in advance!

**Comment by andrewgorpenko** [comment]
I mean the following: it is often needed to access application models. For example factories. If I want to make a fake model, I cannot do that, because there is no access to App\Models namespace for example. Of course there are many many different situations where it would be really handy.

However, if you wont add this feature to your repo, then can you advise me how to do that by itself? I mean I would create a fork and modify your original version, so nobody else would be "touched". 

By the way, thanks in advance!

**Comment by crynobone** [comment]
No, this has been discussed in the FAQ under the documentation. Feel free to look at example how this can be done <https://github.com/laravie/authen/tree/master/tests>
