### ISSUE TITLE
Testbench not compatible with PHPUnit 8

### ISSUE THREAD

**Issue by mfn** [orchestral/testbench#238]
> PHP Fatal error:  Declaration of Orchestra\Testbench\TestCase::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void in /…/laravel-framework/vendor/orchestra/testbench-core/src/TestCase.php on line 15

PHPUnit 8 introduced return type `: void` it's `TestCase` class, like `setUp`, `tearDown`, etc. which all have to be adapted.

**Comment by crynobone** [comment]
This changes will only happen after Laravel start migrating/upgrading to PHPUnit 8

**Comment by mfn** [comment]
I figured so, it just looked like a chicken/egg thing that when I locally updated the test unit I couldn't really do it because the dependency doesn't work 😄

**Comment by crynobone** [comment]
https://github.com/laravel/framework/pull/26457#issuecomment-437672713

We want to avoid things like this from happening again.

**Comment by mfn** [comment]
Hey thanks! :feelsbad:

**Comment by GrahamCampbell** [comment]
Laravel can't upgrade because Taylor wants to keep php 7.1 compatibility in the 5.8 release. So, I guess Laravel will not support phpunit 8 until laravel 5.9.

**Comment by GrahamCampbell** [comment]
I did see this issue coming 5 months ago, and suggested Laravel 5.8 switched to PHP 7.2+, but no. 🤷‍♀️

**Comment by driesvints** [comment]
Both PHPUnit 7 and 8 can be supported. Sent in a PR here: https://github.com/orchestral/testbench-core/pull/18
