### ISSUE TITLE
Clearing app_path() dir

### ISSUE THREAD

**Issue by Naoray** [orchestral/testbench#240]
I am trying to write a test where eventually a model gets created via `make:model` command. But because it is saved in the `laravel/app` directory, the second time this test run, it fails. Is there any way to reset the `laravel/` directory?

**Comment by crynobone** [comment]
`File::delete(app_path('User.php'));` on teardown?

**Comment by Naoray** [comment]
@crynobone thanks. I did go with 

```php
public function setUp()
    {
        parent::setUp();

        $this->beforeApplicationDestroyed(function () {
            File::cleanDirectory(app_path());
        });
    }
```

Another question: When I call `class_exists()` on a model created I get `false`. Any reason why or advice on how to fix this?

**Comment by crynobone** [comment]
> EDIT: or otherwise... shouldn't the `laravel/app` directory be autoloaded?

Not by default, if you need it to be, please handle it on your project.

**Comment by squiaios** [comment]
> > EDIT: or otherwise... shouldn't the `laravel/app` directory be autoloaded?
> 
> Not by default, if you need it to be, please handle it on your project.

Hello,

I'm facing this problem too,  can you explain how to handle it for my tests please
