### ISSUE TITLE
Can we load the migration files from outside the test namespace?

### ISSUE THREAD

**Issue by jsdmultisys** [orchestral/testbench#242]
Hello.

Currently, we can run the migration files in the `/tests/database/migrations` folder. Can orchestra see the migrations from `../src/database/migrations` ? This way, I would not have to copy the migration files in my packages into the test migration folder.

I have tried

```
$this->loadMigrationsFrom(__DIR__ . '../src/database/migrations');
```
but it would still not see it unless I do:

```
$this->loadMigrationsFrom(__DIR__ . '/database/migrations');
```

and copy the files from the `/src/database/migrations` folder.

**Comment by crynobone** [comment]
![Screen Shot 2019-03-22 at 1 27 54 PM](https://user-images.githubusercontent.com/172966/54802457-57a19480-4ca6-11e9-9459-8de20121779e.png)

Why not use `ServiceProvider::loadMigrationsFrom()`?

**Comment by jsdmultisys** [comment]
@crynobone 

Are you suggesting that instead looking at the src/database/migrations, my service provider will look into the tests/database/migrations? I need your suggestion, is that the proper way?

Currently my service provider is like this:

```
<?php

namespace Geekhives\Unionbank;

class ServiceProvider extends \Illuminate\Support\ServiceProvider
{

    /**
     * Perform post-registration booting of services.
     *
     * @return void
     */
    public function boot()
    {
        $this->loadMigrationsFrom(__DIR__ . '/database/migrations');
    }
}
```

and you are suggesting to do like:

```
<?php

namespace Geekhives\Unionbank;

class ServiceProvider extends \Illuminate\Support\ServiceProvider
{

    /**
     * Perform post-registration booting of services.
     *
     * @return void
     */
    public function boot()
    {
        $this->loadMigrationsFrom(__DIR__ . '../tests/database/migrations');
    }
}
```

Is that correct? Will laravel automatically migrate this even without publishing?

**Comment by crynobone** [comment]
If you're storing the migrations file in `src` folder, doesn't that mean it's part of the "deployment" migration and not just for tests? If yes then it should already be added in our package `ServiceProvider`.

**Comment by jsdmultisys** [comment]
@crynobone Yes it is part of the deployment and I am doing auto discovery by Laravel so even the migration is not published, it will be migrated. Currently, I have to copy those files to the tests folder so that it will run before the test executes. Not sure how others are doing it.

**Comment by crynobone** [comment]
1. <https://laravel.com/docs/5.7/packages#migrations>
2. Have the service provider added to `getPackageProviders($app)`
2. Run `$this->artisan('migrate')->run()` for Laravel 5.7+

It should be migrated.

**Comment by crynobone** [comment]
No you don't have to copy the file to tests if it's already registered with ServiceProvider.

**Comment by jsdmultisys** [comment]
@crynobone Ohhh. I just need to

```
...
    /**
     * @param \Illuminate\Foundation\Application $app
     * @return array
     */
    protected function getPackageProviders($app)
    {
        return ['Acme\AcmeServiceProvider'];
    }
```
so it will see the package's migration files in the test. Thank you so much! 🎉

**Comment by crynobone** [comment]
We don't use auto-discovery because you might want to test scenarios where packages is not loaded etc.

**Comment by jsdmultisys** [comment]
@crynobone I will keep that in mind. Thanks a lot!
