### ISSUE TITLE
Migration run ordering

### ISSUE THREAD

**Issue by antonkomarev** [orchestral/testbench#243]
Orchestra v3.8.1

Orchestra runs migration in this order:
1) Package migrations registered in package Service Provider: `database/migrations`
2) Application published migrations: `vendor/orchestra/testbench-core/laravel/database/migrations`
3) Package tests migrations: `tests/database/migrations`

I need to run package tests migrations first of all. How can I do it?

In `TestCase.php` I'm loading package test migrations:

```php
protected function setUp(): void
{
    parent::setUp();

    $this->loadMigrationsFrom(__DIR__ . '/database/migrations');
}
```

In test file there is `RefreshDatabase` trait.

Here is an example where I found this issue: [laravel-love/add-console-setup-commands](https://github.com/cybercog/laravel-love/blob/7b4a2a0b01081f38752919ac6c00830da3844757/tests/Unit/Console/Commands/SetupReacterableTest.php). Tests are working good until this case is executed. It creates migration file in application. [Next tests will fail](https://travis-ci.org/cybercog/laravel-love/jobs/541000626) because created migration will be runned before package test migrations which contains tables required for this case.

**Comment by antonkomarev** [comment]
Sorry, I was wrong with describing order in initial post, so I've edited it.

**Comment by crynobone** [comment]
What's the purpose of `RefreshDatabase` when you are testing with sqlite `:memory:` configuration?

**Comment by antonkomarev** [comment]
This is the same config for all my repositories (some of them using mysql in tests). To be assure that everything will be migrated from scratch on each run.

**Comment by crynobone** [comment]
Well, it's not useful and cause issue exactly as you experienced right now.

**Comment by crynobone** [comment]
> To be assure that everything will be migrated from scratch on each run.

`:memory:` already covers this. You don't need RefreshDatabase unless you are working with persistent database storage

**Comment by antonkomarev** [comment]
@crynobone thanks. I've removed all `RefreshDatabase` traits usage and added manual migrate launching command:

```php
$this->artisan('migrate', ['--database' => 'sqlite'])->run();
```

Now it seems to work.
