### ISSUE TITLE
Dependancy resolution issues when upgrading 3.5 > 3.8

### ISSUE THREAD

**Issue by andrewmclagan** [orchestral/testbench#244]
Issues when mocking out dependancies of a console `Command`.

We upgraded:

- PHPUnit `6` to `8`
- orchestral/testbench `~3.5` to `~3.8`

No code changes, tests pass when rolling back to previous versions. 

Also if we comment-out loading test migrations it works again:

```php
    /**
     * Setup the test environment.
     *
     * @return void
     * @throws Exception
     */
	protected function setUp(): void
	{
	    parent::setUp();

           // $this->loadMigrationsFrom(realpath(__DIR__.'/../database/migrations'));
	}	
```
The tests that fail mock out dependancies of a `Command`:

```php
    /**
     * @test
     */
    public function it_creates_an_index()
    {
        $this->mock(IndexManager::class, function ($mock) {
            $mock->shouldReceive('create')
                ->once()
                ->withNoArgs()
                ->andReturn(true);
        });

        $this->artisan('es:index-create')->run();
    }
```

The dependancy `IndexManager` is injected into the command via its constructor. If we call `resolve(get_class(IndexManger::class))` inside the Command that is under test it does not echo out the mocked dependancy, just the actual dependancy. Where previously under PHPUnit `6` and Testbench `~3.5` it echos out the Mockery dependancy.

I cant figure out why `loadMigrationsFrom` would effect this or what changes in the newer underlying Laravel version or Testbench setup would cause this? 

Will post more information as its available.

**Comment by crynobone** [comment]
We haven't changed anything on our end, the only recent changes to artisan command is to enable testing support for artisan command in that is coming from Laravel Framework testing class.

**Comment by andrewmclagan** [comment]
Okay, thats a start thank you. I will head-over to the laravel repo and see if people are reporting anything.

**Comment by andrewmclagan** [comment]
@crynobone I have investigated the internals of Testbench from `3.5` to `3.8` and there actually is a change that is effecting this. I will outline:

in `3.5` migrations are run via the trait: `Orchestra\Testbench\Concerns\WithLoadMigrationsFrom` without calling `->run()` and also setting the console kernel to null. Whereas in `3.8` there is a new class `Orchestra\Testbench\Database\MigrateProcessor` that calls `->run()` on the command.

see `3.5`:
```php
// ...
$this->artisan('migrate', $options);

$this->app[ConsoleKernel::class]->setArtisan(null);
// ...
```

see `3.8`:
```php
// ...
$console = $this->testbench->artisan($command, $this->options);

if ($console instanceof PendingCommand) {
    $console->run();
}
// ...
```

**Comment by andrewmclagan** [comment]
So ... narrowing it down even more:

in `3.8` there are _also_ changed to the artisan migrate command options

3.8:
```php
$options = \is_array($database) ? $database : ['--database' => $database];
$options['--path'] = 'migrations';
// then the 'migrate' command is called with $options
```

3.5:
```php
$options = is_array($realpath) ? $realpath : ['--realpath' => $realpath];
// then the 'migrate' command is called with $options
```

in `3.8` if i comment out `$options['--path'] = 'migrations';` ours tests pass

**Comment by andrewmclagan** [comment]
So in conclusion the difference between `3.8` and `3.5` is `$this->app[ConsoleKernel::class]->setArtisan(null);` is no longer called in `3.8` and  calling it manually addresses the issue

**Comment by crynobone** [comment]
Fixed in:

* https://github.com/orchestral/testbench-core/releases/tag/v3.6.7
* https://github.com/orchestral/testbench-core/releases/tag/v3.7.9
* https://github.com/orchestral/testbench-core/releases/tag/v3.8.5
