### ISSUE TITLE
Testing console commands

### ISSUE THREAD

**Issue by NoelDavies** [orchestral/testbench#245]
I have a command that I want to test, It's pretty simple, takes 2 arguments into the constructor (resolved from the container), runs over a few if statements and calls a method on an injected service dependant on the result of the conditionals.

Now, I want this to be tested (Test all the things) but can't seem to find a way, with or without testbench, to be able to test a console command.

My issue is that without `testbench`, I see issues like not being able to resolve facades, etc, which makes sense because the framework isn't present.

But with test bench, I get 
```
Error : Call to a member function getFormatter() on null
```
because the output writer is instantiated inside of `\Illuminate\Console\Command`.

Does anybody have any light they could help to shed on this issue? 

So far, the only solution I can think of is writing a `service` outside of the command, test that, and then just trust that the command works.

I've seen #98 but that doesn't really answer my question.

**Comment by Arkitecht** [comment]
We use a CommandTestCase class: https://gist.github.com/Arkitecht/bd4ef59ceca2a8a8b673d79ab1ba61a1

Then you can test by either running and checking for output, or checking db, or invoking methods on the command directly and checking returns

**Comment by NoelDavies** [comment]
The services that the console command I've created are already tested, so I'm more wanting to test that specific methods are called with specific arguments within this command by mocking the services and check the calls on them. The console command has very little output apart from a result (success/failed).

Does this make sense?

**Comment by crynobone** [comment]
I don't see it can't be done right now.

```php
$this->instance('GivenService', $service = Mockery::mock('GivenService'));

$service->shouldReceive('foo')->andReturn('bar');

$this->artisan('hello')->expectsOutput('bar');
```

https://laravel.com/docs/5.8/console-tests#expecting-input-and-output

**Comment by crynobone** [comment]
> It's pretty simple, takes 2 arguments into the constructor (resolved from the container)

This might be where things get tricky, but did you know you can actually do Dependency Injection via `Command::handle()` method?
