### ISSUE TITLE
Connection refused.. Need to use phpUnit xml config file instead getEnvironmentSetUp method

### ISSUE THREAD

**Issue by nanoarmando** [orchestral/testbench#248]
Hi guys, I just updated my project and now if I use the getEnvironmentSetUp method to configure the sqlite (memory) database I get a connection error refused

![Captura de Pantalla 2019-08-14 a la(s) 12 25 50 p  m](https://user-images.githubusercontent.com/21105862/63038231-af77ac80-be8e-11e9-9784-e0abb270d764.jpg)

but if I use the PHPUnit xml configuration file ... I get all my tests passed

![Captura de Pantalla 2019-08-14 a la(s) 12 29 33 p  m](https://user-images.githubusercontent.com/21105862/63038450-33319900-be8f-11e9-9e7a-f84a15d3b7e6.jpg)

**Comment by nanoarmando** [comment]
**Update**:  Even if i use the same "testing" connection on the xml file i get all my tests passed

![Captura de Pantalla 2019-08-14 a la(s) 12 34 26 p  m](https://user-images.githubusercontent.com/21105862/63038806-00d46b80-be90-11e9-92fa-05ec5784687a.jpg)

Any idea ?

**Comment by crynobone** [comment]
I'm guessing this more towards IDE related issue rather than Testbench. Pretty sure even Laravel itself uses `getEnvironmentSetUp` to setup database connection for it's own Integration testing.

**Comment by nanoarmando** [comment]
Even testing outside of IDE, i got the same behavior, i will change my code.. but if you guys can check it out it would great. 

![Captura de Pantalla 2019-08-14 a la(s) 12 46 34 p  m](https://user-images.githubusercontent.com/21105862/63040230-054e5380-be93-11e9-8162-74259cdc21d3.jpg)
![Captura de Pantalla 2019-08-14 a la(s) 12 47 02 p  m](https://user-images.githubusercontent.com/21105862/63040237-08494400-be93-11e9-96f9-dd8dfc439b37.jpg)

**Comment by crynobone** [comment]
See <https://github.com/laravel/framework/search?q=getEnvironmentSetUp+memory&unscoped_q=getEnvironmentSetUp+memory>

Laravel itself uses `getEnvironmentSetUp` to create `:memory:` database connection for it's integration tests running on Orchestra Testbench. If there is an issues, you'll not be the first to report it.
