### ISSUE TITLE
Improve documentation on loadMigrationsFrom

### ISSUE THREAD

**Issue by stancl** [orchestral/testbench#249]
Related to #247 

It should be explained that when using `$this->loadMigrationsFrom`, you must specify the database connection using `config(['database.default' => 'foo'])` and that you shouldn't run `migrate` manually.

**Comment by stancl** [comment]
I just discovered that I'm getting a "migrations table not found" error *after* a test succeeds. The issue was that the `tearDown()` method didn't use the right DB connection.

So it's also necessary to do this:

```php
protected function tearDown(): void
{
    config(['database.default' => 'foo']);

    parent::tearDown();
}
```

**Comment by crynobone** [comment]
No, `loadMigrationFrom()` doesn't modify the default database connection. It your "tenant" package that generally changed it.

**Comment by stancl** [comment]
I never said it modifies the default database connection. I'm just suggesting that it would be useful if the docs pointed out that
> when using `$this->loadMigrationsFrom`, you must specify the database connection using `config(['database.default' => 'foo'])` [when you want to change the DB connection]

**Comment by crynobone** [comment]
```php
$this->loadMigrationsFrom(['--path' => __DIR__.'/migrations', '--database' => 'foo']);
```

There no reason to swap **default** database connection. As I said this use case generally meant only for tenant package development.

**Comment by stancl** [comment]
I see. The `$paths` argument name is confusing https://github.com/orchestral/testbench-core/blob/db033c1bbe701e7c108e38a03e73d9112a25d55a/src/Concerns/WithLoadMigrationsFrom.php#L16

**Comment by stancl** [comment]
@crynobone 

> No, loadMigrationFrom() doesn't modify the default database connection

Actually, it *does*!

```php
dump(config('database.default'));
$this->loadMigrationsFrom([
    '--path' => realpath(__DIR__ . '/../src/assets/migrations'),
    '--database' => 'central',
]);
dd(config('database.default'));
```

```
"sqlite"
"central"
```

**Comment by crynobone** [comment]
```php
dump(config('database.default'));
$this->artisan('migrate', [
    '--path' => realpath(__DIR__ . '/../src/assets/migrations'),
    '--realpath' => true,
    '--database' => 'central',
]);
dd(config('database.default'));
```

```
"sqlite"
"central"
```

`loadMigrationFrom()` proxy the migrate artisan command, nothing more.

**Comment by stancl** [comment]
Okay, thanks. I'll open an issue at laravel/framework.
