### ISSUE TITLE
Factories not working correctly, results in call to a member function define on null error.

### ISSUE THREAD

**Issue by maikelmotivo** [orchestral/testbench#250]
Using factories does not work as intended in tests. Trying to call a factory results in the following error:
`Fatal error: Uncaught Error: Call to a member function define() on null`

This is for orchestra v3.8

These are the TestCase, Test and factory files being used.

```
namespace Tests;

use Orchestra\Testbench\Concerns\WithFactories;
use Orchestra\Testbench\TestCase as BaseTestCase;

class TestCase extends BaseTestCase
{
    use WithFactories;

    protected function setUp(): void
    {
        parent::setUp();

        $this->withFactories(__DIR__.'/../src/database/factories');
    }

    protected function getPackageProviders($app): array
    {
        return [
            // providers
        ];
    }

    protected function getPackageAliases($app)
    {
        return [
            // aliases
        ];
    }
}
```

```
namespace Tests\Feature;

use App\User;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;

class UserTest extends TestCase
{
    use WithFaker;

    private $user;

    public function setUp(): void
    {
        parent::setUp();

        $this->artisan('migrate');

        $this->user = factory(User::class)->create();
    }
}
```

```
/** @var \Illuminate\Database\Eloquent\Factory $factory */
use App\User;
use Illuminate\Support\Str;
use Faker\Generator as Faker;

$factory->define(User::class, function (Faker $faker) {
    return [
        'first_name' => $faker->firstName,
        'last_name' => $faker->lastName,
        'email' => $faker->unique()->safeEmail,
        'email_verified_at' => now(),
        'password' => '', // password
        'remember_token' => Str::random(10),
    ];
});
```

Can you tell me what could possibly be wrong here? Is this an implementation error or a bug in orchestra itself?

**Comment by crynobone** [comment]
There's no `App\User` unless you create the class manually.

**Comment by maikelmotivo** [comment]
Correct, i do create the class manually, that is not the issue here. The issue is that the method define() is called on a null, meaning that the variable $factory does not exist.

**Comment by crynobone** [comment]
It's definitely not a bug since I actively use that feature on few of my projects

**Comment by wotta** [comment]
Also keeping track of this issue since we work for the same company.

@crynobone that is correct, we looked how you did this and used the same setup.
Have you seen something like this before? And if so was it fixed at some point or do you not know that?

**Comment by crynobone** [comment]
> Have you seen something like this before?

`Fatal error: Uncaught Error: Call to a member function define() on null`

This error normally occur when you try to do `factory('Foo\User')->create()` when you for example registers

```php
$factory->define('Bar\User', function (Faker $faker) {
    return [
        'first_name' => $faker->firstName,
        'last_name' => $faker->lastName,
        'email' => $faker->unique()->safeEmail,
        'email_verified_at' => now(),
        'password' => '', // password
        'remember_token' => Str::random(10),
    ];
});
```

**Comment by wotta** [comment]
Thank you, I understand why you gave that advice.
I hope Maikel will come back with some results today so we can hopefully fix this.

Would you need some more things if we cannot figure this out?
For example a gist with the basic setup we have?

**Comment by crynobone** [comment]
* https://github.com/laravie/authen
* https://github.com/laravie/cabinet
* https://github.com/katsana/remote-control

All 3 projects uses factories without any problem.

**Comment by wotta** [comment]
@crynobone yeah I saw the top one :) 
I hope you don't interpreted my last message as if I didn't believe you.

I will be at work tomorrow so I hope he made progress by then.
Thanks in advance.

**Comment by crynobone** [comment]
No worries. The code is just a proxy to Laravel `ModelFactory` implementation. So it's hard to see how it would fail if everything is setup correctly.

**Comment by maikelmotivo** [comment]
Sorry for the late response, yesterday i was not able to find the time to work on this issue.

The issue was caused because the factory was placed in the src folder. I was trying to mimic default laravel structure and placed it the src\database\factories folder. By simply moving the factories folder to the test folder i was eventually able to resolve my issue.

Thanks for the help however!

**Comment by crynobone** [comment]
> The issue was caused because the factory was placed in the src folder. I was trying to mimic default laravel structure and placed it the src\database\factories folder.

Might be due to relative path between the actual tests file and the src folder. I not sure why you want to have `factories` in `src` since it would only be used for `tests`.

**Comment by culturegr** [comment]
@maikelmotivo  didi you managed to find a solution?  I am still stuck with `Fatal error: Uncaught Error: Call to a member function define() on null`

**Comment by wotta** [comment]
@culturegr I guess the issue you are having is that you have your factories in a namespaced folder that gets registered by the psr-4 autoloader.
You might want to move your factories to a non namespaced/autoloaded directory.

If this is not your issue we ( as in @maikelmotivo and I ) are unable to help you any further.

**Comment by culturegr** [comment]
@wotta Thank you for your answer. However I was able finally to solve the problem by keeping the `Factories` directory under `tests` folder (which btw is namespaced and psr-4 autoloaded) and twaking my `phpunit.xml` file as follows:

```xml

// This did NOT work :cry: 
    <testsuites>
        <testsuite name="Package">
            <directory suffix=".php">./tests/</directory>
        </testsuite>
    </testsuites>

// This works :smiley: 
    <testsuites>
        <testsuite name="Package">
            <directory suffix="Test.php">./tests/</directory>
        </testsuite>
    </testsuites>
```

Notice that I had to provide *a more specific suffix* (my tests are in the form of `FooTest.php`)

**Comment by wotta** [comment]
@culturegr aah yes. That's another way to solve it!
Have a nice day 🙂

**Comment by jva91** [comment]
Thx @culturegr  this helps me a lot for running the tests

**Comment by ahthomsen** [comment]
I had the same problem and it turned out that I had forgotten to delete the following tag for the relevant test file: 

/**
 * @runTestsInSeparateProcesses
 */

Thought it might be helpful for someone in the future
