### ISSUE TITLE
Custom Global Http Exception Handler

### ISSUE THREAD

**Issue by michaviehauser** [orchestral/testbench#251]
Hi there,

I am looking for a way to register a global exception handler for HTTP requests.

Use case would be to e.g. catch an InvalidArgumentException and convert it to a 400 status code.

What would be the intended way to achieve this?

Thanks!

**Comment by crynobone** [comment]
You can override [resolveApplicationExceptionHandler](https://github.com/orchestral/testbench-core/blob/v4.0.0/src/Concerns/CreatesApplication.php#L282-L292) **only for testing** purpose.
