### ISSUE TITLE
Issue with routing and $_GET variables

### ISSUE THREAD

**Issue by ROTGP** [orchestral/testbench#252]
I'm having an issue with routing and accessing the current route and $_GET variables when run from within testbench. 

In `getEnvironmentSetUp` I define the route as follows:

```
$router = $app['router'];
$router->get('/items', function () {
    return Item::all();
})->name('items');
```

Then in a test I call:
`$response = $this->get('/items?foo=bar');`

This works fine and the items are returned, however, from within my package I need to know which route is currently being called, by calling `url()->current()`, as well as access to the request's $_GET variables, by calling `Input::get()`. 

Calling these in a normal environment returns what I expect (`http://localhost/items` and `['foo' => 'bar']`), but when running tests with testbench they're always `http://localhost` and `null`.  I've tried using the route() method as well (together with a named route), but with no luck. 

Am I missing something? Are there any examples/tests which might illustrate how to do this? I've looked at [this](https://github.com/orchestral/testbench-core/blob/ce1b8b329967c022a43a5efae4fdd9080eca3a6b/tests/RouteTest.php)  test but again, no luck.  

I've also tried solutions offered [here](https://stackoverflow.com/questions/47474554/laravel-phpunit-testing-get-with-parameters) but with no success

**Comment by crynobone** [comment]
```php
    /** @test */
    public function it_can_get_request_information()
    {
        $this->app['router']->get('hello', ['uses' => function () {
            return 'hello world';
        }]);

        $this->call('GET', 'hello?foo=bar');

        $this->assertSame('http://localhost/hello?foo=bar', url()->full());
        $this->assertSame('http://localhost/hello', url()->current());
        $this->assertSame(['foo' => 'bar'], request()->all());
    }
```

**Comment by ROTGP** [comment]
The above code works fine, but using the exact same code to test my own code fails.

Say for example I have a model in my package:
```
class Item extends Model
{
   protected static function boot()
    {
        parent::boot();
        dd(url()->current(), request()->all());
}
```
and then I execute the following test:
```
$this->app['router']->get('items', ['uses' => function () {
        return Item::all();
}]);

$response = $this->call('GET', 'items?foo=bar');
```
I would expect to see a dump of `http://localhost/items', and `['foo' => 'bar']`, but I'm getting `http://localhost', and `null`. If I test this in the browser (or postman, or similar), I get the values that I'm expecting.  I'm guessing there's something else I'm doing wrong but I can't pinpoint it.

**Comment by crynobone** [comment]
You have to understand that in phpunit everything is run under command line and only when you make a request Laravel will rebind a request object while on a web request a request object is used based on the web request itself

**Comment by ROTGP** [comment]
Ok so, this is expected behaviour? If so feel free to close.

**Comment by crynobone** [comment]
> Sorry if this is beyond the scope of your package.

It is, Testbench main priority is to create a "sandbox" environment for packages to run tests on Laravel, all the request code is coming directly from Laravel Framework "Testing" classes so the behaviour that you are experiencing will exist in Testbench and Laravel. 

To overcome this the only way is to use Laravel Dusk where you are making a real HTTP request during the tests.

**Comment by crynobone** [comment]
Laravel create the request object early on under [laravel/laravel "public/index.php"]( https://github.com/laravel/laravel/blob/master/public/index.php#L54-L56)

```php
$response = $kernel->handle(
    $request = Illuminate\Http\Request::capture()
);
```

While during tests, it's only created when you run `->get()`, `->post()`, ... or `->call()`

See [Illuminate\Foundation\Testing\Concerns\MakesHttpRequests::call()](https://github.com/laravel/framework/blob/6.x/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php#L433-L435)

```php
$response = $kernel->handle(
    $request = Request::createFromBase($symfonyRequest)
 );
```

**Comment by ROTGP** [comment]
> While during tests, it's only created when you run ->get(), ->post(), ... or ->call()

And I did indeed run `->call('GET', 'items', ['foo' => 'bar'])` during the tests, so I'm surprised that it failed.

**Comment by ROTGP** [comment]
Just to follow up, this was indeed a bad assumption on my part (about the lifecycle of eloquent models). That being said, there's no reason why request variables and routes can't be accessed by models/controllers when testing with testbench. Thanks again
