### ISSUE TITLE
Setting app config by reading package config in service provider is not supported.

### ISSUE THREAD

**Issue by halaei** [orchestral/testbench#257]
I need to call this function inside my service provider to move some values from package's config to database config:
```php
    protected function addRedisConfigs()
    {
        $config = config('my-package.redis-servers');
        foreach ($config as $name => $params) {
            config(['database.redis.'.$name => $params]);
        }
    }
```
The function has to be called before Laravel creates instance of `Illuminage\Redis\RedisManager` because the object reads the config only once in the constructor. So any config change after creation of redis manager is not affected.
That means the only safe place to call `addRedisConfigs()` is in `MyServiceProvider::register()` method. However, if I do that, package tests fails because `config()` doesn't really work in register phase under testbench. For testbench to work, I need to call `addRedisConfigs()` in `boot()`. So I guess this issue is a lack of config feature support in testbench?

**Comment by crynobone** [comment]
> However, if I do that, package tests fails because config() doesn't really work in register phase under testbench.

Provide prove or step that you took to cause the tests to failed.
