### ISSUE TITLE
Faking the DB Facade causes the teardown to break.

### ISSUE THREAD

**Issue by nmc9** [orchestral/testbench#260]
- Testbench Version: 4.x-dev
- Laravel Version: 6.x-dev
- PHP Version: 7.3.1
- Database Driver & Version: Mysql Ver 14.14 Distrib 5.7.28, for Linux (x86_64)
### Description:
Faking the DB Facade causes the teardown to break. 

It only happens when you add migrations. When the migration teardown runs it uses the mocked facade instead of a real one so it breaks.

### Exception:

> Mockery\Exception\BadMethodCallException: Received Mockery_2_Illuminate_Database_DatabaseManager::connection(), but no expectations were specified
> 
> ~\vendor\laravel\framework\src\Illuminate\Support\Facades\Schema.php:41
> ~\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php:166
> ~\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php:255
> ~\database\migrations\2016_06_01_000005_create_example_balance_table.php:35
> ~\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php:392
> ~\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php:401
> ~\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php:363
> ~\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php:284
> ~\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php:234
> ~\vendor\laravel\framework\src\Illuminate\Database\Console\Migrations\RollbackCommand.php:63
> ~\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:32
> ~\vendor\laravel\framework\src\Illuminate\Container\Util.php:36
> ~\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:90
> ~\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:34
> ~\vendor\laravel\framework\src\Illuminate\Container\Container.php:590
> ~\vendor\laravel\framework\src\Illuminate\Console\Command.php:134
> ~\vendor\symfony\console\Command\Command.php:255
> ~\vendor\laravel\framework\src\Illuminate\Console\Command.php:121
> ~\vendor\symfony\console\Application.php:1001
> ~\vendor\symfony\console\Application.php:271
> ~\vendor\symfony\console\Application.php:147
> ~\vendor\laravel\framework\src\Illuminate\Console\Application.php:93
> ~\vendor\laravel\framework\src\Illuminate\Console\Application.php:185
> ~\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php:273
> ~\vendor\laravel\framework\src\Illuminate\Foundation\Testing\PendingCommand.php:137
> ~\vendor\orchestra\testbench-core\src\Database\MigrateProcessor.php:73
> ~\vendor\orchestra\testbench-core\src\Database\MigrateProcessor.php:56
> ~\vendor\orchestra\testbench-core\src\Concerns\WithLoadMigrationsFrom.php:33
> ~\vendor\orchestra\testbench-core\src\Concerns\Testing.php:204
> ~\vendor\orchestra\testbench-core\src\Concerns\Testing.php:90
> ~\vendor\orchestra\testbench-core\src\TestCase.php:51

### Steps To Reproduce:

Here is my test code

```
    public function test_can_view_keys_from_users_table(){
        $this->loadMigrationsFrom(__DIR__ . '/../../database/migrations');
        $this->withFactories(__DIR__ . '/../../database/factories');

        \DB::shouldReceive('select')->once();

        \DB::select("SHOW KEYS FROM users");
    }
```

**Comment by GrahamCampbell** [comment]
I think this is to be expected?

**Comment by crynobone** [comment]
Why would you run migration and suddenly fake the db connection. 

This definitely is expected.

**Comment by nmc9** [comment]
Wow. I had the migrations in the setup() and I didn't even think to take them out. Yeah I can see why that wouldn't work.
