### ISSUE TITLE
Failure on first run

### ISSUE THREAD

**Issue by afonsogloeden** [orchestral/testbench#261]
- Testbench Version: v4.6.0
- Laravel Version: v6.17.1
- PHP Version: 7.4.3
- Database Driver & Version: Not using

### Description:
I'm developing a package for Laravel where it has a configuration file, when I run tests to check the values of these settings, the first two tests of the first run always fail, if you run the tests again, the tests are successful. An example of the errors can be found [here](https://github.com/afonsogloeden/encrypted-responses-laravel/actions/runs/47850860).

### Steps To Reproduce:
```sh
git clone https://github.com/afonsogloeden/encrypted-responses-laravel.git
cd encrypted-responses-laravel
composer install && vendor/bin/phpunit # Fail
vendor/bin/phpunit # Pass
```

**Comment by crynobone** [comment]
Can't replicate the issue on my projects (with configuration file).

**Comment by crynobone** [comment]
Not a Testbench bug.

You code simply missing `mergeConfigFrom()`, refer to <https://laravel.com/docs/6.x/packages#configuration>

**Comment by afonsogloeden** [comment]
You're right, sorry about that.
