### ISSUE TITLE
Questions about really slow tests

### ISSUE THREAD

**Issue by boris-glumpler** [orchestral/testbench#263]
Not really a bug report or feature request, just a quick question. 

Some context... I've only started using testbench a couple weeks ago and it does exactly what it says, cheers! I have noticed, however, that any test classes extending `Orchestra\Testbench\TestCase` are really slow locally. I have one package with 28 tests, for example, that take about 15 min to run. When these same tests run via Github Actions they only take around 3.5 min, so already considerably faster. That package was extracted from a Laravel project, where the same tests only took a small fraction of that time. 

I just use Homebrew/Phpbrew locally, so no Homestead or Valet. Off the top of your head, do you know what could cause these slow tests? Is it maybe my dev environment and nothing to do with testbench?

Here's the repo in question: https://github.com/ShabuShabu/Abseil

Thanks!

**Comment by crynobone** [comment]
I would presume that has something to do with enable XDebug on your local machine.

![Screenshot 2020-04-20 at 10 27 26 PM](https://user-images.githubusercontent.com/172966/79763071-24707f80-8356-11ea-9718-714b73415926.png)

**Comment by boris-glumpler** [comment]
Did not think of XDebug, cheers! Disabled it and tests now run in a couple seconds. Thanks!
