### ISSUE TITLE
Testing routes

### ISSUE THREAD

**Issue by innoflash** [orchestral/testbench#264]
Forgive me for this rather silly question but how exactly do we test routes with testbench. All i have tried so far has given me a 404 error.

```php
$response = $this->post('api/auth/login', [
	'email' => 'email@gmail.com',
	'password' => 'secret'
]);
```

I seem to get a 404, what am i missing?

**Comment by innoflash** [comment]
@crynobone i just get error 404 if i try the code above, do i have to do something specific to setup route testing. I haven`t found working solutions. The same code works if i test it on default laravel app but when am working on a package separately i get the 404

**Comment by crynobone** [comment]
Where does this route coming from, how does the package load this route, has testbench known about this route? 

All this questions need to be answered for someone else to understand where you need to change.

But if you just asking me if routes can be tested, the answer is yet it is working.

**Comment by innoflash** [comment]
I am loading the routes in the service provider as i would in the normal package. Now that you mentioned it, how do i make testbench be aware of those routes.

**Comment by crynobone** [comment]
By default Testbench does require you to load service provider manually.

https://github.com/orchestral/testbench#custom-service-provider

**Comment by innoflash** [comment]
@crynobone yes i did load the custom service provider in my parent `TestCase`

```php
//TestCase.php
    protected function getPackageProviders($app)
    {
        return [
            FaithGenSDKServiceProvider::class,
            AuthServiceProvider::class,
            EventServiceProvider::class,
        ];
    }
```

**Comment by crynobone** [comment]
If the package service provider has been load properly, you should be able to test routes. 

This has been used in many packages without a problem. Again, I don't have enough information to see what went wrong on your case.

**Comment by innoflash** [comment]
I do not know if this will help but the files are short if you can inspect.

I do not know how else to load the services apart from how i read it on the doc.

[https://github.com/faithgen/laravel-sdk/blob/master/tests/TestCase.php](https://github.com/faithgen/laravel-sdk/blob/master/tests/TestCase.php) is the parent test.

and its failing when i run this test [https://github.com/faithgen/laravel-sdk/blob/9aebd5a3dc3116e3b0f3e7991228351d8e41746a/tests/Feature/MinistryTest.php#L129](https://github.com/faithgen/laravel-sdk/blob/9aebd5a3dc3116e3b0f3e7991228351d8e41746a/tests/Feature/MinistryTest.php#L129)

If i dd() that response it 404 written all over it.

**Comment by crynobone** [comment]
Does the test register `faithgen-sdk.prefix` config anywhere? 

Unless this config is not published on the "testbench" environment, the booted Laravel wouldn't know about it.

**Comment by innoflash** [comment]
Oh yeah, you are really helping here sir.I do not remember setting up any prefix. So you mean i have to write code to mimic the config file in the setup right?

**Comment by crynobone** [comment]
Yup, you either need to publish the config during the test bootstrap or use `getEnvironmentSetup()` to register the default configuration.

**Comment by innoflash** [comment]
Now i am kinda stuck here :)

How do i do any of those, i can't seem  to see a method like `$this->mergeConfig()` on the `Orchestra/Testbench/TestCase` same way it is for migrations

**Comment by innoflash** [comment]
I just found out why it always never worked, i set a middleware to show the route for certain condition and it wasn`t passing. Thanks a lot sir.
