### ISSUE TITLE
`view` routes are run before the migrations

### ISSUE THREAD

**Issue by edalzell** [orchestral/testbench#265]
- Testbench Version: 4.8
- Laravel Version: 6.18.11
- PHP Version: 7.4
- Database Driver & Version: SQLite

### Description:

I have `Route::view(...)` that cause errors when I attempt to run my tests (that have nothing to do with those routes. I get "table not found" errors.

### Steps To Reproduce:

A route that causes the issue:
```
        Route::view('customers', 'charge::cp.customers', ['customers' => User::customers()->get()])
            ->name('index');
```

I do load the migrations in my base FeatureTestcase:
```
    protected function setUp(): void
    {
        parent::setUp();

        Eloquent::unguard();

        $this->loadMigrationsFrom(__DIR__.'/../__migrations__');
        $this->loadMigrationsFrom(__DIR__.'../../../../laravel/cashier/database/migrations');
    }
```

It is a migration in `__migrations__` that has the `users` table (copied from Laravel).

Is this a timing issue or have I done something wrong? Is there anyway I can keep the `view` route AND have my tests run fine?

Apologies if this is the wrong place for this, I did look through the existing issues and did a Google search.

Thanks for this amazing package...made my dev life so much better!

**Comment by crynobone** [comment]
```php
Route::view('customers', 'charge::cp.customers', ['customers' => User::customers()->get()])
            ->name('index');
```

I wouldn't recommend doing this structure at all, when developer install your package they will have the same problem if `User::customers()` migration is not available in the database. 

I would suggest using an invokable controller for this usage.
