### ISSUE TITLE
Custom error handler

### ISSUE THREAD

**Issue by innoflash** [orchestral/testbench#266]
So testbench does not use default `App` classes but in a regular Laravel app we use` App\Exceptions\Handler::class` for catching errors and we can make changes in it. 

How do edit make changes (override render function) on the error handler on testbench?

**Comment by crynobone** [comment]
You can always override the default handler.

```php
    /**
     * Resolve application HTTP exception handler.
     *
     * @param  \Illuminate\Foundation\Application  $app
     *
     * @return void
     */
    protected function resolveApplicationExceptionHandler($app)
    {
        $app->singleton('Illuminate\Contracts\Debug\ExceptionHandler', 'Orchestra\Testbench\Exceptions\Handler');
    }
```

**Comment by innoflash** [comment]
worked, thanks mate
