### ISSUE TITLE
Add Laravel 8 Branch Support

### ISSUE THREAD

**Issue by lancepioch** [orchestral/testbench#268]
Add Laravel 8 Branch Support :)

**Comment by GrahamCampbell** [comment]
This is already done... https://github.com/orchestral/testbench/blob/master/composer.json

**Comment by lancepioch** [comment]
There doesn't seem to be a tag or branch for it.

**Comment by crynobone** [comment]
Stable tag will only be added when Laravel 8 has been released, not before.
