### ISSUE TITLE
Question: How to use the new class-based model factory ?

### ISSUE THREAD

**Issue by vishytk** [orchestral/testbench#271]
I am testing with using the latest version of orchestra/testbench (6.0) and I am getting UserFactory not found error when I run the test. Basically, the User::factory()->create() called from within the test file is looking for the UserFactory inside the Models folder instead of database/factories folder.

Attached the code. Please help.

[l8-testing.zip](https://github.com/orchestral/testbench/files/5197018/l8-testing.zip)

**Comment by crynobone** [comment]
I would recommend using `UserFactory::new()->create()` instead of referring from the model as reference from the model would require you to register custom namespace globally.
