### ISSUE TITLE
Testing cached routes

### ISSUE THREAD

**Issue by bumbummen99** [orchestral/testbench#274]
- Testbench Version: 6.0.0
- Laravel Version: 8.1.0
- PHP Version: 7.4.0
- Database Driver & Version: -

### Description:

I am sorry if this has already been clarified somewhere but is there any way to test cached routes? Doing something like: 
```php
$this->artisan('route:cache');
```
in my test does provoke the following error when calling [getFreshApplicationRoutes](https://github.com/laravel/framework/blob/ea4796e333acda062b4c205c6bd61eca69cec6e0/src/Illuminate/Foundation/Console/RouteCacheCommand.php#L55) in the command handle method:
`CodeZero\LocalizedRoutes\Tests\Unit\UrlGeneratorTest::it_does_also_work_with_cached_routes
ErrorException: require(/home/patrick/private/workspace/laravel-localized-routes/vendor/orchestra/testbench-core/laravel/bootstrap/app.php): failed to open stream: No such file or directory`

### Steps To Reproduce:
- Use route:cache in a test.

**Comment by crynobone** [comment]
You might need to build a custom command if you need that, not supported by Testbench.

**Comment by crynobone** [comment]
The reason why Laravel had to boot-up a fresh application instance
