### ISSUE TITLE
Unable to use **Laravel Time Testing Helper**

### ISSUE THREAD

**Issue by plateena** [orchestral/testbench#275]
- Testbench Version: 6.0.0
- Laravel Version: 8.x
- PHP Version: 7.3
- Database Driver & Version: SQLite 

### Description:
Unable to use **Laravel Time Testing Helper**

### Steps To Reproduce:
1. Use `$this->travel(5)->hours();`
 2. Get an error `Call to undefined method ::travel()`

**Comment by crynobone** [comment]
Need to use the new `WormHole` trait. Can you try it out and report back.

**Comment by plateena** [comment]
Can't find Wormhole traits. It's a class.
Can you show me how to use it?

**Comment by crynobone** [comment]
https://www.github.com/laravel/framework/tree/8.x/src%2FIlluminate%2FFoundation%2FTesting%2FWormhole.php

**Comment by plateena** [comment]
So we use it like:
`(new Wormhole(5))->hours(function() {
// Our test here
});`

Is that correct?

**Comment by crynobone** [comment]
Sorry, it's actually `InteractsWithTime` trait. 

Pushed a fix on 6.x https://github.com/orchestral/testbench-core/commit/eda5dbd754ff84bbbbc51fa94dc7e8aea05ca4e7

**Comment by crynobone** [comment]
Fixed in `6.1.0`.
