### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by Jhnbrn90** [orchestral/testbench#276]
Dear @crynobone 

I am not sure, but I guess the ["Class 'Illuminate\Database\Eloquent\Factory' not found"](https://github.com/orchestral/testbench#class-illuminatedatabaseeloquentfactory-not-found) section in `README.md` contains a typo, where "Laravel 6" should be "Laravel 5.6". 

Is this correct or am I missing something?

> Laravel | Minimum Versions
> -- | --
> 5.5 | 3.5.6
> 5.6 | 3.6.7
> 5.7 | 3.7.8
> 5.8 | 3.8.6
> 6.x | 4.8.0
> 7.x | 5.2.0
>
> E.g: If you need to support minimum Laravel 6 here how the requirement should look like in composer.json:
> 
> ```
> {
>     "require-dev": {
>         "orchestra/testbench": "~3.6.7 || ~3.7.8 || ~3.8.6 || ^4.8 || ^5.2 || ^6.0"
>     }
> }
> ```

**Comment by crynobone** [comment]
You are correct, fixed.

Thank you.
