### ISSUE TITLE
Error install Version 5.0 higher for Laravel 7

### ISSUE THREAD

**Issue by antweny** [orchestral/testbench#277]
- Testbench Version: 5.0
- Laravel Version: 7.29
- PHP Version: 7.4
- Database Driver & Version:

### Description:

I'm developing a package for Laravel 7 so want to use this package for testing. I have tried to install version 5.0 which is compatible with Laravel 7 latest update. but not working

### Steps To Reproduce:

This is how I'm doing in the new package directory and the errors I'm getting

![error 1](https://user-images.githubusercontent.com/28085591/98033749-fe5c8980-1e26-11eb-89a2-cc5b3d5b8f75.JPG)
![error2](https://user-images.githubusercontent.com/28085591/98033753-00264d00-1e27-11eb-994e-a4c984a8f8a3.JPG)

need help

**Comment by crynobone** [comment]
The error message is clear and you should follow the step. This is a composer requirement to access repositories on GitHub rather than a bug with Testbench.
