### ISSUE TITLE
Unresolvable dependency resolving [Parameter #0 [ <required> $request ]] 

### ISSUE THREAD

**Issue by realtebo** [orchestral/testbench#279]
- Testbench Version:  "orchestra/testbench": "^6.4"
- Laravel Version: 8.x
- PHP Version: 7.3
- Database Driver & Version: sqlite - not relevant

### Description:

When calling $this->post  u receive this error

```
Illuminate\Contracts\Container\BindingResolutionException : Unresolvable dependency resolving [Parameter #0 [ <required> $request ]] in class Illuminate\Http\Client\Request
```

### Steps To Reproduce:

In my package, in tests/Feature/ImageUploadText.php i'm doing this to simulate posting of a new image

```
        Storage::fake('image_upload');

        $fake_image = UploadedFile::fake()->image('photo1.jpg');

        $response = $this->post(route('package.product-image.upload'), [
            'file' => $fake_image
        ]);

        $response->assertStatus(200);
```

The called controller, part of this package, is trying to simply do this

```
use Illuminate\Http\Client\Request;

....

    public function upload(Request $request)
    {
        return "Ciao";
    }

...
```

I receive this error

```
Illuminate\Contracts\Container\BindingResolutionException : Unresolvable dependency resolving [Parameter #0 [ <required> $request ]] in class Illuminate\Http\Client\Request
```

There is something to do to be able to call $this->post from a package test?

> Note: my test class is extending a TestCase which is extending OrchestraTestCase

**Comment by crynobone** [comment]
it should have been 

```php
use Illuminate\Http\Request;
```

and not

```php
use Illuminate\Http\Client\Request;
```
