### ISSUE TITLE
Problem with Laravel 6: parseTestMethodAnnotations

### ISSUE THREAD

**Issue by szepeviktor** [orchestral/testbench#281]
`"laravel/framework": "^6.18",`

Hello!

An update to testbench-core 4.11.0 breaks our project: Larastan.
Please see https://github.com/nunomaduro/larastan/issues/732
and https://github.com/nunomaduro/larastan/pull/731#issuecomment-742100530

Was it planned?

**Comment by crynobone** [comment]
Fixed in 

Testbench Core: `v4.11.1`
Testbench: `v4.12.2`

**Comment by szepeviktor** [comment]
Thank you.
Great speed.

**Comment by stancl** [comment]
Getting the same issue on `^6.6`

**Comment by stancl** [comment]
And on any other 6.x version too. Seems to be due to testbench-core not having a new 6.x release with this patch.

**Comment by blimundo** [comment]
I have tried versions 6.5 and 6.6, same issue. How to fix it?

**Comment by crynobone** [comment]
Create a new issue with full details.
