### ISSUE TITLE
Artisan command helper does not return status code

### ISSUE THREAD

**Issue by MatasElectronics** [orchestral/testbench#283]
- Testbench Version: 6.7.2
- Laravel Version: 8.21.0
- PHP Version: 7.3.21
- Database Driver & Version: SQL Server

### Description:
We've been using the Artisan command helper to run migrations on our CI pipeline.
But apparently the command does not return the status code, so for instance when a migration fails, we still get a 'success' on the CI job.

### Steps To Reproduce:
1. Create a migration that fails.
2. Run `testbrench migrate`
3. The status code from the command is incorrect.

**Comment by crynobone** [comment]
Feel free to submit a PR for this.

**Comment by MatasElectronics** [comment]
@crynobone I've been trying to look into this, but seem to be stuck.

I've tracked it down to a certain line where the `testbench migrate` command result seems to deviate from `artisan migrate`.

Inside the `Illuminate\Foundation\Console\Kernel::handle` method, we have a `try/catch` construct that catches any errors returned by the framework, and it should return a status code of `1` when an exception is thrown.

This works fine when you run `artisan migrate`, but when you run `testbench migrate` you get the same output, but the status code is `0`.

When I comment out the `$this->reportException($e)` line, it does seem to work, so it makes me think it has something to do with the exception handler. But this is where I'm stuck for now.

Maybe you can have a look? If I can help in any way, please let me know.

**Comment by crynobone** [comment]
This should be fixed on the latest Testbench 6.

**Comment by MatasElectronics** [comment]
@crynobone Sadly the last update broke our entire setup. It seems to be the related to the Ray integration. Inside the service provider Ray is trying to register a Query watcher, but it can not find the database connection that is specified in the `testbench.yaml`

**Comment by MatasElectronics** [comment]
Is there a way to just have Testbench skip the entire Ray integration? We're not using it, so it's not solving anything for us, and only causing us troubles right now.
If not I will for now just stick to an older tag.
