### ISSUE TITLE
Question: How to test using Laravel Sanctum

### ISSUE THREAD

**Issue by vishytk** [orchestral/testbench#284]
- Testbench Version: 6.7.2
- Laravel Version: 8.18.1
- PHP Version: 8.0
- Database Driver & Version: sqlite, memory

I am creating a package that uses Sanctum Cookie based authentication (SPA) and written a test which fails with Unauthenticated message.

My Code: 

1. ServiceProvider

    /**
     * Register the application services.
     */
    public function register()
    {
        App::register('Laravel\Sanctum\SanctumServiceProvider');
    }

2. tests/TestCase.php

    protected function getEnvironmentSetUp($app)
    {
        $app['config']->set('cors.paths',['api/*', 'sanctum/csrf-cookie']);
        $app['config']->set('cors.supports_credentials', true);
        $app['config']->set('sanctum.stateful', 'localhost');
        $app['config']->set('session.domain', 'localhost');
    }

3. The Feature/TestFile

    public function setUp(): void
    {
        parent::setUp();

        $this->user = UserFactory::new()->create([
            'username' => 'admin',
            'firstname' => 'Babruvahana',
            'password' => 'secret',
        ]);
    }

    /** @test */
    public function an_authenticated_user_can_access_own_profile_data()
    {
        $response = $this->actingAs($this->user, 'api')
            ->get('/api/auth/user');
        dump($response);

        // $response->assertStatus(200);
        // $response->assertJsonFragment([
        //     'username' => 'admin',
        //     'firstname' => 'Babruvahana',
        // ]);
    }

4. Output of dump
  +baseResponse: Illuminate\Http\RedirectResponse^ {#2348
    #request: Illuminate\Http\Request^ {#1320
      #json: null
      #convertedFiles: null
      #userResolver: Closure($guard = null)^ {#1322
        class: "Illuminate\Auth\AuthServiceProvider"
        this: Illuminate\Auth\AuthServiceProvider {#598 …}
        use: {
          $app: Illuminate\Foundation\Application {#634 …}
        }
      }
      #routeResolver: Closure()^ {#1326
        class: "Illuminate\Routing\Router"
        this: Illuminate\Routing\Router {#455 …}
        use: {
          $route: Illuminate\Routing\Route {#443 …}
        }
      }
      +attributes: Symfony\Component\HttpFoundation\ParameterBag^ {#1319
        #parameters: []
      }
      +request: Symfony\Component\HttpFoundation\InputBag^ {#1317
        #parameters: []
      }
      +query: Symfony\Component\HttpFoundation\InputBag^ {#1317}
      +server: Symfony\Component\HttpFoundation\ServerBag^ {#1315
        #parameters: array:16 [
          "SERVER_NAME" => "localhost"
          "SERVER_PORT" => 80
          "HTTP_HOST" => "localhost"
          "HTTP_USER_AGENT" => "Symfony"
          "HTTP_ACCEPT" => "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
          "HTTP_ACCEPT_LANGUAGE" => "en-us,en;q=0.5"
          "HTTP_ACCEPT_CHARSET" => "ISO-8859-1,utf-8;q=0.7,*;q=0.7"
          "REMOTE_ADDR" => "127.0.0.1"
          "SCRIPT_NAME" => ""
          "SCRIPT_FILENAME" => ""
          "SERVER_PROTOCOL" => "HTTP/1.1"
          "REQUEST_TIME" => 1610074427
          "PATH_INFO" => ""
          "REQUEST_METHOD" => "GET"
          "REQUEST_URI" => "/api/auth/user"
          "QUERY_STRING" => ""
        ]
      }
      +files: Symfony\Component\HttpFoundation\FileBag^ {#1314
        #parameters: []
      }
      +cookies: Symfony\Component\HttpFoundation\InputBag^ {#1316
        #parameters: []
      }
      +headers: Symfony\Component\HttpFoundation\HeaderBag^ {#1313
        #headers: array:5 [
          "host" => array:1 [
            0 => "localhost"
          ]
          "user-agent" => array:1 [
            0 => "Symfony"
          ]
          "accept" => array:1 [
            0 => "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
          ]
          "accept-language" => array:1 [
            0 => "en-us,en;q=0.5"
          ]
          "accept-charset" => array:1 [
            0 => "ISO-8859-1,utf-8;q=0.7,*;q=0.7"
          ]
        ]
        #cacheControl: []
      }
      #content: null
      #languages: null
      #charsets: null
      #encodings: null
      #acceptableContentTypes: array:4 [
        0 => "text/html"
        1 => "application/xhtml+xml"
        2 => "application/xml"
        3 => "*/*"
      ]
      #pathInfo: "/api/auth/user"
      #requestUri: "/api/auth/user"
      #baseUrl: ""
      #basePath: null
      #method: "GET"
      #format: null
      #session: null
      #locale: null
      #defaultLocale: "en"
      -preferredFormat: null
      -isHostValid: true
      -isForwardedValid: true
      -isSafeContentPreferred: null
      basePath: ""
      format: "html"
    }
    #session: Illuminate\Session\Store^ {#2355
      #id: "A5cVAzUvONQAhkHB5Bmk4EVmOqlWJbZI7b9f4TL4"
      #name: "laravel_session"
      #attributes: array:1 [
        "url" => array:1 [
          "intended" => "http://localhost/api/auth/user"
        ]
      ]
      #handler: Illuminate\Session\ArraySessionHandler^ {#2304
        #storage: []
        #minutes: 120
      }
      #started: false
    }
    #targetUrl: "http://localhost/api/auth/login"
    +headers: Symfony\Component\HttpFoundation\ResponseHeaderBag^ {#2353
      #computedCacheControl: array:2 [
        "no-cache" => true
        "private" => true
      ]
      #cookies: []
      #headerNames: array:4 [
        "cache-control" => "Cache-Control"
        "date" => "Date"
        "location" => "Location"
        "content-type" => "Content-Type"
      ]
      #headers: array:4 [
        "cache-control" => array:1 [
          0 => "no-cache, private"
        ]
        "date" => array:1 [
          0 => "Fri, 08 Jan 2021 02:53:47 GMT"
        ]
        "location" => array:1 [
          0 => "http://localhost/api/auth/login"
        ]
        "content-type" => array:1 [
          0 => "text/html; charset=UTF-8"
        ]
      ]
      #cacheControl: []
    }
    #content: """
      <!DOCTYPE html>\n
      <html>\n
          <head>\n
              <meta charset="UTF-8" />\n
              <meta http-equiv="refresh" content="0;url='http://localhost/api/auth/login'" />\n
      \n
              <title>Redirecting to http://localhost/api/auth/login</title>\n
          </head>\n
          <body>\n
              Redirecting to <a href="http://localhost/api/auth/login">http://localhost/api/auth/login</a>.\n
          </body>\n
      </html>
      """
    #version: "1.1"
    #statusCode: 302
    #statusText: "Found"
    #charset: null
    +original: null
    +exception: Illuminate\Auth\AuthenticationException^ {#2349
      #guards: array:1 [
        0 => "sanctum"
      ]
      #redirectTo: "http://localhost/api/auth/login"
      #message: "Unauthenticated."
      #code: 0
      #file: "./vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php"

**Comment by crynobone** [comment]
I personally doesn't use Sanctum and doesn't have any idea on this one. But anything JavaScript + multi request testing should actually use Testbench Dusk.
