### ISSUE TITLE
Error: Call to undefined method Tests\ValidationRuleTest::getAnnotations() when run github action

### ISSUE THREAD

**Issue by vanthao03596** [orchestral/testbench#302]
- Testbench Version: 6.0.0
- Laravel Version: 7, 8
- PHP Version: 7.4, 8
- Database Driver & Version: sqlite

### Description:
When run command ./vendor/bin/testbench package:test --parallel --no-coverage everything work find but when i run with github action i got error "Call to undefined method Tests\ValidationRuleTest::getAnnotations()". Not sure this error from package or wrong setup github action

### Steps To Reproduce:
[Here is github action error](https://github.com/vanthao03596/laravel-password-history/runs/2226250187?check_suite_focus=true)

**Comment by crynobone** [comment]
Use minimum version 6.15 for parallel testing.
