### ISSUE TITLE
Dropped PHP7 support for version >= 6.10

### ISSUE THREAD

**Issue by bastian-schur** [orchestral/testbench#305]
- Testbench Version: >= 6.10.*
- Laravel Version: 8.38.0
- PHP Version: 7.4.3
### Description:
I just want to update my dependencies and run into the following error: 
`During class fetch: Uncaught ParseError: syntax error, unexpected '|', expecting variable (T_VARIABLE) in /home/schur/development/viantis/new-api/vendor/spatie/macroable/src/Macroable.php:14`

Orchestra and also spatie/laravel-ray are allowed to use php 7.4. But  an sub package of spatie dropped the php7 support a month ago: #https://github.com/spatie/macroable/commit/b074d687489d2d65352eb0ed3967898948cc3b1b#diff-7b0bb3d81366160b953b3492f77e1b2ef249e0683b85a5eff1d9f26e18b57bb6

**Comment by crynobone** [comment]
`spatie/macroable` 1 still support PHP 7.2+
