### ISSUE TITLE
Question about another issue

### ISSUE THREAD

**Issue by Stevemoretz** [orchestral/testbench#323]
Hi this is not an issue, just curious about : https://github.com/orchestral/testbench/issues/322
What exactly happened, why is that closed? I was still waiting for a response or something.

**Comment by crynobone** [comment]
See https://github.com/orchestral/testbench/issues/322#issuecomment-967232007 

I not going to repeat my answer.

**Comment by Stevemoretz** [comment]
Well you did, and you were wrong so I explained in great details why you were wrong and what you should do to fix it, if you don't care about your library's issues why don't you remove the issues section for good? And not waste other people's time finding exactly what is wrong with your library in great details and finding out you not giving a ****.

**Comment by crynobone** [comment]
> and you were wrong so I explained in great details why you were wrong and what you should do to fix it,

1. Nope, I do know that it is not Testbench responsibility to ensure every package works with it, as I explained previously. 
2. Have you ever considered that no one else has the same issue you're having right now?
3. The problem is not with Testbench, there's nothing to fix.
4. Your explanation just repeats and ignores what I said, so what's else to explain.

> if you don't care about your library's issues why don't you remove the issues section for good? And not waste other people's time finding exactly what is wrong with your library and present to you in great details just to find out you are not giving a ****.

One piece of advice, don't demand helps on open-sourced projects.

**Comment by Stevemoretz** [comment]
Thank you for the response, you haven't noticed as I mentioned your package used that package take a look at your composer.json, https://github.com/orchestral/testbench/blob/7149330a4483f5be4e5363265207b96ef9e2f913/composer.json#L25
If a dependency of my package is causing issues for my library I'm supposed to something about it, isn't that right?

That's what I've mentioned twice in the other topic, I'm not using laravel Ray, your package is using it, and in the matter of nobody else having this issue doesn't mean the issue doesn't exist I brought you an example and proof, there's always a first one to encounter it an issue. 

All you need to test that example is a fresh laravel installation + your own library, no other libraries involved.

And by the way I'm not asking for help, I can fix my own issues even if it is in somebody else's library I just reported it to you, so you might wanna fix your library. (or request a fix on its dependency)

And at the end, thanks for this great library.

**Comment by Stevemoretz** [comment]
First all of, thank you for writing that test!
(as for clearing the confusion I meant using your library in a package on Laravel, I stated that in the wrong way)
It works now because of your commit : https://github.com/spatie/laravel-ray/pull/224
If you had just wrote about that commit in the other topic instead of closing it and saying nothing, we wouldn't have had have this little misunderstanding.

By the way thank you again, and I'm sorry for any inconvenience I may have caused. Didn't mean to be rude, but you yourself know for sure, sometimes you put your heart into trying to contribute and instead get ignored.
