### ISSUE TITLE
Can't assert on Artisan facade because Console\Kernel is final

### ISSUE THREAD

**Issue by shalvah** [orchestral/testbench#326]
- Testbench Version: 7.x branch
- Laravel Version: 9.x branch
- PHP Version: 8.1.0
- Database Driver & Version: None

### Description:
Hi, I'm trying to prepare my library for Laravel 9, but I keep running into this issue:

```
Mockery\Exception: The class \Orchestra\Testbench\Console\Kernel is marked final and its methods cannot be replaced.
Classes marked final can be passed in to \Mockery::mock() as instantiated objects to create a partial mock,
but only if the mock is not subject to type hinting checks.
```

This happens on both PHP 9.5 and 10, and is caused by this line:

```php
Artisan::shouldReceive('call')->once()->...;
```

I see that the `Kernel` class is now marked final, and I understand the error. But I'm not sure what I can do here, considering that this is the recommended Laravel way to make such an assertion. Is there a different way, or could we possibly revert the `final`-ization?

### Steps To Reproduce:
See above

**Comment by crynobone** [comment]
Override `resolveApplicationConsoleKernel()` as described in the documentation.
