### ISSUE TITLE
[7.x] Call to a member function merge() on array

### ISSUE THREAD

**Issue by andrey-helldar** [orchestral/testbench#327]
- Testbench Version: 7.x-dev
- Laravel Version: v9.0.0-beta.1
- PHP Version: 8.0.14
- Database Driver & Version: MySQL 8.0.27

### Description:

```
Error : Call to a member function merge() on array
 C:\dev\domains\dragon-code\laravel-migration-actions\vendor\orchestra\testbench-core\laravel\config\app.php:193
 C:\dev\domains\dragon-code\laravel-migration-actions\vendor\orchestra\testbench-core\src\Bootstrap\LoadConfiguration.php:40
 C:\dev\domains\dragon-code\laravel-migration-actions\vendor\orchestra\testbench-core\src\Bootstrap\LoadConfiguration.php:24
 C:\dev\domains\dragon-code\laravel-migration-actions\vendor\orchestra\testbench-core\src\Concerns\CreatesApplication.php:266
 C:\dev\domains\dragon-code\laravel-migration-actions\vendor\orchestra\testbench-core\src\Concerns\CreatesApplication.php:228
 C:\dev\domains\dragon-code\laravel-migration-actions\vendor\orchestra\testbench-core\src\TestCase.php:73
 C:\dev\domains\dragon-code\laravel-migration-actions\vendor\orchestra\testbench-core\src\Concerns\Testing.php:81
 C:\dev\domains\dragon-code\laravel-migration-actions\vendor\orchestra\testbench-core\src\TestCase.php:41
 C:\dev\domains\dragon-code\laravel-migration-actions\tests\TestCase.php:28
```

![image](https://user-images.githubusercontent.com/10347617/149910474-e9db2c1f-3bff-4225-b1fc-cd6c6a672144.png)

![image](https://user-images.githubusercontent.com/10347617/149910512-a1061bce-3e76-48a1-a13f-221b618e639a.png)

### Steps To Reproduce:

Just run the tests: https://github.com/TheDragonCode/laravel-migration-actions/tree/laravel-9/tests

![image](https://user-images.githubusercontent.com/10347617/149916253-982efc57-6bd1-423f-9ffc-c6c95f0ed30e.png)

**But** if I remove the attempt to call the union method on the array, then the problem immediately disappears:

![image](https://user-images.githubusercontent.com/10347617/149916473-669cfa38-f6d2-494d-985d-6b96b4694793.png)

That is, the code continues to work "correctly".

**Comment by voidgraphics** [comment]
Same problem here. Here's a failed GitHub Actions run showcasing the error, maybe it can provide additional information if needed: https://github.com/whitecube/laravel-prices/actions/runs/1712128175

Seems related to [this PR](https://github.com/laravel/framework/pull/40453), they mention needing to update Testbench already in there. Looks like it's already on their radar, a fix should probably arrive pretty soon.

**Comment by andrey-helldar** [comment]
Understood. In this case, my PR will be superfluous :)

**Comment by crynobone** [comment]
The issue should be solved now

**Comment by andrey-helldar** [comment]
The new tag has not been published yet: https://packagist.org/packages/laravel/framework#v9.0.0-beta.1

We wait :)

**Comment by crynobone** [comment]
> The new tag has not been published yet: https://packagist.org/packages/laravel/framework#v9.0.0-beta.1

That's no longer relevant.
