### ISSUE TITLE
[7.x] Expecting events changed/deprecated?

### ISSUE THREAD

**Issue by cviebrock** [orchestral/testbench#329]
- Testbench Version: 7.x-dev
- Laravel Version: ^9.0
- PHP Version: 8.1.1
- Database Driver & Version: MySQL 8.0.27

### Description:

I'm upgrading my [cviebrock/eloquent-taggable](cviebrock/eloquent-taggable) package for Laravel 9 support, and running into an error with this code from one of my [test suites](https://github.com/cviebrock/eloquent-taggable/blob/master/tests/EventTests.php#L33
):

```php
    public function testModelTaggedEvent(): void
    {
        $this->expectsEvents(ModelTagged::class);

        $this->testModel->tag('Apple');
    }
```

The error:
```
Error: Call to undefined method Cviebrock\EloquentTaggable\Test\EventTests::expectsEvents()
```

Has the syntax for testing for events changed in the new version?

### Steps To Reproduce:

Check out the last run of GitHub actions here: https://github.com/cviebrock/eloquent-taggable/actions/runs/1743404354

Or, to test locally: 
- check out the package: `git clone https://github.com/cviebrock/eloquent-taggable.git`
- `composer install`
- make sure there is a MySQL server running on localhost (user `root`, db `testing`)
- `composer run tests`

**Comment by crynobone** [comment]
None that I'm aware of.

**Comment by crynobone** [comment]
On further investigation, it was due to the removal of the deprecated `MocksApplicationServices` trait from the default `TestCase`. https://github.com/laravel/framework/pull/36716

You may still use it for now by adding it back to your base TestCase class or movee to the latest facade mocking options.

**Comment by fulopattila122** [comment]
I stumbled upon this as well.
Anyone else looking for an up-to-date way of doing it https://laravel.com/docs/master/mocking#event-fake needs to be used.

Example:

**Old code**:
```php
$this->expectsEvents([PaymentDeclined::class]);
// test code that fires the events
```

**New code**:
```php
Event::fake();
// test code that fires events
Event::assertDispatched(PaymentDeclined::class);
```
