### ISSUE TITLE
After 7.10.2 Illuminate\View\ViewException: File does not exist at path 

### ISSUE THREAD

**Issue by angeljqv** [orchestral/testbench#345]
- Testbench Version: 7.10.2
- Laravel Version: 9.36.2
- PHP Version: 8.1.1
- Database Driver & Version: None

### Description:
After upgrading 7.10.2 pops the exception, with 7.10.1 everything works

### Steps To Reproduce:
https://github.com/spatie/laravel-permission/actions/runs/3276093280/jobs/5391731843

**Comment by angeljqv** [comment]
Seems to be related to `https://github.com/laravel/framework/pull/44487`
Maybe adding `forgetCompiledOrNotExpired()` is needed

**Comment by crynobone** [comment]
7.10.2 has nothing to do with views caching.
