### ISSUE TITLE
Laravel 9 / PHP8 flushCache() undefined on test teardown. 

### ISSUE THREAD

**Issue by Kyon147** [orchestral/testbench#347]
- Testbench Version: 
  - orchestra/testbench (v7.0.2)
  - orchestra/testbench-core (v7.11.2)
- Laravel Version: laravel/framework (v9.0.0)
- PHP Version:  8.0.25
- Database Driver & Version:

### Description:

When running tests in PHP8 and Laravel 9 and the test teardown runs, this error happens.

`Call to undefined method Illuminate\View\Component::flushCache()`

### Steps To Reproduce:
1. Run any test.

**Comment by crynobone** [comment]
It seems you have used incompatible dependencies. Please remove `~` constraint from all CI build. https://twitter.com/driesvints/status/1575396427240509440
