### ISSUE TITLE
SQLSTATE[HY000] [2002] Connection refused

### ISSUE THREAD

**Issue by KarinaRashchynskaya** [orchestral/testbench#349]
-  Testbench Version: 7.12.1

**Description** 

Hi,

After I got the updated testbench version, I can not execute some commands successfully. 
For example, the following command throwing the error SQLSTATE[HY000] [2002] Connection refused.

> vendor/bin/testbench migrate --database=sqlite  --path=vendor/orchestra/testbench-core/laravel/migrations --path=../../../../database/migrations

I have set my own testbench.yaml file with the following database configuration but it seems that `testbench-core` ignores them.

>    DB_CONNECTION="sqlite"
      DB_DATABASE="database.sqlite"

     
     
 How can I set the DB_CONNECTION parameter in `testbench-core` ? Is it possible to change the default configuration settings of testbench using any commands option?

**Comment by crynobone** [comment]
> I have set my own testbench.yaml file with the following database configuration but it seems that testbench-core ignores them.

both of the configuration are the default.

**Comment by KarinaRashchynskaya** [comment]
Of what I see, the default db connection is mysql

![Screenshot from 2022-12-06 15-49-30](https://user-images.githubusercontent.com/115797465/205929799-421f5208-956d-4651-b57e-fd8d0b50e419.png)

**Comment by KarinaRashchynskaya** [comment]
> > I have set my own testbench.yaml file with the following database configuration but it seems that testbench-core ignores them.
> 
> both of the configuration are the default.

From what I see, the default db connection is mysql

![Screenshot from 2022-12-06 15-49-30](https://user-images.githubusercontent.com/115797465/205930533-164b3688-c6b7-4c2f-b264-648d637edc59.png)

**Comment by crynobone** [comment]
When you run `vendor/bin/testbench` it would generate `.env` from `.env.example`, which is default to `sqlite`. You can confirm this by running `php vendor/bin/testbench about`

**Comment by crynobone** [comment]
https://github.com/orchestral/testbench-core/blob/277858ba55f1f316bc1720d9d460cc1be3c0c51d/src/Console/Commander.php#L115-L123

**Comment by KarinaRashchynskaya** [comment]
> When you run `vendor/bin/testbench` it would generate `.env` from `.env.example`, which is default to `sqlite`. You can confirm this by running `php vendor/bin/testbench about`

Please find below the output of the mentioned command. I am still getting mysql

![Screenshot from 2022-12-06 16-03-33](https://user-images.githubusercontent.com/115797465/205932840-9d58bb2c-7a3e-4d70-9d90-eefe3f882e7e.png)

**Comment by KarinaRashchynskaya** [comment]
> ```shell
> package:create-sqlite-db
> ```

Is there any other way to change the default db connection into  `testbench-core` ?

**Comment by KarinaRashchynskaya** [comment]
> ![image](https://user-images.githubusercontent.com/172966/205934443-aea00f1d-8294-4fde-9d8f-5dca8d07d536.png)
> 
> Unable to replicate your issue.

Is there any other way to change the default db connection into testbench-core ?

**Comment by KarinaRashchynskaya** [comment]
> > From what I see when I run vendor/bin/testbench is that it would generate .env from .env file which is located in my project root directory
> 
> Then you don't you just edit that file directly?

I am trying to figure out in a different way and avoid dependencies between my .env file and testbench-core.
Since the package also copies the testbench.yaml file, why does it not take it into consideration?

**Comment by KarinaRashchynskaya** [comment]
> ```shell
>  package:create-sqlite-db
> ```
Is there any way to skip /bypass the .env file through the commands options and take into consideration the testbench.yaml settings?

**Comment by KarinaRashchynskaya** [comment]
> Nope, `.env` has higher priority than `testbench.yaml`

Is there any way to skip /bypass the .env file through the commands options and take into consideration the testbench.yaml settings?

**Comment by crynobone** [comment]
No plan to modify the behavior. Use what's available at the moment.
