### ISSUE TITLE
phpunit.xml file does not exist in testbench-core

### ISSUE THREAD

**Issue by karinarastsinskagia** [orchestral/testbench#362]
- Testbench Version: orchestra/testbench v8.5.1,  orchestra/testbench-core v8.5.1 , orchestra/testbench-dusk v8.6.0
- Laravel Version: v10.9.0
- PHP Version: 8.1

### Description:

Hello,

I am using the `package:test` command in order to execute my phpunit tests in parallel mode and everything worked well until the latest updates. Particularly, after I updated the latest versions of `orchestral/testbench` and `nunomaduro/collision` packages, I have started to receive the following error message :

![Screenshot from 2023-05-05 14-07-48](https://user-images.githubusercontent.com/32904307/236444470-0379ffbf-a8e7-4ecd-a60e-2fad5ec09561.png)

After some research, I noticed that the recent `nunomaduro/collision` changes, included some extra functionality in terms of caching which  requires loading the proper `phpunit.xml` file 
(https://github.com/nunomaduro/collision/commit/6fc0c4786dd9db20dd7ea355f34243448e6f1707). 
However, in this step, from the`orchestral/testbench` end, the `phpunit.xml` file does not exist and the command fails.

### Steps To Reproduce:
So, my question is, if you are already working on this issue or if it's possible to deal with it by including a default `phpunit.xml` file or copy the one, before the parent class executes.

For example, one solution might be the following :

![Screenshot from 2023-05-05 14-20-38](https://user-images.githubusercontent.com/32904307/236444671-7943aca2-da14-4ab7-8e33-779465da8496.png)

Thank you

**Comment by crynobone** [comment]
This should be fixed with the upcoming release of `collision`.
