### ISSUE TITLE
Undefined version constraint

### ISSUE THREAD

**Issue by jasonmccreary** [orchestral/testbench#368]
- Testbench Version: 8.5.7
- Laravel Version: 10.13.2
- PHP Version: 8.2.4
- Database Driver & Version: N/A

### Description:
While not a "bug", the recent constraints for `laravel/framework` list `<10.15.0`. However, this is not a real Laravel version (yet). As such, it breaks parsing and compatibility tests. Simply `>=10.13.5` or `^10.13.5` is enough to represent the `10.13.5` requirement as well as future versions. It help me, as well as those that use Shift, if you could drop the upper bound, invalid constraint.

**Comment by crynobone** [comment]
> Simply >=10.13.5 or ^10.13.5 is enough to represent the 10.13.5 requirement as well as future versions.

This would break when Laravel Framework or Testbench Core API has "minor" breaking changes when using `--prefer-lowest` etc:

* #367
* #345
* orchestral/testbench-core#81
* statamic/cms#6801

Latest version changed from `<10.15.0` to `<10.14.0`.

**Comment by jasonmccreary** [comment]
`10.14.0` is non-existent as well. I think the simpler way to write this would be `~10.13.5`. But, your call. Thanks anyway. I'll just have Shift set projects to `^8.0` instead of tracking the latest versions.

**Comment by crynobone** [comment]
Yes that should work fine. The idea is that if they use `stable` minimum stability they should get stable releases from `develop` branch, or use `8.x` branch if they use `dev` minimum stability.
