### ISSUE TITLE
https://packages.tools/testbench

### ISSUE THREAD

**Issue by hooman-mirghasemi** [orchestral/testbench#370]
documention url not working:
https://packages.tools/testbench

**Comment by crynobone** [comment]
Unable to replicate

**Comment by hooman-mirghasemi** [comment]
wow!! i am saying your documention url is not reponding..
and maybe its down.
why u close issue with "Unable to replicate" !!!

**Comment by crynobone** [comment]
![Screenshot_20230724_164329_Chrome.png](https://github.com/orchestral/testbench/assets/172966/82a04752-b340-482d-a218-d6280b690bdc)

Because it not down. If something is wrong with Cloudflare or Netlify it's also out of my control.
