### ISSUE TITLE
Faker not setup after update

### ISSUE THREAD

**Issue by royduin** [orchestral/testbench#374]
- Testbench Version: 7.26.2
- Laravel Version: 9.52.15
- PHP Version: 8.1
- Database Driver & Version:

This one is working: https://github.com/rapidez/core/actions/runs/5791528367/job/15696480561 but since the Testbench update from 7.25 to 7.26 it's not working anymore: https://github.com/rapidez/core/actions/runs/5803677584/job/15732130410. Also with 7.26.2 it's not working: https://github.com/rapidez/core/actions/runs/5827705169/job/15811617310

Somehow Faker setup isn't getting called anymore: https://github.com/laravel/framework/blob/9.x/src/Illuminate/Foundation/Testing/TestCase.php#L151 which we use in our test: https://github.com/rapidez/core/blob/master/tests/Browser/NewsletterTest.php#L11 and now fails as it's `null`: https://github.com/rapidez/core/blob/master/tests/Browser/NewsletterTest.php#L19

Ideas?

**Comment by crynobone** [comment]
Please check with the latest Testbench Core 7.26 release.

**Comment by royduin** [comment]
Same issue: https://github.com/rapidez/core/actions/runs/5827705169/job/15813821107

- `orchestra/testbench` (v7.26.2)
- `orchestra/testbench-core` (v7.26.3)
- `orchestra/testbench-dusk` (v7.17.0)

**Comment by crynobone** [comment]
Unable to replicate the issue: https://github.com/orchestral/testbench-dusk/commit/fef8914c66a85544ca4ec54d329a6dc562508836

**Comment by royduin** [comment]
Thank you for your time! I'll look into this further soon and coming back to you.

**Comment by crynobone** [comment]
It seems that you locked `laravel/dusk` to `^6.22` while latest `orchestra/testbench-dusk` requires `^7.7` which causes incompatible. You need to upgrade `laravel/dusk` to fix the issue

**Comment by royduin** [comment]
Thank you! It's working 🚀
