### ISSUE TITLE
phpunit.xml Env Variables Not Loaded in `testbench package:test` Command

### ISSUE THREAD

**Issue by SupianIDz** [orchestral/testbench#380]
- Testbench Version: 8.11
- PHP Version: 8.1

### Description:
when running `./vendor/bin/phpunit` directly all tests work correctly, but when testing with the command `./vendor/bin/testbench package:test` it shows `No application encryption key has been specified.`

This occurs when the `encrypt` function is used

<img width="679" alt="Screenshot 2023-09-22 at 04 04 13" src="https://github.com/orchestral/testbench/assets/37969970/3b40d81e-8cdd-44ca-9c84-fd1c3b633381">

I tried `dd($_ENV)` in testing, it seems the `./vendor/bin/testbench package:test` command doesn't load the env defined in `phpunit.xml`

1. ./vendor/bin/phpunit
<img width="505" alt="Screenshot 2023-09-22 at 04 05 43" src="https://github.com/orchestral/testbench/assets/37969970/f0a91a69-5db6-47f5-a5b7-7286c07758e5">

2. ./vendor/bin/testbench package:test
<img width="632" alt="Screenshot 2023-09-22 at 04 05 56" src="https://github.com/orchestral/testbench/assets/37969970/4ddb05ab-612f-4918-ad31-1d6bbd8d39c3">

### Steps To Reproduce:
1. git clone https://github.com/SupianIDz/testbench-test
3. composer install
4. ./vendor/bin/phpunit
5. ./vendor/bin/testbench package:test

**Comment by crynobone** [comment]
https://github.com/orchestral/testbench-core/commit/5cc96a43478e0178b4adc4ed90314dd2c54eb9a0

Unable to reproduce, our GitHub Action also being tested using `package:test` and `package:test --parallel` without issue.

**Comment by SupianIDz** [comment]
Hi @crynobone

could you take a look reproduction of the repository? I tried in 3 different environments + github action but got the same error.

github action workflow : https://github.com/SupianIDz/testbench-test/blob/main/.github/workflows/testbench.yml
github action result : https://github.com/SupianIDz/testbench-test/actions/runs/6271550982/job/17031352888

<img width="818" alt="Screenshot 2023-09-22 at 15 47 40" src="https://github.com/orchestral/testbench/assets/37969970/ad4f6538-dcf3-43d8-b83e-15f4ba8e40f6">


1. result from linux server
<img width="628" alt="Screenshot 2023-09-22 at 15 31 50" src="https://github.com/orchestral/testbench/assets/37969970/7b1cc0f3-b2dd-48c3-8511-ad5c5c70dc8d">

---
2. result from ubuntu desktop
![Screenshot from 2023-09-22 15-28-32](https://github.com/orchestral/testbench/assets/37969970/c23d7544-127e-494d-8e9d-2ed4b1a66b38)

**Comment by crynobone** [comment]
> could you take a look reproduction of the repository? I tried in 3 different environments + github action but got the same error.

You can try submit a failing test to https://github.com/orchestral/testbench-core

**Comment by SupianIDz** [comment]
I think this is enough: https://github.com/orchestral/testbench-core/commit/b9fc730788b42b37812454e915fd515ca9f7b43f

but I am very confused about this problem, it can be seen from the reproduction of the repo, everything is very minimal but the error still occurs.

https://github.com/SupianIDz/testbench-test/blob/main/tests/FooBarTest.php#L14
