### ISSUE TITLE
What is workbench?

### ISSUE THREAD

**Issue by SlimDeluxe** [orchestral/testbench#389]
Hi, thank you for your work on this package.
I just updated testbench in a package I am developing and noticed you now have a "workbench" thing. It is not clear to me what it's purpose is and how to use it. The docs only have the "introduction" part.
Could you please provide some explanation with an example?

Edit:
I did try to run the `workbench:install` command and it created some script entries in `composer.json` and a workbench dir in project root with what looks like an app skeleton. Still no clue what should I do with it :smile:

**Comment by crynobone** [comment]
See https://youtu.be/fm628IJ1OKw?si=_p7qHyjbjMsnYspS

**Comment by SlimDeluxe** [comment]
Okay, saw it.
If I understood it correctly, you can use the workbench dir to set up an app to test your package as it would be used in an app, instead of just running the tests with a skeleton?
Currently, I have a sample app where I added the package from a local dir (which composer installs as a symlink) to allow me to test it while I develop. Workbench would now replace this if I am not mistaken.

**Comment by crynobone** [comment]
yeah, that's correct

**Comment by SlimDeluxe** [comment]
Great, thank you for the quick support :)
All the best in the future

**Comment by josegus** [comment]
Workbench is great but there're not enough tutorials nor documentation about how to use it. 

I know it comes with a default login screen, for example, but.. is it possible to export that `login.blade.php` file from the vendor folder to the root path `/workbench/resources/views`?

**Comment by crynobone** [comment]
That's not the intention of this package. Workbench auth feature is only there to help speed up previewing your package. If you're doing an auth package you need to come out with your own views etc
