### ISSUE TITLE
Livewire failing on testbench 9

### ISSUE THREAD

**Issue by joshhanley** [orchestral/testbench#391]
- Testbench Version: 9.x-dev
- Laravel Version: dev-master (11.x)
- PHP Version: 8.2
- Database Driver & Version:

### Description:
Running Livewire's test suite using L11/Orchestra9/TestbenchDusk9 is throwing the below error (wasn't sure if this was better here or in testbench-dusk).

If I downgrade to L10/Testbench8/TestbenchDusk8, everything runs happily.

Haven't had a chance to dig into it yet, but was wondering if you had any insights as to what might be happening?

![image](https://github.com/orchestral/testbench/assets/882837/307050f9-2dce-4f52-9892-c75e10415274)

### Steps To Reproduce:

Clone a new copy of Livewire repo, update chrome driver and run php unit:

```
git clone git@github.com:livewire/livewire.git livewire-L11-test

cd livewire-L11-test

composer install

./vendor/bin/dusk-updater update

./vendor/bin/phpunit
```

Should result in a lot of the dusk tests throwing the above error.

Thanks in advance!

**Comment by crynobone** [comment]
Laravel 11 will change the default session driver from `file` to `database`. You can either add the environment variable to use `file` or update database migrations to include `sessions` table.

**Comment by joshhanley** [comment]
@crynobone ah ok thanks for the heads up. I will give it a go and report back.

**Comment by joshhanley** [comment]
@crynobone adding `<env name="SESSION_DRIVER" value="file"/>` to `phpunit.xml.dist` fixed the issue. Thanks for the quick response!
