### ISSUE TITLE
Change default middleware in bootstrap/app.php in Laravel 11

### ISSUE THREAD

**Issue by ivanvermeyen** [orchestral/testbench#396]
Hi,

My package needs to run a middleware in the `web` group in a certain order/priority.

Before Laravel 11, I could stub the `Kernel.php` file in my base TestCase:

```php
protected function resolveApplicationHttpKernel($app): void
{
    $app->singleton(
        'Illuminate\Contracts\Http\Kernel',
        'My\Tests\Stubs\Kernel'
    );
}
```

But as of Laravel 11, this is now handled in `bootstrap/app.php`.
Is there a way to stub this file too?

**Comment by bayareawebpro** [comment]
Use an `afterApplicationCreated` callback by overriding the `setUp` method:

```php
protected function setUp(): void
{
    parent::setUp();

    $this->afterApplicationCreated(function (){
        $this->app->singleton(
            'Illuminate\Contracts\Http\Kernel',
            'My\Tests\Stubs\Kernel'
        );
    });
}
```
