### ISSUE TITLE
Package migrations don't get executed anymore with v8.22 (core v8.23)

### ISSUE THREAD

**Issue by finpension-aless** [orchestral/testbench#399]
- Testbench Version:  8.22.0
- Laravel Version: 10.48.2
- PHP Version: 8.3
- Database Driver & Version: postgresql v16

### Description:
After updating the orchestra libraries to the new version released on March 12th/13th, our tests fail and when I debug the problem I notice that our Laravel migrations don't get executed anymore. We still use the trait "RefreshDatabase" and in our setUp method we still call "$this->loadMigrationsFrom(__DIR__ . '/../../database/migrations');", nothing changed there since the update.

### Steps To Reproduce:
Execute a test that uses the database and has some Laravel migrations.

**Comment by finpension-aless** [comment]
The issue seems to be with orchestra/testbench-core v8.23 
When I downgrade it back to 8.22.1 the tests go through again.

**Comment by crynobone** [comment]
Don't use `RefreshDatabase` with `loadMigrationsFrom` outside of `defineDatabaseMigrations` method: https://github.com/orchestral/testbench-core/discussions/194 

We have never suggested using `loadMigrationsFrom` within `setUp()` method.
