### ISSUE TITLE
Package migrations are not executed with v7.41.0 (core v7.42.0)

### ISSUE THREAD

**Issue by amir215909** [orchestral/testbench#400]
- Testbench Version: 7.41.0
- Laravel Version: 9.52.16
- PHP Version: 8.2.10
- Database Driver & Version: Sqlite

### Description:

Migrations loaded with `loadMigrationsFrom` method of `InteractsWithMigrations` don't run.

### Steps To Reproduce:
`main` branch of the [repository](https://github.com/amir215909/testbench-7.41.0-migration-bug-report) which is a bug reproduction demo can be used to reproduce the issue (detailed instructions are in [README.MD](https://github.com/amir215909/testbench-7.41.0-migration-bug-report/blob/main/README.md))

**Comment by crynobone** [comment]
Don't use `RefreshDatabase` with `loadMigrationsFrom` outside of `defineDatabaseMigrations` method: https://github.com/orchestral/testbench-core/discussions/194 

We have never suggested using `loadMigrationsFrom` within `setUp()` method.
