### ISSUE TITLE
PHPUnit 11.1 is not allowed

### ISSUE THREAD

**Issue by szepeviktor** [orchestral/testbench#404]
- Testbench Version: v9

### Description:

https://github.com/orchestral/testbench-core/blob/eabe0c72e787aae29df96bd4e33c61fffa6d5edc/composer.json#L58

Is there an incompatibility with v11.1?

**Comment by crynobone** [comment]
Fixed via 9.0.15

**Comment by szepeviktor** [comment]
Thank you.
