### ISSUE TITLE
Workbench install stuck in installing

### ISSUE THREAD

**Issue by mrkdyrit** [orchestral/testbench#422]
- Testbench Version: 9.6
- Laravel Version: 11.0
- PHP Version: 8.2

### Description:
Running `php vendor/bin/testbench workbench:install` seems to be stuck and is not completing, it is only running until it created the **testbench.yaml** and is seemed to be stuck

**Comment by crynobone** [comment]
Sorry, but I'm not able to reproduce this error. `testbench.yaml` is always optional. Need additional information in order to debug and fix this.

**Comment by mrkdyrit** [comment]
I am also unsure on what is going on but it just stops, is there any log file that I can view to see additional information?

**Comment by mrkdyrit** [comment]
It seems like the installation continues as normal but it just not automatically exist so it seems like it is stuck.
