### ISSUE TITLE
Show " INFO  Seeding database." in the console then migrate:fresh command is run.

### ISSUE THREAD

**Issue by skulich** [orchestral/testbench#426]
Hello,

I find out that running `vendor/bin/testbench migrate:fresh` will run all seeders listed in the `seeders:` section of tesbench.yaml file but no info about it is shown.

It would be nice to see that DB is seeded as if you get used to the `artisan migrate:fresh` command you expect that info line (if the `--seed` option is provided).

Thank you

**Comment by crynobone** [comment]
Seeding was done via Laravel event dispatcher, there no way to hook into the console output
