### ISSUE TITLE
Cache and session config files should be array

### ISSUE THREAD

**Issue by willrowe** [orchestral/testbench#58]
The cache and session config files should be like those in the testing environment folder in Laravel. The drivers should be set to `array` and not `file`. There can be collision between tests when the cache and sessions would be expected to be cleared since the application is refreshed, but since they're stored in files they are persisted between all tests in a suite and even between instances of running test suites. I can make PR if that would be helpful, it's a quick edit.

**Comment by willrowe** [comment]
It looks like the the default driver for the cache is back to `file` instead of `array` in v3.0, was this done on purpose?

**Comment by GrahamCampbell** [comment]
Looks like a bug to me.

**Comment by crynobone** [comment]
Could also add environment variable in your phpunit.xml while a fix could
be merged.
