### ISSUE TITLE
[3.0] Timezone ID '' is invalid

### ISSUE THREAD

**Issue by micheleangioni** [orchestral/testbench#77]
Hi,
I'm currently having issues by using 3.0 Testbench version on the Laravel 5 conversion of a package of mine.

The package is [Message Board](https://github.com/micheleangioni/message-board) and Travis gets [my same error](https://travis-ci.org/micheleangioni/message-board/jobs/49501600).

The composer.json is quite simple

    "require": {
        "php": ">=5.4.0",
        "chromabits/purifier": "dev-master",
        "laravel/framework": "~5.0",
        "michele-angioni/support": "~2.0"
    },
    "require-dev": {
        "mockery/mockery": "dev-master",
        "orchestra/testbench": "3.0.*",
        "phpunit/phpunit": "~4.1",
        "sami/sami": "dev-master"
    },

This is [one of the failing tests](https://github.com/micheleangioni/message-board/blob/master/tests/MbAbstractGatewayTest.php) : as you can see, the test boilerplate is most copied from your example.
However, it already fails at the parent::setUp() call, in the setUp() method.

Tracking down the issue it happens in the $this->resolveApplicationConfiguration($app) call in ApplicationTrait and the failing line is n. 199 `$app->make('Illuminate\Foundation\Bootstrap\LoadConfiguration')->bootstrap($app);` during the Application bootstrap.

That line calls in the LoadConfiguration class

    date_default_timezone_set($config['app.timezone']);

and it obviously fails because app.timezone is still not set.
Is there something I miss? Is there an error somewhere?

Thanks for your help

**Comment by crynobone** [comment]
Should be fixed, thank you for the report.

**Comment by micheleangioni** [comment]
Glad it helped!

**Comment by micheleangioni** [comment]
@crynobone I tried the updated version [the tests still error](https://travis-ci.org/micheleangioni/message-board/jobs/49789606) :(

Commit 0a6a9e7ecda38cfbd7fd47552c8b65969f553db8 modifies src/Traits/ApplicationTrait.php after the erroring line (line 199 with $app->make('Illuminate\Foundation\Bootstrap\LoadConfiguration')->bootstrap($app);)

I think the problem is that, even if date_default_timezone_set is already set, $config['app.timezone'] is not when it is called in Illuminate\Foundation\Bootstrap\LoadConfiguration.

Any ideas?

**Comment by crynobone** [comment]
The purpose of LoadConfiguration is loading the config, which would get the default value from fixture directory.

**Comment by crynobone** [comment]
Why the issue occur:

1. The TestCase reset the base path to your package src, instead of testbench fixture dir.
2. The would cause fixture `config/app.php` to not properly loaded.
3. There also limitation on how `php artisan migrate` works.

**Comment by GrahamCampbell** [comment]
Surely this issue only occurs due to incorrect usage so we're fixing a non-issue?

**Comment by crynobone** [comment]
> Surely this issue only occurs due to incorrect usage?

Not really, the suggested method is to point the base directory to your package dir. But by doing so the fixture is no longer referenced. 

At the moment I feel that allowing to specific a realpath to `php artisan migrate` is the most suitable option <https://github.com/orchestral/testbench/commit/ab0fde7610985a689c19cf40c5daefdf633186e5>

**Comment by micheleangioni** [comment]
@crynobone the last commit fixed the problem :+1:  I agree the only option was to use a custom LoadConfiguration.  

However, I had also to add a /storage/framework directory under my src directory, where a services.json file is created. Maybe that should be added in the docs.

@GrahamCampbell well, the test was erroring at the very beginning, at the parent::setUp(); call in the setUp() method. I just followed install instructions and used the example test. Furthermore, I had no problems with the Laravel 4 version.  
I would thank you if you could tell me where I am/was wrong in the testbench usage.

**Comment by cviebrock** [comment]
> However, I had also to add a /storage/framework directory under my src directory, where a services.json file is created. Maybe that should be added in the docs.

I'm running into the same problem with my test setup, in that my tests fail with:

```
ErrorException: file_put_contents(/Users/admin/Documents/github/cviebrock/eloquent-taggable/src/storage/framework/services.json): failed to open stream: No such file or directory
```

This is with running `3.0.x@dev`, BTW.  Any ideas?

**Comment by crynobone** [comment]
> I'm running into the same problem with my test setup, in that my tests fail with

I think it should be best not to change the base path unless you have a specific reason for it. Previously we do this to make it easier to run migration, but now you can just simply use `$artisan->call('migrate', ['--realpath' => '/path/to/your/package/migrations']);`

**Comment by cviebrock** [comment]
Yeah, I had a `getBasePath` method in my test.  Removed it, and it all works.
