### ISSUE TITLE
3.0.1 -> 3.0.2 Brakes Everything

### ISSUE THREAD

**Issue by GrahamCampbell** [orchestral/testbench#78]
Looks like we're not booting correctly: https://travis-ci.org/BootstrapCMS/CMS/jobs/50404411.

**Comment by crynobone** [comment]
I tried downloading the repo, but I can't seem to find `app:install` console class.

**Comment by crynobone** [comment]
Under `GrahamCampbell\Testbench\AbstractAppTestCase` add the following:

```php
    /**
     * Resolve application implementation.
     *
     * @return \Illuminate\Foundation\Application
     */
    protected function resolveApplication()
    {
        return new \Illuminate\Foundation\Application($this->getBasePath());
    }
```

Only packages testcase need to use `Orchestra\Testbench\Bootstrap\LoadConfiguration`

**Comment by GrahamCampbell** [comment]
Oh right, thank you. :)
