### ISSUE TITLE
Unable to fully swap base path on Laravel 5

### ISSUE THREAD

**Issue by nWidart** [orchestral/testbench#79]
Hello,
I'm trying to run my tests, that are creating a folder.
I use the following to define the wanted path:

``` php
$this->testModulePath = __DIR__ . "/../Modules/{$this->testModuleName}";
```
When I dump this using `dd` I get : `"/Users/nicolaswidart/Sites/Asguard/IndividualModules/Workshop/Tests/../Modules/TestingTestModule"`, which is correct.

Though when calling an artisan command that is suppose to generate it, it makes it under `vendor/orchestra/testbench/fixtures/Modules/TestingTestModule`

This is my `getEnvironmentSetUp` method:

``` php
protected function getEnvironmentSetUp($app)
{
    $app['path.base'] = __DIR__ . '/..';
}
```
Did I miss something ?

Thanks!

**Comment by crynobone** [comment]
Yes, because the way Laravel 5 resolve path no longer work the same as Laravel 4. Change `$app['path.base']` might or might not give any affect depending on how the command fetch the path. 

Have you look at <https://github.com/laravel/framework/blob/5.0/src/Illuminate/Foundation/Application.php#L228>

**Comment by nWidart** [comment]
Oh okay.
Used `$app->setBasePath(__DIR__ . '/..');` now to setup the base path, though it still generates in the wrong folder.

Thank you,

**Comment by crynobone** [comment]
Still getting `vendor/orchestra/testbench/fixtures/Modules/TestingTestModule`?

**Comment by nWidart** [comment]
Yes.

When dumping `dd(__DIR__ . '/..', $app->basePath());`, here: 

``` php
protected function getEnvironmentSetUp($app)
{
    $app->setBasePath(__DIR__ . '/..');
    dd(__DIR__ . '/..', $app->basePath());
}
```
I do get
```
"/Users/nicolaswidart/Sites/Asguard/IndividualModules/Workshop/Tests/.."
"/Users/nicolaswidart/Sites/Asguard/IndividualModules/Workshop/Tests/.."
```

But for some reason it isn't using that in the test.
In test now:

``` php
$this->testModulePath = base_path("Modules/{$this->testModuleName}");
```

**Comment by crynobone** [comment]
The only location where we mess with base path is at <https://github.com/orchestral/testbench/blob/3.0/src/Traits/ApplicationTrait.php>, you can also try swapping `getBasePath()` but that could also have some side-affect.

Otherwise might be also consider:

```php
$this->testModulePath = $this->app->basePath()."/Modules/{$this->testModuleName}";
```

**Comment by nWidart** [comment]
```
$this->test

ModulePath = $this->app->basePath()."/Modules/{$this->testModuleName}";
```
Still generates in the fixtures folder.

How would you swap that `getBasePath()` method ? 
Wouldn't that make the `fixtures/config` folder useless ?

Thanks!

**Comment by crynobone** [comment]
> Wouldn't that make the `fixtures/config` folder useless ?

https://github.com/orchestral/testbench/blob/3.0/src/Bootstrap/LoadConfiguration.php#L52 I enforced the the bootstrap to explicitly look inside `fixture/config`.

> How would you swap that `getBasePath()` method ? 

Basically almost the same as you would right now, the problem with this is that every path in Laravel 5 is relative to the `path.base`, so once you change it, storage path would also changed (unlike Laravel 5 where every path is defined separately).

Another problem is we have `$app['path.base']` and `$app->basePath()`, when you change `$app['path.base']` it doesn't affect `$app->basePath()`.

**Comment by nWidart** [comment]
Hm okay. Still don't really get how to 'force' the base path though.

Thanks,

**Comment by crynobone** [comment]
> About the storage path, I'm thinking it's not too bad

It going to create issue where it would try to generate `services.json` inside none existing storage path (when you change base path location). Wouldn't it not be possible to recreate a full `fixtures` (that mimic the application skeleton), and build your module based on that directory?

**Comment by nWidart** [comment]
Hm recreate a `fixtures` folder you mean ? Like inside `Tests/Fixtures` ?  That would be possible, it I can change the base path..
Would I did for know, as a temporary solution, is moving the generated code, from you `fixtures` folder, to the desired location in the `Tests` directory. This isn't very clean, also adds unnecessary IO operations, but it works for now.

**Comment by crynobone** [comment]
> That would be possible, if I can change the base path..

```php
class TestCase extends Orchestra\Testbench\TestCase {
   protected function getBasePath()
   {
      return realpath(__DIR__.'/fixtures');
   }
}
```

**Comment by Jeroen-G** [comment]
This did the trick for me:
```php
$app['path.base'] = realpath(__DIR__ . '/../src');
```
The `/.../` that the dd dump showed is actually not correct, it should show the full path.

**Comment by crynobone** [comment]
I'm closing this for now, if anyone has any suggestion on how to handle requirement around Laravel limitation feel free to share it here, PR are welcomed too :)

**Comment by nWidart** [comment]
I've set the basepath to :

``` php
$app['path.base'] = realpath(__DIR__ . '/../Modules');`
```
But still getting the wrong path in the laravel test:

```
var_dump($this->app->basePath()); exit;
# output: [...]/vendor/orchestra/testbench/src/Traits/../../fixture
```

**Comment by crynobone** [comment]
As I said earlier, just changing `$app['path.base']` doesn't always change everything. `$this->app->basePath()` doesn't fetch the value from `$this->app['path.base']`.

**Comment by nWidart** [comment]
I'm very sorry but, I'm still having issues with this. :disappointed: 

When I set the base path with :

``` php
protected function getBasePath()
    {
        return realpath(__DIR__.'/fixtures');
    }
```
I get the following, while trying to dump `dd(base_path());` in my test:

```
Class path.storage does not exist
 /Users/nicolaswidart/Sites/Asguard/Modules-Development/Modules/Workshop/vendor/laravel/framework/src/Illuminate/Container/Container.php:736
 /Users/nicolaswidart/Sites/Asguard/Modules-Development/Modules/Workshop/vendor/laravel/framework/src/Illuminate/Container/Container.php:626
 /Users/nicolaswidart/Sites/Asguard/Modules-Development/Modules/Workshop/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:643
 /Users/nicolaswidart/Sites/Asguard/Modules-Development/Modules/Workshop/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:53
 /Users/nicolaswidart/Sites/Asguard/Modules-Development/Modules/Workshop/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:528
 /Users/nicolaswidart/Sites/Asguard/Modules-Development/Modules/Workshop/vendor/orchestra/testbench/fixture/config/cache.php:47
 /Users/nicolaswidart/Sites/Asguard/Modules-Development/Modules/Workshop/vendor/orchestra/testbench/src/Bootstrap/LoadConfiguration.php:39
 /Users/nicolaswidart/Sites/Asguard/Modules-Development/Modules/Workshop/vendor/orchestra/testbench/src/Bootstrap/LoadConfiguration.php:23
 /Users/nicolaswidart/Sites/Asguard/Modules-Development/Modules/Workshop/vendor/orchestra/testbench/src/Traits/ApplicationTrait.php:190
 /Users/nicolaswidart/Sites/Asguard/Modules-Development/Modules/Workshop/vendor/orchestra/testbench/src/Traits/ApplicationTrait.php:150
 /Users/nicolaswidart/Sites/Asguard/Modules-Development/Modules/Workshop/vendor/laravel/framework/src/Illuminate/Foundation/Testing/ApplicationTrait.php:34
 /Users/nicolaswidart/Sites/Asguard/Modules-Development/Modules/Workshop/vendor/orchestra/testbench/src/TestCase.php:42
 /Users/nicolaswidart/Sites/Asguard/Modules-Development/Modules/Workshop/Tests/BaseTestCase.php:16
 /Users/nicolaswidart/Sites/Asguard/Modules-Development/Modules/Workshop/Tests/ThemeScaffoldTest.php:30
```

When I change it to:

``` php
protected function getBasePath()
    {
        return realpath(__DIR__ . '/../' . $this->path);
    }
```

I get:

```
file_put_contents(/Users/nicolaswidart/Sites/Asguard/Modules-Development/Modules/Workshop/Themes/bootstrap/cache/services.json): failed to open stream: No such file or directory
 /Users/nicolaswidart/Sites/Asguard/Modules-Development/Modules/Workshop/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:81
 /Users/nicolaswidart/Sites/Asguard/Modules-Development/Modules/Workshop/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:188
 /Users/nicolaswidart/Sites/Asguard/Modules-Development/Modules/Workshop/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:135
 /Users/nicolaswidart/Sites/Asguard/Modules-Development/Modules/Workshop/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:60
 /Users/nicolaswidart/Sites/Asguard/Modules-Development/Modules/Workshop/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:476
 /Users/nicolaswidart/Sites/Asguard/Modules-Development/Modules/Workshop/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php:17
 /Users/nicolaswidart/Sites/Asguard/Modules-Development/Modules/Workshop/vendor/orchestra/testbench/src/Traits/ApplicationTrait.php:158
 /Users/nicolaswidart/Sites/Asguard/Modules-Development/Modules/Workshop/vendor/laravel/framework/src/Illuminate/Foundation/Testing/ApplicationTrait.php:34
 /Users/nicolaswidart/Sites/Asguard/Modules-Development/Modules/Workshop/vendor/orchestra/testbench/src/TestCase.php:42
 /Users/nicolaswidart/Sites/Asguard/Modules-Development/Modules/Workshop/Tests/BaseTestCase.php:16
 /Users/nicolaswidart/Sites/Asguard/Modules-Development/Modules/Workshop/Tests/ThemeScaffoldTest.php:30
```

At least now the path is correct (`Modules/Workshop/Themes/`)...

I also have `$app['path.base'] = realpath(__DIR__ . '/../' . $this->path);` in the `getEnvironmentSetUp` method.  Where `this->path` is on the 2 test classes, that need different paths.

**Comment by crynobone** [comment]
Mock the whole `fixture` folder to `Modules/Workshop/Themes` if you insist on doing this.

**Comment by nWidart** [comment]
Hm well that's not really an option, since that'll be committed in source control.

**Comment by crynobone** [comment]
> Hm well that's not really an option

There is NO OTHER OPTION, almost everything in Laravel code internally uses `$app['base.path']` to resolve the path, and once you change it, everything else need to follow that path.

**Comment by nWidart** [comment]
Ok ... Even not in the fixtures folder of the Testbench package ? :confused:

**Comment by crynobone** [comment]
> Ok ... Even not in the fixtures folder of the Testbench package ?

If not modifying the base path, you be using the fixtures folder. That exactly why we add it there.

**Comment by nWidart** [comment]
Oh ok, well I need to change it for one test, where the generated folder cannot be in the fixtures folder of Testbench, and I should set it back to its original state for the second test. If that works...

What is the original state of `$app['path.base']` ? As I needed to set that to:

``` php
$app['path.base'] = realpath(__DIR__ . '/../' . $this->path);
```

**Comment by crynobone** [comment]
This is not getting anywhere useful. If you really insist on doing this. Do whatever you need to do, hack it, add your own fixtures. Totally up to you.

**Comment by nWidart** [comment]
Ok then ... thanks I guess.

Testing this isn't possible then in laravel 5, great. :(

**Comment by crynobone** [comment]
> Testing this isn't possible then in laravel 5, great. :(

Already suggested the possible option, you just choose not to follow it.

- Use the available fixtures folder. We provide it for that exact reason, and clean up once the test is executed.
- Create your own fixtures folder, a complete replicate of `fixture` folder in Testbench repository.
