### ISSUE TITLE
Shouldn't ApplicationTrait::refreshApplication() be called in setUpBeforeClass(), instead of setUp()?

### ISSUE THREAD

**Issue by FractalizeR** [orchestral/testbench#85]
```php
    /**
     * Setup the test environment.
     *
     * @return void
     */
    public function setUp()
    {
        if (! $this->app) {
            $this->refreshApplication();
        }
    }
```

Shouldn't this run in `setUpBeforeClass()` (once per test suite) rather than in` setUp()` (before each test)?

In this case, however, `app` member should be made static since `setUpBeforeClass` is static.

**Comment by crynobone** [comment]
`app` shouldn't be static, and shouldn't inherit between test.

**Comment by FractalizeR** [comment]
Yea, saw that. Sorry for stupid question.
