### ISSUE TITLE
Laravel not finding migrations - sometimes

### ISSUE THREAD

**Issue by nWidart** [orchestral/testbench#87]
Hello,

I'm having a weird issue, where laravel can't find the migrations to run, and thus tests are failing due to those missing tables.

I do have a [method to setup and run](https://github.com/AsgardCms/Menu/blob/develop/Tests/BaseMenuTest.php#L64) migrations, that works on other packages without problems ... just here, it doesn't for some weird reason that I can't seem to figure out.

The migrations [are there](https://github.com/AsgardCms/Menu/tree/develop/Database/Migrations) though. :confused: 

[Example of failing build on travis](https://travis-ci.org/AsgardCms/Menu/jobs/57909650)

I have the same 'issue' on a W.I.P. package locally too :/

Did I miss something stupid or something ?

Thank you!

**Comment by crynobone** [comment]
why not use `--realpath` option.

**Comment by nWidart** [comment]
I don't see that option:

![screen shot 2015-04-10 at 1 33 18 pm](https://cloud.githubusercontent.com/assets/882397/7086882/3aebd134-df86-11e4-8dd5-37a89cabf199.png)

**Comment by crynobone** [comment]
Testbench is not using `Illuminate\Database\MigrationServiceProvider` but instead `Orchestra\Database\MigrationServiceProvider` which has this option. 

<https://github.com/orchestral/testbench/blob/master/tests/DatabaseFixtureTest.php#L30>

**Comment by crynobone** [comment]
![screen shot 2015-04-10 at 8 18 57 pm](https://cloud.githubusercontent.com/assets/172966/7087519/da3859d2-dfbe-11e4-867b-1932ee60457e.png)

**Comment by nWidart** [comment]
Found the error. Was a pretty stupid one, I had a db call in a service provider. 

Sorry for the trouble.

Thanks for that realpath tip, will try that too. :smile:

**Comment by nWidart** [comment]
Crazy, this is happening again on a clean 'package'.
Nothing in service provider or anything in the way.

When I use `--realpath` with the `Database/Migrations` (not correct for real path) option, I get the error:

```
Class 'CreateBlocksTables' not found   
```
Which is normal.

Though when I provide a correct path, using `--path=Database/Migrations` or `--realpath`, I get 

```
Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1 no such table: block__blocks (SQL: select * from "block__blocks" order by "created_at" desc)
```
So it finds the migration, but somehow doesn't execute it ? :/

/lost

**Comment by crynobone** [comment]
1. Don't mess around with `base.path`, as I said many times this could cause issues.
2. Use `--realpath` with `realpath()`.

**Comment by crynobone** [comment]
```php
        $migrationsPath = realpath('../../Database/Migrations');
        $artisan = $this->app->make('Illuminate\Contracts\Console\Kernel');
        // Makes sure the migrations table is created
        $artisan->call('migrate', [
            '--database' => 'sqlite',
            '--realpath' => $migrationsPath,
        ]);
```

**Comment by nWidart** [comment]
Hello,

Oh man, thanks for noticing this path issue! Don't know how I didn't see this. :open_mouth:

Using `$app->setBasePath('/../..');` instead of `base.path`,still gives the same issue.

I've moved the tests up a folder to try.
Using `$app['path.base'] = __DIR__ . '/..';` + `$migrationsPath = 'Database/Migrations';` works. 
It doesn't work though when using `$app->setBasePath('/..');`.
Not setting any base path + using realpath also works.

Moving the tests back into `Integration` folder, and using realpath `$migrationsPath = realpath('Database/Migrations');` , works too.

Thanks a lot for your time and pointing out this path issue!
