### ISSUE TITLE
Artisan command test doesn't honor database settings

### ISSUE THREAD

**Issue by aimeos** [orchestral/testbench#88]
I've created a test for the artisan commands of my Laravel package and provided database settings via the getEnvironmentSetUp() but they aren't used. Instead I'm getting:

SQLSTATE[28000] [1045] Access denied for user 'forge'@'localhost' (using password: NO)

Did I miss something? The test case code is:

```
class SetupCommandTest extends Orchestra\Testbench\TestCase
{
	public function testSetupCommand()
	{
		$this->assertEquals(0, $this->artisan('aimeos:setup', array('site' => 'unittest')));
	}

	protected function getEnvironmentSetUp($app)
	{
		$app['config']->set('database.default', 'testbench');
		$app['config']->set('database.connections.testbench', [
			'driver' => 'mysql',
			'host' => 'localhost',
			'database' => 'laravel'
			'username' => 'root',
			'password' => '',
		]);
	}

	protected function getPackageProviders()
	{
		return ['Aimeos\Shop\ShopServiceProvider'];
	}
}
```

**Comment by crynobone** [comment]
Does your code actually configuration from `config/database.php` or from <https://github.com/aimeos/aimeos-laravel/blob/master/src/config/shop.php#L22-L33>?

**Comment by aimeos** [comment]
You are right, it actually uses the "mysql" database settings. I've changed getEnvironmentSetUp() to
```
$app['config']->set('database.default', 'mysql');
$app['config']->set('database.connections.mysql', [
```
but it still yields the same error. Isn't it possible to use the config() function there?

**Comment by crynobone** [comment]
You could do that, but you need to move `$this->mergeConfigFrom` from `register` to `boot`:

```php
$this->mergeConfigFrom(dirname(dirname(__DIR__)).DIRECTORY_SEPARATOR.'config/shop.php', 'shop');
```

If you stick with the current structure, your code is still loading the default configuration because of this sequence:

```php
$app->make('Illuminate\Foundation\Bootstrap\RegisterProviders')->bootstrap($app);
$this->getEnvironmentSetUp($app);
$app->make('Illuminate\Foundation\Bootstrap\BootProviders')->bootstrap($app);
```

https://github.com/orchestral/testbench/blob/master/src/Traits/ApplicationTrait.php#L176-L180

**Comment by aimeos** [comment]
Cool, that worked! :-)
I have another problem with routing but I will create a new issue for that and you can close this one now. Thank you for your help!

**Comment by crynobone** [comment]
No problem, feel free to post the issue/question when you're ready.
