### ISSUE TITLE
getRoutes() not found in Router mock object

### ISSUE THREAD

**Issue by aimeos** [orchestral/testbench#89]
One of my tests fails with this message:
```
1) ViewTest::testCreateWithLocale
BadMethodCallException: Method Mockery_0_Illuminate_Routing_Router::getRoutes() does not exist on this mock object

.../aimeos-laravel/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php:45
.../aimeos-laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:290
.../aimeos-laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:773
.../aimeos-laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:656
.../aimeos-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:642
.../aimeos-laravel/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:53
.../aimeos-laravel/src/Aimeos/Shop/Base/View.php:54
.../aimeos-laravel/tests/Base/ViewTest.php:33
```
It worked when the package was part of an application but since using the testbench package it fails. What could be the cause for this?

The test code is available at https://github.com/aimeos/aimeos-laravel/blob/master/tests/Base/ViewTest.php#L15-L34

**Comment by crynobone** [comment]
That would be hard to test:

1. You could convert this test to actually run a route using `$this->call()`, the API is the same with <http://laravel.com/docs/5.0/testing#calling-routes-from-tests>
2. You could actually reduce the dependency from `Route` facade and instead directly inject the resolving object as `View` constructor (with this, you can even skip using `Orchestra\Testbench\TestCase` and instead use `PHPUnit_Framework_TestCase`.

**Comment by aimeos** [comment]
I'm not sure if I understand the problem correctly. To me it seems like ```app('url')``` can't create an ```\Illuminate\Contracts\Routing\UrlGenerator``` object. The route facade is only used to satisfy the method calls in
* https://github.com/aimeos/aimeos-laravel/blob/master/src/Aimeos/Shop/Base/View.php#L35-L36
* https://github.com/aimeos/aimeos-laravel/blob/master/src/Aimeos/Shop/Base/View.php#L90-L98

The test does actually nothing with the UrlGenerator object and neither any code inside the View class calls a method of the UrlGenerator that would access Route objects or do I understand something wrong?

**Comment by crynobone** [comment]
> The route facade is only used to satisfy the method calls in

When you use `Route::shouldReceive()`, it would first try to get the resolved instance of `app('router')` and replaced it with a mocked instance, now this would work fine but once `url` required `$router->getRoutes()` it can't find one on your mocked instance in `RoutingServiceProvider`.

Basically it never was easy to mock `router` or `request` instance, which is why there's a lots of helper to run routing testcase for Laravel.

**Comment by aimeos** [comment]
OK, got it. I've removed all ```Route::*``` calls in the test to get it working now.
Are these kind errors related to this problem:
```
1) AccountControllerTest::testActions
InvalidArgumentException: Action Aimeos\Shop\Controller\AccountController@indexAction not defined.

.../aimeos-laravel/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:561
.../aimeos-laravel/vendor/orchestra/testbench/src/Traits/ClientTrait.php:77
.../aimeos-laravel/tests/Controller/AccountControllerTest.php:7
```

**Comment by crynobone** [comment]
As for above error it can be solved by removing `\` prefix as it not needed in this case:

```php
Route::match( array( 'GET', 'POST' ), 'myaccount', array(
	'middleware' => 'auth',
	'as' => 'aimeos_shop_account',
	'uses' => 'Aimeos\Shop\Controller\AccountController@indexAction'
));
```

However you would still have an issue with `"middleware" => "auth"` as this middleware only exist inside the application context. Testbench doesn't include this by default because we can't guarantee that this middleware would always exist (a user could delete it on purpose etc).

**Comment by crynobone** [comment]
To solve auth middleware, you can always swap the basic `Orchestra\Testbench\Http\Kernel` with something that fits your need. https://github.com/orchestral/testbench#overriding-http-kernel

**Comment by aimeos** [comment]
I've tried your suggestion and removed the first backslash from the values in ```uses``` but that made no difference. Anything else I could try?

**Comment by crynobone** [comment]
```
aimeos-laravel git:master ✗ phpunit tests/Controller/AccountControllerTest.php
PHP Strict standards:  Declaration of AccountControllerTest::getPackageProviders() should be compatible with Orchestra\Testbench\TestCase::getPackageProviders($app) in /Users/crynobone/aimeos-laravel/tests/Controller/AccountControllerTest.php on line 6
PHP Stack trace:
PHP   1. {main}() /Users/crynobone/.composer/vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /Users/crynobone/.composer/vendor/phpunit/phpunit/phpunit:36
PHP   3. PHPUnit_TextUI_Command->run() /Users/crynobone/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:105
PHP   4. PHPUnit_Runner_BaseTestRunner->getTest() /Users/crynobone/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:127
PHP   5. PHPUnit_Runner_BaseTestRunner->loadSuiteClass() /Users/crynobone/.composer/vendor/phpunit/phpunit/src/Runner/BaseTestRunner.php:72
PHP   6. PHPUnit_Runner_StandardTestSuiteLoader->load() /Users/crynobone/.composer/vendor/phpunit/phpunit/src/Runner/BaseTestRunner.php:127
PHP   7. PHPUnit_Util_Fileloader::checkAndLoad() /Users/crynobone/.composer/vendor/phpunit/phpunit/src/Runner/StandardTestSuiteLoader.php:43
PHP   8. PHPUnit_Util_Fileloader::load() /Users/crynobone/.composer/vendor/phpunit/phpunit/src/Util/Fileloader.php:42
PHP   9. include_once() /Users/crynobone/.composer/vendor/phpunit/phpunit/src/Util/Fileloader.php:58

Strict standards: Declaration of AccountControllerTest::getPackageProviders() should be compatible with Orchestra\Testbench\TestCase::getPackageProviders($app) in /Users/crynobone/aimeos-laravel/tests/Controller/AccountControllerTest.php on line 6

Call Stack:
    0.0003     231360   1. {main}() /Users/crynobone/.composer/vendor/phpunit/phpunit/phpunit:0
    0.0089     730480   2. PHPUnit_TextUI_Command::main() /Users/crynobone/.composer/vendor/phpunit/phpunit/phpunit:36
    0.0089     731112   3. PHPUnit_TextUI_Command->run() /Users/crynobone/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:105
    0.0298    2240128   4. PHPUnit_Runner_BaseTestRunner->getTest() /Users/crynobone/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:127
    0.0298    2240176   5. PHPUnit_Runner_BaseTestRunner->loadSuiteClass() /Users/crynobone/.composer/vendor/phpunit/phpunit/src/Runner/BaseTestRunner.php:72
    0.0305    2264360   6. PHPUnit_Runner_StandardTestSuiteLoader->load() /Users/crynobone/.composer/vendor/phpunit/phpunit/src/Runner/BaseTestRunner.php:127
    0.0305    2296960   7. PHPUnit_Util_Fileloader::checkAndLoad() /Users/crynobone/.composer/vendor/phpunit/phpunit/src/Runner/StandardTestSuiteLoader.php:43
    0.0306    2297104   8. PHPUnit_Util_Fileloader::load() /Users/crynobone/.composer/vendor/phpunit/phpunit/src/Util/Fileloader.php:42
    0.0307    2307792   9. include_once('/Users/crynobone/aimeos-laravel/tests/Controller/AccountControllerTest.php') /Users/crynobone/.composer/vendor/phpunit/phpunit/src/Util/Fileloader.php:58

PHPUnit 4.6.2 by Sebastian Bergmann and contributors.

Configuration read from /Users/crynobone/aimeos-laravel/phpunit.xml

E

Time: 153 ms, Memory: 10.75Mb

There was 1 error:

1) AccountControllerTest::testActions
ErrorException: call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Auth\Guard' does not have a method 'handle'

/Users/crynobone/aimeos-laravel/vendor/laravel/framework/src/Illuminate/Support/Manager.php:139
/Users/crynobone/aimeos-laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:125
/Users/crynobone/aimeos-laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:125
/Users/crynobone/aimeos-laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:101
/Users/crynobone/aimeos-laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php:694
/Users/crynobone/aimeos-laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php:661
/Users/crynobone/aimeos-laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php:619
/Users/crynobone/aimeos-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:214
/Users/crynobone/aimeos-laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:141
/Users/crynobone/aimeos-laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:101
/Users/crynobone/aimeos-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:115
/Users/crynobone/aimeos-laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:84
/Users/crynobone/aimeos-laravel/vendor/orchestra/testbench/src/Traits/ClientTrait.php:39
/Users/crynobone/aimeos-laravel/vendor/orchestra/testbench/src/Traits/ClientTrait.php:79
/Users/crynobone/aimeos-laravel/tests/Controller/AccountControllerTest.php:9

FAILURES!
Tests: 1, Assertions: 0, Errors: 1.
```

**Comment by crynobone** [comment]
> ErrorException: call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Auth\Guard' does not have a method 'handle'

This is the part where it tried to resolved "auth" middleware, but since it not available it tried to resolve "auth" from the IoC which would give `Illuminate\Auth\Guard`.

**Comment by aimeos** [comment]
I've removed the "auth" middleware but still all calls to ```Aimeos\Shop\Controller\...Controller@...Action``` fail (not only the protected ones from the AccountController). The code in the GitHub repository is updated so you can see what I mean.

For the tests I've used Laravel 5.0.23 and Testbench 3.0.* but using dev-master doesn't make a difference.

**Comment by crynobone** [comment]
```
1) AccountControllerTest::testActions
MW_DB_Exception: SQLSTATE[HY000] [1045] Access denied for user 'forge'@'localhost' (using password: NO)

/Users/crynobone/aimeos-laravel/vendor/arcavias/arcavias-core/lib/mwlib/src/MW/DB/Manager/PDO.php:86
/Users/crynobone/aimeos-laravel/vendor/arcavias/arcavias-core/lib/mshoplib/src/MShop/Locale/Manager/Site/Default.php:496
```

What's inside Site/Default that require a PDO connection, it obvious that would failed if the package try to make a db connection when the test case doesn't do any db setup.

**Comment by aimeos** [comment]
You are right, I forgot to adapt the ```getEnvironmentSetUp()``` methods in the the controller test classes and the error messages swallowed the real cause of the problem!

There's one more thing I'm struggling with: My package tries to extend from an ```app.blade.php``` template which is not available when using testbench. Can I provide one as fixture or how could I cope with that?

**Comment by crynobone** [comment]
You could use `https://github.com/laravel/framework/blob/5.0/src/Illuminate/View/Factory.php#L712` e.g: `View::addLocation('tests/fixtures/views')` to include that location when View try to resolved. 

Otherwise you could look into adding a complete base app skeleton fixture such as https://github.com/orchestral/testing (I use this to test Orchestra Platform application).

**Comment by aimeos** [comment]
I got the test working now but only one by one:
phpunit --filter=testTermsAction -> OK
phpunit -> testTermsAction fails

The error is still the same:
```
12) PageControllerTest::testTermsAction
InvalidArgumentException: Action Aimeos\Shop\Controller\PageController@termsAction not defined.
.../aimeos-laravel/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:561
.../aimeos-laravel/vendor/orchestra/testbench/src/Traits/ClientTrait.php:77
.../aimeos-laravel/tests/Controller/PageControllerTest.php:21
```
Only the first controller/action test succeeds, all subsequent ones are failing. Have you seen this before or do I still make a mistake?

**Comment by crynobone** [comment]
Don't use `require_once "routes.php";`, as the code intended, it would only load once.

**Comment by aimeos** [comment]
You are great! :-)
Thank you very much
