### ISSUE TITLE
Service provider not being loaded

### ISSUE THREAD

**Issue by kirkbushell** [orchestral/testbench#91]
Hey there!

tbh I'm not sure this is an actual issue, but I'm having problems getting my service provider recognised. It appears to load other providers, but not mine (aka, register method never gets called).

This is how I've setup the test case class:

```php
<?php
namespace Tests;

use Mockery as m;

class TestCase extends \Orchestra\Testbench\TestCase
{
    public function tearDown()
    {
        parent::tearDown();
        m::close();
    }

    public function setUp()
    {
        parent::setUp();
        $this->init();
    }

    protected function init()
    {
        // Stub/template method - overloadable by children
    }

    protected function getPackageProviders()
    {
        return [
            'Collective\Html\HtmlServiceProvider',
            'FloatingPoint\Stylist\StylistServiceProvider',
        ];
    }

    protected function getPackageAliases($app)
    {
        return [
            'Stylist' => 'FloatingPoint\Stylist\Facades\StylistFacade',
            'Theme' => 'FloatingPoint\Stylist\Facades\ThemeFacade',
        ];
    }
}
```

Then in the StylistServiceProvider:

```php
<?php
namespace FloatingPoint\Stylist;

use Cache;
use Config;
use FloatingPoint\Stylist\Html\ThemeHtmlBuilder;
use FloatingPoint\Stylist\Theme\Loader;
use FloatingPoint\Stylist\Theme\Stylist;
use Illuminate\Support\AggregateServiceProvider;
use Illuminate\Foundation\AliasLoader;

class StylistServiceProvider extends AggregateServiceProvider
{
    /**
     * Stylist provides the HtmlServiceProvider for ease-of-use.
     *
     * @var array
     */
    protected $providers = [
        'Collective\Html\HtmlServiceProvider'
    ];

    /**
     * Registers the various bindings required by other packages.
     */
    public function register()
    {
        parent::register();

        $this->registerConfiguration();
        $this->registerStylist();
        $this->registerAliases();
        $this->registerThemeBuilder();
        $this->registerCommands();
    }
```

I thought this might have something to do with the aggregate service provider, so I tried setting it to just a normal one, but unfortunately no change. What's really odd is that if I register my service provider first - it works, but then the HtmlServiceProvider isn't loaded. Thing is, the StylistServiceProvider is providing the HtmlServiceProvider - so I shouldn't need to provide both. If anything, that's probably a little confusing in its own right.

Any ideas?

**Comment by crynobone** [comment]
I don't see why a basic service provider using `Illuminate\Support\AggregateServiceProvider` would failed. It might be something else.

```php
$this->registerConfiguration();
$this->registerStylist();
$this->registerAliases();
$this->registerThemeBuilder();
$this->registerCommands();
```

Try troubleshooting each of the register process, or do you have any error log that could be useful?

**Comment by kirkbushell** [comment]
@crynobone it doesn't get that far - the service provider is never registered.

**Comment by crynobone** [comment]
6df04e3 shows that a basic aggregate service is loaded with Testbench. So I would think this is something else.

**Comment by kirkbushell** [comment]
Yeah it's not the aggregate service provider. Have you tried it with more than one service provider - as that appears to be the issue...

**Comment by nWidart** [comment]
I get the following error when trying to run your tests:

![screen shot 2015-06-09 at 8 01 26 pm](https://cloud.githubusercontent.com/assets/882397/8065701/766335f4-0ee3-11e5-8ae9-d7066e637fe3.png)

Using Testbench 3.1, laravel 5.1

**Comment by crynobone** [comment]
How is that related?

**Comment by nWidart** [comment]
It's related because it's the same package.

Also, this might help ..

![screen shot 2015-06-09 at 8 11 37 pm](https://cloud.githubusercontent.com/assets/882397/8065746/d0ff88c8-0ee3-11e5-9bde-121676bce4ee.png)

**Comment by crynobone** [comment]
`hasExceptionOnOutput()` is not related to the example code shown so far. Seriously I can't solve this issue unless there a clear picture what is wrong with it. 

`Class stylist doesn't found` could be related to service provider not registered, if anything.

**Comment by nWidart** [comment]
I'm now on the same branch of Kirk.. He has his Service provider loaded, and `Collective\Html\HtmlServiceProvider`. Though we still get 

```
  Class 'Collective\Html\HtmlServiceProvider' not found    
```
You can see this here: https://github.com/floatingpointsoftware/stylist/blob/feature/test-fixes/tests/TestCase.php

**Comment by kirkbushell** [comment]
Just to let you know that I was able to get my tests to pass, but tbh I'm not sure how or why it was broken to begin with. It has something to do with service provider loading, but I don't think it's an issue unique to TestBench. As a result of that, I'll close this as I don't think it's an issue iwth the library.

Thanks for your time @crynobone and @nWidart :)

**Comment by crynobone** [comment]
@kirkbushell check out the PR I submit to your repository.
