### ISSUE TITLE
RuntimeException: No supported encrypter found. The cipher and / or key length are invalid.

### ISSUE THREAD

**Issue by aedart** [orchestral/testbench#93]
Laravel's Encrypter class fails, because of too weak "random" string, in the app.php configuration (in fixtures), when the default AES-256-CBC cipher is being used.

In the current version, "SomeRandomString" is being used as the default APP_KEY value. This should be changed to something else...

Perhaps a key should / could be generated, before the application is created, if the default key is set to "SomeRandomString".

Additional information about this issue, can be found here: http://laravel.io/forum/06-09-2015-no-supported-encrypter-found-the-cipher-and-or-key-length-are-invalid

**Comment by GrahamCampbell** [comment]
You need a 32 byte encryption key, and you're sorted.

**Comment by crynobone** [comment]
See <https://github.com/orchestral/testbench#no-supported-encrypter-found-the-cipher-and--or-key-length-are-invalid>

Thank for the report.

**Comment by aledmb** [comment]
I had this issue randomly, sometimes it worked, sometimes not.

Thanks to @GrahamCampbell for pointing me to the solution. ;)

https://github.com/laravel/framework/issues/13764#issuecomment-239349336

**Comment by crynobone** [comment]
@aledmb I don't see how this is suitable for `orchestra/testbench`.

**Comment by aledmb** [comment]
@crynobone yeah, sorry for crossing your path, I just wanted to point out how it helped me solve it on Laravel, so maybe that's gives a clue for anyone on this side. ;)

**Comment by crynobone** [comment]
> so maybe that gives a clue for someone on this side. 

Testbench are used for purely for testing, therefore using `config:cache` would **JUST** cause more problem.

**Comment by siempay** [comment]
Hi guys! I have the same problem and I figured it out with this `tail -f storage/logs/laravel.log` because the error comes randomly and especially on ajax requests, but how to solve this one time and for ever?

**Comment by crynobone** [comment]
Locking this issue since questions isn't related to Testbench
