### ISSUE TITLE
Laravel views not found

### ISSUE THREAD

**Issue by nWidart** [orchestral/testbench#97]
Hello,

On an application I'm working on I have some events that send out emails in the handlers. 
I've set the `mail.pretend` option to true in the `getEnvironmentSetUp` method, but laravel opens the view.

I'm getting the following error when it tries to open a view (in phpunit response):

```
View [my.view.name] not found.
```

Is there something I can do ?

Sorry if this is a silly question.

Thanks!

**Comment by crynobone** [comment]
You need to add a new location for your views. <https://github.com/laravel/framework/blob/5.1/src/Illuminate/View/Factory.php#L685>

e.g:

```php
View::addLocation(__DIR__.'/stubs/views');
```

**Comment by nWidart** [comment]
Oh, of course! 

Thanks a lot for the quick response! :smile:

**Comment by JulienTant** [comment]
@crynobone : your reactivity is impressive. I'd like to thank your for what you bring to the community :) (not the best place, i know)

**Comment by crynobone** [comment]
Thank @nWidart @JulienTant 

/me on my working hours right now (6pm) with Slack notification :)

**Comment by GrahamCampbell** [comment]
> mail.pretend

That config option is deprecated in 5.1 and was removed in 5.2.

**Comment by GrahamCampbell** [comment]
Was replaced by the log mail driver introduced in 5.0.

**Comment by nWidart** [comment]
Good to know, thanks @GrahamCampbell .

**Comment by nWidart** [comment]
Too bad there isn't an option in Laravel to disable emails completely in testing environment, loading these views slows the tests considerably down.

**Comment by GrahamCampbell** [comment]
There is a way. If you send emails by using event handlers, then you can run the tests with events disabled.

**Comment by nWidart** [comment]
True, indeed I send emails via event handlers, but I also use event handlers for other stuff. For instance in this case I set a specific property on a model in the handler class, or just other logic not related to emails.

So disabling events is not really an option.

**Comment by GrahamCampbell** [comment]
Maybe you need to just rebind the mailer object then?

**Comment by nWidart** [comment]
Hm that's a good idea, thanks. :smile:
