### ISSUE TITLE
How to test artisan command questions?

### ISSUE THREAD

**Issue by acoustep** [orchestral/testbench#98]
Hi,

I have a console command that requires the user to confirm overwriting files if they already exist:

```php
// ...
if($this->confirm('Overwrite '.$file_path.'? [y|N]'))
// ...
```

I have a ```--force``` option which I can use for testing most cases, however, I would like to test that the confirm option is working as intended, too.

This is what I have so far

```php
/**
 * @test
 */
public function overwrite_if_asked()
{
    $command = $this->artisan('entrust-gui:models', [
        'User',
        '--path' => $this->root->url().'/models',
       // '--force' => 'true',
    ]);
}
```

Currently the test hangs due to waiting for a response.

**Comment by GrahamCampbell** [comment]
You're going to need to change the input object used internally.

**Comment by crynobone** [comment]
Testbench doesn't provide any facilty to help you unit test commands, nor does Laravel.

I did try to come out with some wrapper but to be honest it a huge mess. Try  http://marekkalnik.tumblr.com/post/32601882836/symfony2-testing-interactive-console-command

**Comment by acoustep** [comment]
Thank you for the fast responses!

I will see if I can mock the input object.

Closing for now.

**Comment by GrahamCampbell** [comment]
Or, rather than mocking, just make your own class that implements the interface. That might be easier, and would run much faster than mocking using mockery for example.

**Comment by acoustep** [comment]
Thanks, Graham. 

My main concern for now is how to inject the class - I will have a play around and see what I can do.
