### ISSUE TITLE
Lumen support

### ISSUE THREAD

**Issue by tacone** [orchestral/testbench#99]
Out of curiosity: does the testbench support Lumen? If not, is Lumen support planned?

**Comment by crynobone** [comment]
For testing lumen packages? Yeah we could actually do that.

**Comment by tacone** [comment]
Right now, I'm testing some packages in Travis CI with a script that downloads a whole Laravel of a given version. I am currently in the process to switch to orchestral/testbench because it seems to work much better.

Everything good and well, but since my last baby project is a API builder, I began to wonder if Lumen is supported or not. I have no immediate need, but I suggest you to take it into consideration. I may be able to test my packages with all the Lumen versions along with Laravel's, and that would be just awesome.

**Comment by crynobone** [comment]
We can do it, but bare in mind that we need to include different set of `TestCase` and possibly `ApplicationTrait` because Laravel and Lumen has different bootstrapping process.

**Comment by tacone** [comment]
Ok. If I get to make to the end of this new package that I'm developing, I'll be very happy to test the Lumen support.

In the meantime, keep up the good work, I'll watch this bug. :smile:

**Comment by crynobone** [comment]
An update on this, this is not possible at the moment, because just as soon as we include `"laravel/lumen-framework"`, PHP would throw duplicate class detected under `Illuminate\Foundation` which exist in both `"laravel/framework"` and `"laravel/lumen-framework"`. The alternative is to build a separate package for developing on lumen but that might not seem ideal.

**Comment by tacone** [comment]
First off, thank you so much for investigating this issue. If you happen to be able to share the broken branch somewhere I would happily clone it for future reference.

**Comment by crynobone** [comment]
Combining both framework will generate exception due to class name duplication.

```json
{
     "require: {
         "laravel/framework": "~5.1",
         "laravel/lumen-framework": "~5.1"
     }
}
```

**Comment by lvidal1** [comment]
I'd been working in several lumen packages I'd like to apply testing on them. Will be support for lumen framework in the future?

**Comment by crynobone** [comment]
> Will be support for lumen framework in the future?

Not on any of my plan.

**Comment by ssi-anik** [comment]
Just in case someone reaches here. You can check it out. 

https://github.com/ssi-anik/testbench-lumen
